# Generated by Django 4.2.13 on 2025-10-02 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_passwordchangecode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Derogation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="datecreation",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        db_column="dateexpiration", verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        db_column="motif",
                        help_text="Motif détaillé de la dérogation.",
                        verbose_name="Motif",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_column="utilisee",
                        default=False,
                        help_text="Indique si la dérogation a déjà été consommée.",
                        verbose_name="Utilisée",
                    ),
                ),
                (
                    "user_beneficiaire",
                    models.ForeignKey(
                        db_column="idutilisateurbeneficiaire",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derogations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur bénéficiaire",
                    ),
                ),
                (
                    "user_habilite",
                    models.ForeignKey(
                        db_column="idutilisateurhabilite",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derogations_accordees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur habilité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dérogation",
                "verbose_name_plural": "Dérogations",
                "db_table": "stdderogation",
                "permissions": [
                    ("can_accord_derogation", "Peut accorder une dérogation")
                ],
            },
        ),
    ]
