# Generated by Django 4.1.4 on 2023-03-21 09:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuration_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "IdClient",
                    models.AutoField(
                        db_column="idclient", primary_key=True, serialize=False
                    ),
                ),
                ("Nom", models.CharField(db_column="nom", max_length=60)),
                (
                    "Prenoms",
                    models.CharField(
                        blank=True, db_column="prenoms", max_length=60, null=True
                    ),
                ),
                (
                    "Vip",
                    models.CharField(
                        db_column="vip",
                        max_length=1,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("Adresse1", models.CharField(db_column="adresse1", max_length=100)),
                (
                    "Adresse2",
                    models.CharField(
                        blank=True, db_column="adresse2", max_length=100, null=True
                    ),
                ),
                (
                    "IdVille",
                    models.IntegerField(blank=True, db_column="idville", null=True),
                ),
                ("Telephone", models.CharField(db_column="telephone", max_length=20)),
                (
                    "Mobile",
                    models.CharField(db_column="mobile", max_length=20, unique=True),
                ),
                (
                    "Fax",
                    models.CharField(
                        blank=True, db_column="fax", max_length=20, null=True
                    ),
                ),
                (
                    "Fixe",
                    models.CharField(
                        blank=True, db_column="fixe", max_length=20, null=True
                    ),
                ),
                (
                    "IdQualite",
                    models.IntegerField(blank=True, db_column="idqualite", null=True),
                ),
                (
                    "IdProfession",
                    models.IntegerField(
                        blank=True, db_column="idprofession", null=True
                    ),
                ),
                (
                    "Responsable",
                    models.CharField(
                        blank=True, db_column="responsable", max_length=120, null=True
                    ),
                ),
                (
                    "Email",
                    models.EmailField(db_column="email", max_length=254, unique=True),
                ),
                (
                    "Particulier",
                    models.CharField(
                        db_column="particulier",
                        max_length=1,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("DateMaj", models.DateTimeField(auto_now=True, db_column="datemaj")),
                ("CniPat", models.CharField(db_column="cnipat", max_length=50)),
                (
                    "DateCreation",
                    models.DateTimeField(auto_now_add=True, db_column="datecreation"),
                ),
                (
                    "Statut",
                    models.CharField(
                        db_column="statut",
                        max_length=1,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "Matricule",
                    models.CharField(
                        blank=True, db_column="matricule", max_length=50, null=True
                    ),
                ),
                (
                    "IdOperateur",
                    models.IntegerField(blank=True, db_column="idoperateur", null=True),
                ),
                (
                    "Rib",
                    models.CharField(
                        blank=True,
                        db_column="rib",
                        max_length=24,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(24)],
                    ),
                ),
                (
                    "DateNaissance",
                    models.DateField(blank=True, db_column="datenaissance", null=True),
                ),
                (
                    "Reconquete",
                    models.CharField(
                        blank=True,
                        db_column="reconquete",
                        max_length=1,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "IdProfil",
                    models.IntegerField(blank=True, db_column="idprofil", null=True),
                ),
                (
                    "CreeCie",
                    models.CharField(
                        db_column="creecie",
                        max_length=1,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "CodePostal",
                    models.CharField(
                        blank=True, db_column="codepostal", max_length=15, null=True
                    ),
                ),
                (
                    "IdCategorie",
                    models.IntegerField(blank=True, db_column="idcategorie", null=True),
                ),
                (
                    "ExonereDeTaxes",
                    models.BooleanField(
                        blank=True, db_column="exoneredetaxe", null=True
                    ),
                ),
                (
                    "ExonereDeAccess",
                    models.BooleanField(
                        blank=True, db_column="exoneredeaccess", null=True
                    ),
                ),
                (
                    "NumeroCompte",
                    models.CharField(
                        db_column="numerocompte", default="XXXXXXX", max_length=16
                    ),
                ),
                (
                    "Solde",
                    models.DecimalField(
                        db_column="solde", decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "idtypeassure",
                    models.ForeignKey(
                        db_column="idtypeassure",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.typeassure",
                        verbose_name="Type Assuré",
                    ),
                ),
                (
                    "idtypeclient",
                    models.ForeignKey(
                        db_column="idtypesouscripteur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.typesouscripteur",
                        verbose_name="Type Souscripteur",
                    ),
                ),
            ],
            options={
                "db_table": "stdclient",
            },
        ),
    ]
