# Generated by Django 4.1.4 on 2023-03-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="ExonereDeTaxes",
            field=models.BooleanField(
                blank=True, db_column="exoneredetaxes", null=True
            ),
        ),
    ]
