# Generated by Django 4.1.4 on 2023-04-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_client_exoneredetaxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Email",
            field=models.EmailField(
                blank=True, db_column="email", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="Mobile",
            field=models.CharField(
                blank=True, db_column="mobile", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="NumeroCompte",
            field=models.CharField(
                db_column="numerocompte", default="XXXXXXX", max_length=20
            ),
        ),
    ]
