# Generated by Django 4.1.4 on 2023-05-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_client_email_alter_client_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Adresse1",
            field=models.CharField(
                blank=True, db_column="adresse1", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="Telephone",
            field=models.CharField(
                blank=True, db_column="telephone", max_length=20, null=True
            ),
        ),
    ]
