# Generated by Django 4.1.4 on 2023-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_alter_client_adresse1_alter_client_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="DateUtilisation",
            field=models.DateTimeField(
                auto_now=True, db_column="dateutilisation", null=True
            ),
        ),
    ]
