# Generated by Django 4.1.4 on 2023-05-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_client_dateutilisation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="DateUtilisation",
        ),
    ]
