# Generated by Django 4.1.4 on 2023-05-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_remove_client_dateutilisation"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="LieuNaissance",
            field=models.CharField(
                blank=True, db_column="lieunaissance", max_length=100, null=True
            ),
        ),
    ]
