# Generated by Django 4.2.5 on 2024-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_client_lieunaissance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="IdSecteurActivite",
            field=models.IntegerField(
                blank=True, db_column="idsecteuractivite", null=True
            ),
        ),
    ]
