# Generated by Django 4.2.5 on 2024-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_client_idsecteuractivite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="CniPat",
            field=models.CharField(
                blank=True, db_column="cnipat", max_length=50, null=True
            ),
        ),
    ]
