# Generated by Django 4.2.13 on 2024-09-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_alter_client_cnipat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Nom",
            field=models.CharField(db_column="nom", max_length=150),
        ),
        migrations.AlterField(
            model_name="client",
            name="Prenoms",
            field=models.CharField(
                blank=True, db_column="prenoms", max_length=150, null=True
            ),
        ),
    ]
