# Generated by Django 4.2.13 on 2024-09-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_client_nom_alter_client_prenoms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Matricule",
            field=models.CharField(
                blank=True, db_column="matricule", max_length=50, null=True, unique=True
            ),
        ),
    ]
