# Generated by Django 4.2.13 on 2026-01-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_alter_client_matricule"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Avoir",
            field=models.DecimalField(
                db_column="avoir",
                decimal_places=4,
                default=0.0,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="Solde",
            field=models.DecimalField(
                db_column="solde",
                decimal_places=4,
                default=0.0,
                max_digits=19,
                null=True,
            ),
        ),
    ]
