# Generated by Django 4.2.13 on 2026-01-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_client_avoir_alter_client_solde"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="Fonction",
            field=models.CharField(blank=True, default="", max_length=80, null=True),
        ),
    ]
