# Generated by Django 4.2.13 on 2026-02-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_client_fonction"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="cle_unique",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Identifiant unique pour détecter les doublons",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Clé unique",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="numero_assure",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Numéro unique généré automatiquement. Format: ASS-YYYYMM-NNNN",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Numéro d'assuré",
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["cle_unique"], name="idx_client_cle_unique"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["numero_assure"], name="idx_client_numero_assure"
            ),
        ),
    ]
