# Generated by Django 4.2.13 on 2026-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0014_client_cle_unique_client_numero_assure_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="Fonction",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
