# Generated by Django 4.2.5 on 2024-06-02 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DistripayTransaction",
            fields=[
                (
                    "id_transaction",
                    models.UUIDField(
                        db_column="idtransaction",
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Transaction",
                    ),
                ),
                (
                    "montant_initiation",
                    models.IntegerField(
                        db_column="montantinitiation", verbose_name="Montant Initiation"
                    ),
                ),
                (
                    "devise_initiation",
                    models.CharField(
                        db_column="deviseinitiation",
                        max_length=3,
                        verbose_name="Devise",
                    ),
                ),
                (
                    "description_intiation",
                    models.TextField(
                        db_column="descriptioninitiation",
                        max_length=255,
                        verbose_name="Description Initiation",
                    ),
                ),
                (
                    "code_erreur_initiation",
                    models.CharField(
                        blank=True,
                        db_column="codeerreurinitiation",
                        max_length=3,
                        null=True,
                        verbose_name="Code Erreur Initiation",
                    ),
                ),
                (
                    "message_initiation",
                    models.CharField(
                        blank=True,
                        db_column="messageinitiation",
                        max_length=100,
                        null=True,
                        verbose_name="Message Initiation",
                    ),
                ),
                (
                    "token_paiement",
                    models.CharField(
                        blank=True,
                        db_column="tokenpaiement",
                        max_length=255,
                        null=True,
                        verbose_name="Token de paiement",
                    ),
                ),
                (
                    "url_paiement",
                    models.CharField(
                        blank=True,
                        db_column="urlpaiement",
                        max_length=2000,
                        null=True,
                        verbose_name="URL de paiement",
                    ),
                ),
                (
                    "api_response_id_initiation",
                    models.CharField(
                        blank=True,
                        db_column="apiresponseidinitiation",
                        max_length=50,
                        null=True,
                        verbose_name="API Response ID Initiation",
                    ),
                ),
                (
                    "code_erreur_transaction",
                    models.CharField(
                        blank=True,
                        db_column="codeerreurtransaction",
                        max_length=3,
                        null=True,
                        verbose_name="Code Transaction",
                    ),
                ),
                (
                    "message_transaction",
                    models.CharField(
                        blank=True,
                        db_column="messagetransaction",
                        max_length=100,
                        null=True,
                        verbose_name="Message Transaction",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        blank=True,
                        db_column="statut",
                        max_length=50,
                        null=True,
                        verbose_name="Statut Transaction",
                    ),
                ),
                (
                    "montant_transaction",
                    models.IntegerField(
                        blank=True,
                        db_column="montanttransaction",
                        null=True,
                        verbose_name="Montant Transaction",
                    ),
                ),
                (
                    "devise_transaction",
                    models.CharField(
                        blank=True,
                        db_column="devisetransaction",
                        max_length=3,
                        null=True,
                        verbose_name="Devise Transaction",
                    ),
                ),
                (
                    "methode_paiement",
                    models.CharField(
                        blank=True,
                        db_column="methodepaiement",
                        max_length=30,
                        null=True,
                        verbose_name="Methode Paiement",
                    ),
                ),
                (
                    "description_transaction",
                    models.CharField(
                        blank=True,
                        db_column="descriptiontransaction",
                        max_length=255,
                        null=True,
                        verbose_name="Description Transaction",
                    ),
                ),
                (
                    "metadata",
                    models.CharField(
                        blank=True,
                        db_column="metadata",
                        max_length=255,
                        null=True,
                        verbose_name="Metadata Transaction",
                    ),
                ),
                (
                    "id_operateur",
                    models.CharField(
                        blank=True,
                        db_column="idoperateur",
                        max_length=30,
                        null=True,
                        verbose_name="ID Operateur",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(
                        blank=True,
                        db_column="datepaiement",
                        null=True,
                        verbose_name="Date Paiement",
                    ),
                ),
                (
                    "date_validite_fonds",
                    models.DateTimeField(
                        blank=True,
                        db_column="datevaliditefonds",
                        null=True,
                        verbose_name="Date Validité Fonds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction DISTRIPAY",
                "verbose_name_plural": "Transactions DISTRIPAY",
                "db_table": "stddistripaytransaction",
            },
        ),
    ]
