# Generated by Django 4.2.5 on 2024-06-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distripaytransaction",
            old_name="description_intiation",
            new_name="description_initiation",
        ),
        migrations.AddField(
            model_name="distripaytransaction",
            name="terminee",
            field=models.BooleanField(
                blank=True,
                db_column="terminee",
                default=False,
                null=True,
                verbose_name="Transaction terminée",
            ),
        ),
    ]
