# Generated by Django 4.2.13 on 2024-06-21 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment",
            "0002_rename_description_intiation_distripaytransaction_description_initiation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distripaytransaction",
            name="date_creation",
            field=models.DateTimeField(
                blank=True,
                db_column="datecreation",
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Date Création",
            ),
        ),
    ]
