"""
Django settings for uranus project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import datetime

# from dotenv import load_dotenv
from dotenv import dotenv_values
import os

# load_dotenv()
uranus_backend_config = dotenv_values(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-7p_#04)qobmvg@-b&^ljb&f@cp3fklnmq88^7pjcx$_dw7+w=q'
# SECRET_KEY = os.environ.get("SECRET_KEY")
SECRET_KEY = uranus_backend_config.get("SECRET_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# DEBUG = int(os.environ.get("DEBUG", default=0))
DEBUG = int(uranus_backend_config.get("DEBUG", 0))

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = uranus_backend_config.get("DJANGO_ALLOWED_HOSTS", "").split(" ")

DB_NAME = uranus_backend_config.get("DB_NAME", "")
DB_USER = uranus_backend_config.get("DB_USER", "")
DB_PASSWORD = uranus_backend_config.get("DB_PASSWORD", "")
DB_HOST = uranus_backend_config.get("DB_HOST", "localhost")
DB_PORT = uranus_backend_config.get("DB_PORT", 5432)

# SMTP Server
SMTP_HOST = uranus_backend_config.get("SMTP_HOST")
SMTP_PORT = uranus_backend_config.get("SMTP_PORT")

# Email credentials
SENDER_EMAIL = uranus_backend_config.get("SENDER_EMAIL")
SENDER_EMAIL_PASSWORD = uranus_backend_config.get("SENDER_EMAIL_PASSWORD")

# Send emails with Django infrastructure
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" #Mis en commentaire, le temps de tester backends.console.EmailBackend
EMAIL_HOST = uranus_backend_config.get("SMTP_HOST")
EMAIL_PORT = uranus_backend_config.get("SMTP_PORT")
EMAIL_HOST_USER = uranus_backend_config.get("SENDER_EMAIL")
EMAIL_HOST_PASSWORD = uranus_backend_config.get("SENDER_EMAIL_PASSWORD")
EMAIL_USE_SSL = True
DEFAULT_FROM_EMAIL = uranus_backend_config.get("SENDER_EMAIL") #Mis en commentaire, le temps de tester noreply@uranus.com'

# Demande d'attestation automobile en ligne
# Les huit paramètres ci-dessous permettent de communiquer avec la plateforme de l'ASACI

# Code Intermediaire
ASACI_INTERMEDIARY_CODE = uranus_backend_config.get(
    "ASACI_INTERMEDIARY_CODE", "ASACI_CRT_146"
)

# Code Demandeur
ASACI_REQUESTER_CODE = uranus_backend_config.get("ASACI_REQUESTER_CODE", "")

# Code compagnie
ASACI_COMPANY_CODE = uranus_backend_config.get("ASACI_COMPANY_CODE", "ASACI_NSIA")

# Code d'accès
ASACI_ACCESS_CODE = uranus_backend_config.get("ASACI_ACCESS_CODE", "")

# Point de vente
ASACI_POINT_OF_SALE = uranus_backend_config.get(
    "ASACI_POINT_OF_SALE", "OREOLE ASSURANCES"
)

# Bureau
ASACI_OFFICE = uranus_backend_config.get("ASACI_OFFICE", "OREOLE ASSURANCES")

# Code d'annulation
ASACI_CERTIFICATE_CANCELLATION = uranus_backend_config.get(
    "ASACI_CERTIFICATE_CANCELLATION", 109
)

# Code de suspension
ASACI_CERTIFICATE_SUSPENSION = uranus_backend_config.get(
    "ASACI_CERTIFICATE_SUSPENSION", 120
)

# API BASE URL
ASACI_API_BASE_URL = uranus_backend_config.get("ASACI_API_BASE_URL", "")


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "django_filters",
    "configuration_api.apps.ConfigurationApiConfig",
    "customer.apps.CustomerConfig",
    "account.apps.AccountConfig",
    "production.apps.ProductionConfig",
    "djmoney",
    "corsheaders",
    "knox",
    "drf_toolbox",
    "asaci",
    "sante",
    "django_rest_passwordreset",
    "reporting",
    "phonenumbers",
    "messaging",
    "payment",
    "core",
    "django_celery_beat",
    "django_celery_results",
    "django_api_admin",
    "autorisations",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        # "rest_framework.authentication.SessionAuthentication",
        "knox.auth.TokenAuthentication",
    ],
    # "DEFAULT_PERMISSION_CLASSES": [
    #    "rest_framework.permissions.IsAuthenticated",
    # ],
    # "DEFAULT_MODEL_SERIALIZER_CLASS": "drf_toolbox.serializers.ModelSerializer",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 200,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=1),
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #    "auditlog.middleware.AuditlogMiddleware",
    # "core.middleware.RestrictIPMiddleware",
    # "core.middleware.LogMiddleware",
]
CORS_ALLOW_ALL_ORIGINS = (
    uranus_backend_config.get("CORS_ALLOW_ALL_ORIGINS", "False").upper() == "TRUE"
)
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = uranus_backend_config.get(
    "CORS_ALLOWED_ORIGINS",
    "",
).split(" ")

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
ROOT_URLCONF = "uranus.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ],
        },
    },
]

WSGI_APPLICATION = "uranus.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = "static/"
# STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# MEDIA_URL = "/media/"
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# # Celery settings
# CELERY_BROKER_URL = uranus_backend_config.get("CELERY_BROKER_URL", "redis://localhost:6379/0")
# CELERY_TIME = uranus_backend_config.get("CELERY_TIMEZONE", "Africa/Abidjan")
# CELERY_BEAT_SCHEDULER = uranus_backend_config.get(
#     "CELERY_BEAT_SCHEDULER", "django_celery_beat.schedulers:DatabaseScheduler"
# )
# CELERY_RESULT_BACKEND = uranus_backend_config.get("CELERY_RESULT_BACKEND", "redis://localhost:6379/0")
# CELERY_CACHE_BACKEND = uranus_backend_config.get("CELERY_CACHE_BACKEND", "django-cache")
# CELERY_RESULT_EXTENDED = uranus_backend_config.get("CELERY_RESULT_EXTENDED", False)

#################################################################################
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE # Utilise le même timezone que Django
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
FRONTEND_URL="http://localhost:3000"

# Tâches périodiques (Celery Beat)
CELERY_BEAT_SCHEDULE = {
    'nettoyer-jetons-expires-quotidien': {
        'task': 'autorisations.tasks.nettoyer_jetons_expires',
        'schedule': 86400.0, # Toutes les 24 heures
    },
}

###################################################################################


# AROLITEC SMS gateway client settings
AROLITEC_SMS_USER_ACCOUNT = uranus_backend_config.get("AROLITEC_SMS_USER_ACCOUNT", None)
AROLITEC_SMS_USER_PASSWORD = uranus_backend_config.get(
    "AROLITEC_SMS_USER_PASSWORD", None
)
AROLITEC_SMS_DEFAULT_SENDER = uranus_backend_config.get(
    "AROLITEC_SMS_DEFAULT_SENDER", None
)
AROLITEC_SMS_DEFAULT_NUMERIC_SENDER = uranus_backend_config.get(
    "AROLITEC_SMS_DEFAULT_NUMERIC_SENDER", None
)
AROLITEC_SMS_SEND_MESSAGE_URL = uranus_backend_config.get(
    "AROLITEC_SMS_SEND_MESSAGE_URL", None
)
AROLITEC_SMS_GET_STATUS_URL = uranus_backend_config.get(
    "AROLITEC_SMS_GET_STATUS_URL", ""
)
AROLITEC_SMS_CHECK_BALANCE_URL = uranus_backend_config.get(
    "AROLITEC_SMS_CHECK_BALANCE_URL", ""
)
AROLITEC_SMS_DEFAULT_CHARSET = uranus_backend_config.get(
    "AROLITEC_SMS_DEFAULT_CHARSET", "UTF-8"
)
AROLITEC_SMS_CHARSET_LIST = uranus_backend_config.get(
    "AROLITEC_SMS_CHARSET_LIST", "ISO-8859-1 UTF-8"
).split()

# NERHY settings
NERHY_SMS_ENABLED = int(uranus_backend_config.get("NERHY_SMS_ENABLED", 0))
NERHY_SMS_API_TOKEN = uranus_backend_config.get("NERHY_SMS_API_TOKEN", "")
NERHY_SMS_DEFAULT_SENDER = uranus_backend_config.get("NERHY_SMS_DEFAULT_SENDER", None)
NERHY_SMS_SEND_MESSAGE_URL = uranus_backend_config.get(
    "NERHY_SMS_SEND_MESSAGE_URL", None
)
NERHY_SMS_BULK_SEND_MESSAGE_URL = uranus_backend_config.get(
    "NERHY_SMS_BULK_SEND_MESSAGE_URL", None
)
NERHY_SMS_CHECK_BALANCE_URL = uranus_backend_config.get(
    "NERHY_SMS_CHECK_BALANCE_URL", None
)

# DISTRIPAY settings
DISTRIPAY_ENABLED = uranus_backend_config.get("DISTRIPAY_ENABLED", 0)
DISTRIPAY_API_KEY = uranus_backend_config.get("DISTRIPAY_API_KEY", "")
DISTRIPAY_SITE_ID = uranus_backend_config.get("DISTRIPAY_SITE_ID", None)
DISTRIPAY_INIT_TRANS_URL = uranus_backend_config.get("DISTRIPAY_INIT_TRANS_URL", None)
DISTRIPAY_VERIFY_TRANS_URL = uranus_backend_config.get(
    "DISTRIPAY_VERIFY_TRANS_URL", None
)
DISTRIPAY_DEFAULT_CURRENCY = uranus_backend_config.get("DISTRIPAY_ENABLED", "XOF")
DISTRIPAY_DEFAULT_LANGUAGE = uranus_backend_config.get("DISTRIPAY_ENABLED", "fr")
DISTRIPAY_DEFAULT_CHANNEL = uranus_backend_config.get("DISTRIPAY_ENABLED", "ALL")

URANUS_IN_PRODUCTION = int(uranus_backend_config.get("URANUS_IN_PRODUCTION", 0))
MAX_LIMIT_FOR_SEARCH = int(uranus_backend_config.get("MAX_LIMIT_FOR_SEARCH", 1000))
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_PROFILE_MODULE = "account.UranusUser"

AUTH_USER_MODEL = "account.UranusUser"
