# Generated by Django 4.1.4 on 2023-03-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customer", "0001_initial"),
        ("configuration_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataInsertionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ObjectId", models.IntegerField(default=0)),
                ("OutputMessage", models.CharField(default="", max_length=500)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="GarantieContratFlotte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdContrat", models.IntegerField()),
                ("NatureRisque", models.CharField(max_length=60)),
                ("Garantie", models.CharField(max_length=40)),
                ("SommeMaxGarantie", models.CharField(max_length=40)),
                ("Franchise", models.CharField(max_length=40)),
                ("PrimeNette", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuittanceFn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdDevis", models.IntegerField(null=True)),
                ("IdContrat", models.IntegerField(null=True)),
                ("RaisonSociale", models.CharField(max_length=100)),
                ("LibelleIntermediaire", models.CharField(max_length=50)),
                ("IdClient", models.IntegerField()),
                ("NumeroDevis", models.CharField(max_length=50, null=True)),
                ("NumeroPolice", models.CharField(max_length=50, null=True)),
                ("NumeroAvenant", models.CharField(max_length=50)),
                ("NomClient", models.CharField(max_length=122)),
                ("AdresseClient", models.CharField(max_length=100)),
                ("DateEffet", models.DateField()),
                ("DateExpiration", models.DateField()),
                ("DateEmission", models.DateField()),
                ("Duree", models.IntegerField()),
                ("PrimeNette", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "PrimeNetteHorsFga",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Fga", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Accessoire", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "AccessoireCompagnie",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "AccessoireIntermediaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "TaxeEnregistrement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("PrimeTtc", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Confirme", models.BooleanField(null=True)),
                ("LibelleProduit", models.CharField(max_length=60)),
                ("LibelleCategorie", models.CharField(max_length=100)),
                (
                    "CommissionIntermediaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "CommissionGestionnaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "CommissionAperition",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("TitreClient", models.CharField(max_length=100)),
                ("ProfessionClient", models.CharField(max_length=100)),
                ("TypeAssure", models.CharField(max_length=100)),
                ("TypeSouscripteur", models.CharField(max_length=100)),
                ("TelephoneClient", models.CharField(max_length=20)),
                ("MobileClient", models.CharField(max_length=20)),
                ("AdresseGeographique", models.CharField(max_length=100)),
                ("EmailClient", models.CharField(max_length=254)),
                ("Cedeao", models.DecimalField(decimal_places=4, max_digits=19)),
                ("LibelleMouvement", models.CharField(max_length=50)),
                ("NomAssure", models.CharField(max_length=122)),
                ("AdresseAssure", models.CharField(max_length=100)),
                ("NumeroQuittance", models.CharField(max_length=16)),
                ("LibelleOffre", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QuotationInsertionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdDevis", models.IntegerField(default=0)),
                ("IdDevisDetail", models.IntegerField(default=0)),
                ("NumeroImmatriculation", models.CharField(default="", max_length=50)),
                ("OutputMessage", models.CharField(default="", max_length=500)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VehiculeContrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdContrat", models.IntegerField()),
                ("LibelleTarif", models.CharField(max_length=100)),
                ("LibelleCategorie", models.CharField(max_length=100)),
                ("IdMarque", models.IntegerField()),
                ("LibelleMarque", models.CharField(max_length=60)),
                ("IdTypeVehicule", models.IntegerField()),
                ("LibelleTypeVehicule", models.CharField(max_length=255)),
                ("ChargeUtile", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Puissance", models.SmallIntegerField()),
                ("Immatriculation", models.CharField(max_length=50)),
                ("CodeEnergie", models.CharField(max_length=10)),
                ("LibelleEnergie", models.CharField(max_length=15)),
                ("ValeurNeuve", models.DecimalField(decimal_places=4, max_digits=19)),
                ("ValeurVenale", models.DecimalField(decimal_places=4, max_digits=19)),
                ("NombrePlace", models.SmallIntegerField()),
                ("Rc", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Fga", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Cedeao", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Recours", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "RecoursAnticipe",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "RecoursExpress",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Dommages", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Collision", models.DecimalField(decimal_places=4, max_digits=19)),
                ("BrisDeGlaces", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Incendie", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Explosion", models.DecimalField(decimal_places=4, max_digits=19)),
                ("VolSimple", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "VolMainsArmees",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Vandalisme", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "VolAccessoires",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "IndividuelleChauffeur",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "InfirmitePermanente",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "IncapaciteTemporaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Deces", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "FraisTraitement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "Immobilisation",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("NsiaAssistCar", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "idcontrat",
                    models.AutoField(
                        db_column="idcontrat", primary_key=True, serialize=False
                    ),
                ),
                ("iddevis", models.IntegerField(db_column="iddevis")),
                (
                    "idcompagnie",
                    models.IntegerField(blank=True, db_column="idcompagnie", null=True),
                ),
                ("idintermediaire", models.IntegerField(db_column="idintermediaire")),
                ("idproduit", models.IntegerField(db_column="idproduit")),
                ("idclient", models.IntegerField(db_column="idclient", default=0)),
                ("idassure", models.IntegerField(db_column="idassure", default=0)),
                ("idavenant", models.IntegerField(db_column="idavenant")),
                ("flotte", models.BooleanField(db_column="flotte")),
                ("coassurance", models.BooleanField(db_column="coassurance")),
                (
                    "idaperiteur",
                    models.IntegerField(db_column="idaperiteur", default=0),
                ),
                (
                    "numeropolice",
                    models.CharField(
                        db_column="numeropolice", max_length=50, unique=True
                    ),
                ),
                (
                    "referenceagent",
                    models.CharField(
                        db_column="referenceagent", default="", max_length=50
                    ),
                ),
                (
                    "renouvelable",
                    models.BooleanField(db_column="renouvelable", default=False),
                ),
                (
                    "echeance",
                    models.CharField(db_column="echeance", default="", max_length=5),
                ),
                ("periode", models.CharField(db_column="periode", max_length=1)),
                (
                    "numeroavenant",
                    models.CharField(db_column="numeroavenant", max_length=50),
                ),
                (
                    "dateeffet",
                    models.DateTimeField(blank=True, db_column="dateeffet", null=True),
                ),
                (
                    "heuredebut",
                    models.DateTimeField(blank=True, db_column="heuredebut", null=True),
                ),
                (
                    "dateexpiration",
                    models.DateTimeField(
                        blank=True, db_column="dateexpiration", null=True
                    ),
                ),
                ("dateemission", models.DateTimeField(db_column="dateemission")),
                (
                    "transfere",
                    models.BooleanField(db_column="transfere", default=False),
                ),
                ("nbreche", models.SmallIntegerField(db_column="nbreche", default=1)),
                (
                    "anticipation",
                    models.BooleanField(db_column="anticipation", default=False),
                ),
                (
                    "observation",
                    models.CharField(
                        db_column="observation", default="", max_length=50
                    ),
                ),
                ("idoldhist", models.IntegerField(db_column="idoldhist", default=0)),
                (
                    "oldnumerodevis",
                    models.CharField(
                        db_column="oldnumerodevis", default="", max_length=50
                    ),
                ),
                (
                    "auteur",
                    models.BooleanField(
                        db_column="auteur", default=False, max_length=1
                    ),
                ),
                (
                    "primeannuelle",
                    models.DecimalField(
                        db_column="primeannuelle",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "primenette",
                    models.DecimalField(
                        db_column="primenette",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "accessoire",
                    models.DecimalField(
                        db_column="accessoire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "accessoirecompagnie",
                    models.DecimalField(
                        db_column="accessoirecompagnie",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "accessoireintermediaire",
                    models.DecimalField(
                        db_column="accessoireintermediaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "accessoiregestionnaire",
                    models.DecimalField(
                        db_column="accessoiregestionnaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissionintermediaire",
                    models.DecimalField(
                        db_column="commissionintermediaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissiongestionnaire",
                    models.DecimalField(
                        db_column="commissiongestionnaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissionaperiteur",
                    models.DecimalField(
                        db_column="commissionaperiteur",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe", decimal_places=4, default=0, max_digits=19
                    ),
                ),
                (
                    "primettc",
                    models.DecimalField(
                        db_column="primettc", decimal_places=4, default=0, max_digits=19
                    ),
                ),
                (
                    "idoperateur",
                    models.IntegerField(blank=True, db_column="idoperateur", null=True),
                ),
                (
                    "bonus_malus",
                    models.DecimalField(
                        db_column="bonus_malus",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "assure",
                    models.CharField(
                        blank=True, db_column="assure", max_length=255, null=True
                    ),
                ),
                (
                    "idcontratannulation",
                    models.IntegerField(db_column="idcontratannulation"),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "db_table": "stdcontrat",
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                ("iddevis", models.AutoField(primary_key=True, serialize=False)),
                ("flotte", models.BooleanField()),
                ("coassurance", models.BooleanField()),
                ("numerodevis", models.CharField(max_length=50)),
                ("referenceagent", models.CharField(default="", max_length=50)),
                ("renouvelable", models.BooleanField(default=False)),
                ("echeance", models.CharField(default="", max_length=5)),
                ("periode", models.CharField(max_length=1)),
                ("numeroavenant", models.CharField(max_length=50)),
                ("dateeffet", models.DateTimeField(blank=True, null=True)),
                ("heuredebut", models.DateTimeField(blank=True, null=True)),
                ("dateexpiration", models.DateTimeField(blank=True, null=True)),
                ("confirme", models.BooleanField()),
                ("dateemission", models.DateTimeField()),
                ("transfere", models.BooleanField(default=False)),
                ("nbreche", models.SmallIntegerField(default=1)),
                ("anticipation", models.BooleanField(default=False)),
                ("observation", models.CharField(default="", max_length=50)),
                ("idoldhist", models.IntegerField(default=0)),
                ("oldnumerodevis", models.CharField(default="", max_length=50)),
                ("auteur", models.BooleanField(default=False)),
                (
                    "primeannuelle",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "primenette",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "accessoire",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "accessoirecompagnie",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "accessoireintermediaire",
                    models.DecimalField(
                        db_column="accessoireintermediaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "accessoiregestionnaire",
                    models.DecimalField(
                        db_column="accessoiregestionnaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissionintermediaire",
                    models.DecimalField(
                        db_column="commissionintermediaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissiongestionnaire",
                    models.DecimalField(
                        db_column="commissiongestionnaire",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "commissionaperiteur",
                    models.DecimalField(
                        db_column="commissionaperiteur",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "primettc",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("idoperateur", models.IntegerField(blank=True, null=True)),
                (
                    "bonus_malus",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                ("idenergie", models.SmallIntegerField(blank=True, null=True)),
                ("nomassure", models.CharField(blank=True, max_length=255, null=True)),
                ("idhisto", models.IntegerField(default=0)),
                (
                    "aperiteur",
                    models.ForeignKey(
                        db_column="idaperiteur",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_aperiteur",
                        to="configuration_api.compagnie",
                    ),
                ),
                (
                    "assure",
                    models.ForeignKey(
                        db_column="idassure",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_assure",
                        to="customer.client",
                    ),
                ),
                (
                    "avenant",
                    models.ForeignKey(
                        db_column="idavenant",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_avenant",
                        to="configuration_api.avenant",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="idclient",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_client",
                        to="customer.client",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_compagnie",
                        to="configuration_api.compagnie",
                    ),
                ),
                (
                    "intermediaire",
                    models.ForeignKey(
                        db_column="idintermediaire",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_intermediaire",
                        to="configuration_api.intermediaire",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        db_column="idoffre",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_offre",
                        to="configuration_api.offre",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="idproduit",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="devis_produit",
                        to="configuration_api.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
                "db_table": "stddevis",
            },
        ),
        migrations.CreateModel(
            name="TarifEcran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idtarif", models.IntegerField()),
                ("idgarantie", models.IntegerField()),
                ("garcapitaltype", models.SmallIntegerField()),
                ("garcapitalliste", models.IntegerField()),
                ("garcapitalval", models.DecimalField(decimal_places=4, max_digits=19)),
                ("garfranchisetype", models.SmallIntegerField()),
                ("garfranchiseliste", models.IntegerField()),
                (
                    "garfranchiseval",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("garformuletype", models.SmallIntegerField()),
                ("garformuleliste", models.IntegerField()),
                ("garformuleval", models.SmallIntegerField()),
                ("garplacetype", models.SmallIntegerField()),
                ("garplaceval", models.SmallIntegerField()),
                ("obligatoire", models.BooleanField()),
                ("modecalcind", models.CharField(blank=True, max_length=1, null=True)),
                ("sindelai", models.SmallIntegerField(blank=True, null=True)),
                ("sinbloquant", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "stdtarifecran",
            },
        ),
        migrations.CreateModel(
            name="Tarification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iddetail", models.CharField(blank=True, max_length=255, null=True)),
                ("idtarif", models.CharField(blank=True, max_length=255, null=True)),
                ("idgarantie", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "puissancedu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "puissanceau",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tonnagedu", models.CharField(blank=True, max_length=255, null=True)),
                ("tonnageau", models.CharField(blank=True, max_length=255, null=True)),
                ("capitaldu", models.CharField(blank=True, max_length=255, null=True)),
                ("capitalau", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "franchisedu",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "franchiseau",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "franchisemin",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("agevehdu", models.CharField(blank=True, max_length=255, null=True)),
                ("agevehau", models.CharField(blank=True, max_length=255, null=True)),
                ("agecnddu", models.CharField(blank=True, max_length=255, null=True)),
                ("agecndau", models.CharField(blank=True, max_length=255, null=True)),
                ("placesdu", models.CharField(blank=True, max_length=255, null=True)),
                ("placesau", models.CharField(blank=True, max_length=255, null=True)),
                ("taux", models.CharField(blank=True, max_length=255, null=True)),
                ("primemin", models.CharField(blank=True, max_length=255, null=True)),
                ("placesgrat", models.CharField(blank=True, max_length=255, null=True)),
                ("primeplace", models.CharField(blank=True, max_length=255, null=True)),
                ("primegar", models.CharField(blank=True, max_length=255, null=True)),
                ("deces", models.CharField(blank=True, max_length=255, null=True)),
                ("ipp", models.CharField(blank=True, max_length=255, null=True)),
                ("fraismed", models.CharField(blank=True, max_length=255, null=True)),
                ("minprorata", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codecarburant",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "stdtarification",
            },
        ),
        migrations.CreateModel(
            name="ExtendedDevisInfo",
            fields=[
                (
                    "devis_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="production.devis",
                    ),
                ),
                ("id_produit", models.IntegerField()),
                ("id_contrat", models.IntegerField(null=True)),
                ("libelle_aperiteur", models.CharField(max_length=100)),
                ("libelle_avenant", models.CharField(max_length=50)),
                ("nomclient", models.CharField(max_length=122)),
                ("adressepostaleclient", models.CharField(max_length=100)),
                ("adressegeoclient", models.CharField(max_length=100)),
                ("emailclient", models.CharField(max_length=254)),
                ("telephoneclient", models.CharField(max_length=20)),
                ("libelle_compagnie", models.CharField(max_length=100)),
                ("libelle_intermediaire", models.CharField(max_length=50)),
                ("libelle_offre", models.CharField(max_length=80)),
                ("libelle_produit", models.CharField(max_length=60)),
                ("libelle_categorie", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
            bases=("production.devis", models.Model),
        ),
        migrations.CreateModel(
            name="Quittance",
            fields=[
                (
                    "idquittance",
                    models.AutoField(
                        db_column="idquittance", primary_key=True, serialize=False
                    ),
                ),
                ("exercice", models.SmallIntegerField(db_column="exercice")),
                (
                    "numeroquittance",
                    models.CharField(
                        db_column="numeroquittance", max_length=16, unique=True
                    ),
                ),
                ("nature", models.CharField(db_column="nature", max_length=1)),
                ("dateeffet", models.DateTimeField(db_column="dateeffet")),
                ("dateexpiration", models.DateTimeField(db_column="dateexpiration")),
                ("source", models.SmallIntegerField(db_column="source")),
                ("statut", models.SmallIntegerField(db_column="statut")),
                (
                    "primenette",
                    models.DecimalField(
                        db_column="primenette", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "accessoire",
                    models.DecimalField(
                        db_column="accessoire", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        db_column="commission", decimal_places=4, max_digits=19
                    ),
                ),
                ("encaissee", models.BooleanField(db_column="encaissee")),
                (
                    "mt_encaisse",
                    models.DecimalField(
                        db_column="mt_encaisse", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "mt_regle",
                    models.DecimalField(
                        db_column="mt_regle", decimal_places=4, max_digits=19
                    ),
                ),
                ("reglee", models.BooleanField(db_column="reglee")),
                ("coassurance", models.BooleanField(db_column="coassurance")),
                ("directcie", models.BooleanField(db_column="directcie")),
                ("reglecoass", models.BooleanField(db_column="reglecoass")),
                ("reglecion", models.BooleanField(db_column="reglecion")),
                ("dateemission", models.DateField(db_column="dateemission")),
                (
                    "primettc",
                    models.DecimalField(
                        db_column="primettc", decimal_places=4, max_digits=19
                    ),
                ),
                ("exoneredetaxes", models.BooleanField(db_column="exoneredetaxes")),
                ("exoneredeaccess", models.BooleanField(db_column="exoneredeaccess")),
                (
                    "aperiteur",
                    models.ForeignKey(
                        db_column="idaperiteur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.compagnie",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        db_column="idclient",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="customer.client",
                    ),
                ),
                (
                    "intermediaire",
                    models.ForeignKey(
                        db_column="idintermediaire",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.intermediaire",
                    ),
                ),
                (
                    "police",
                    models.ForeignKey(
                        db_column="numeropolice",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contrat",
                        to_field="numeropolice",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="idproduit",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.produit",
                    ),
                ),
                (
                    "quittanceanullation",
                    models.ForeignKey(
                        db_column="idquittannul",
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="production.quittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quittance",
                "verbose_name_plural": "Quittances",
                "db_table": "stdquittance",
            },
        ),
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "idmodule",
                    models.CharField(
                        db_column="idmodule",
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exercice", models.SmallIntegerField(db_column="exercice")),
                ("libelle", models.CharField(db_column="libelle", max_length=50)),
                ("numero", models.IntegerField(db_column="numero")),
                ("cloture", models.BooleanField(db_column="cloture")),
            ],
            options={
                "db_table": "stdnumero",
                "unique_together": {("idmodule", "exercice")},
            },
        ),
        migrations.CreateModel(
            name="Encaissement",
            fields=[
                (
                    "idencaissement",
                    models.AutoField(
                        db_column="idencaissement", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numeropiece",
                    models.CharField(db_column="numeropiece", max_length=16),
                ),
                (
                    "dateencaissement",
                    models.DateTimeField(db_column="dateencaissement"),
                ),
                (
                    "montantencaissement",
                    models.DecimalField(
                        db_column="montantencaissement", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "montantenattente",
                    models.DecimalField(
                        blank=True,
                        db_column="montantenattente",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "montantdeduit",
                    models.DecimalField(
                        blank=True,
                        db_column="montantdeduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "numerocheque",
                    models.CharField(
                        blank=True, db_column="numerocheque", max_length=20, null=True
                    ),
                ),
                (
                    "compte_compensation",
                    models.CharField(
                        blank=True,
                        db_column="compte_compensation",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "idutilisateur",
                    models.IntegerField(
                        blank=True, db_column="idutilisateur", null=True
                    ),
                ),
                ("datesaisie", models.DateTimeField(db_column="datesaisie")),
                ("piece_annulee", models.BooleanField(db_column="piece_annulee")),
                (
                    "dateannulation",
                    models.DateTimeField(
                        blank=True, db_column="dateannulation", null=True
                    ),
                ),
                (
                    "nomannulation",
                    models.CharField(
                        blank=True, db_column="nomannulation", max_length=50, null=True
                    ),
                ),
                (
                    "motifannulation",
                    models.CharField(
                        blank=True,
                        db_column="motifannulation",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "datesaisieannulation",
                    models.DateTimeField(
                        blank=True, db_column="datesaisieannulation", null=True
                    ),
                ),
                (
                    "nomtireurcheque",
                    models.CharField(db_column="nomtireurcheque", max_length=50),
                ),
                (
                    "banque",
                    models.ForeignKey(
                        blank=True,
                        db_column="idbanque",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.banque",
                    ),
                ),
                (
                    "modepaiement",
                    models.ForeignKey(
                        db_column="idmodepaiement",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.modeencaissement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encaissement",
                "verbose_name_plural": "Encaissements",
                "db_table": "stdencaissement",
            },
        ),
        migrations.CreateModel(
            name="DevisDetail",
            fields=[
                ("iddevisdetail", models.AutoField(primary_key=True, serialize=False)),
                ("iddevis", models.IntegerField()),
                ("idoffre", models.IntegerField(blank=True, null=True)),
                ("idtarif", models.IntegerField()),
                ("vehicule", models.IntegerField()),
                ("codeusage", models.CharField(blank=True, max_length=3, null=True)),
                ("reference", models.CharField(blank=True, max_length=3, null=True)),
                ("idcarrosserie", models.IntegerField(blank=True, null=True)),
                ("puissancefiscale", models.SmallIntegerField(blank=True, null=True)),
                ("nombreplace", models.SmallIntegerField()),
                ("chargeutile", models.DecimalField(decimal_places=4, max_digits=19)),
                ("valeurneuve", models.DecimalField(decimal_places=4, max_digits=19)),
                ("valeurvenale", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "valeuraccessoire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("remorque", models.BooleanField(default=False)),
                ("matrem1", models.CharField(default="", max_length=50)),
                ("matrem2", models.CharField(default="", max_length=50)),
                ("extincteur", models.BooleanField(default=False)),
                ("idprofession", models.IntegerField(blank=True, null=True)),
                ("conducteur", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "adressecnd",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("villecnd", models.IntegerField(blank=True, null=True)),
                ("sexe", models.CharField(default="M", max_length=1)),
                ("datemec", models.DateTimeField(blank=True, null=True)),
                ("datemutation", models.DateTimeField(blank=True, null=True)),
                ("nummoteur", models.CharField(blank=True, max_length=50, null=True)),
                ("numchassis", models.CharField(blank=True, max_length=50, null=True)),
                ("nbreextinteur", models.SmallIntegerField(blank=True, null=True)),
                (
                    "typevehicule",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "modelevehicule",
                    models.CharField(
                        db_column="modelevehicule",
                        default="",
                        max_length=30,
                        verbose_name="Modèle du véhicule",
                    ),
                ),
                ("matricule", models.CharField(default="", max_length=50)),
                ("typeimmat", models.CharField(default="M", max_length=1)),
                ("attestation", models.CharField(default="", max_length=50)),
                ("provisoire", models.BooleanField(default=False)),
                (
                    "permis",
                    models.CharField(blank=True, default="", max_length=50, null=True),
                ),
                ("datedelipc", models.DateTimeField(blank=True, null=True)),
                ("datenaicnd", models.DateTimeField(blank=True, null=True)),
                ("iddelegation", models.IntegerField(blank=True, null=True)),
                ("agrement", models.CharField(default="", max_length=50)),
                ("villeagrement", models.IntegerField(blank=True, null=True)),
                ("observation", models.CharField(default="", max_length=50)),
                ("idoldhist", models.IntegerField(default=0)),
                ("oldpolice", models.CharField(default="", max_length=50)),
                ("oldattestation", models.CharField(default="", max_length=50)),
                ("oldmarque", models.IntegerField(default=0)),
                ("oldtype", models.CharField(default="", max_length=50)),
                ("oldmatricule", models.CharField(default="", max_length=50)),
                ("carteverte", models.BooleanField(default=False)),
                ("numcarteverte", models.CharField(default="", max_length=50)),
                ("auteur", models.CharField(default="M", max_length=1)),
                (
                    "primeannuelle",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "primenette",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "mt_delegation",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "attestationprov",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("pc_control", models.BooleanField(default=False)),
                ("cg_control", models.BooleanField(default=False)),
                ("numpccnd", models.CharField(default="", max_length=50)),
                ("pctype", models.CharField(default="000000000000", max_length=50)),
                (
                    "taxeenregistrement",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "essence",
                    models.ForeignKey(
                        db_column="essence",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.energie",
                    ),
                ),
                (
                    "idgenrevehicule",
                    models.ForeignKey(
                        db_column="idgenrevehicule",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.genrevehicule",
                        verbose_name="Id Genre Véhicule",
                    ),
                ),
                (
                    "idmarque",
                    models.ForeignKey(
                        db_column="idmarque",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.marque",
                    ),
                ),
                (
                    "idtypevehicule",
                    models.ForeignKey(
                        db_column="idtypevehicule",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.typevehicule",
                        verbose_name="Id Type Véhicule",
                    ),
                ),
                (
                    "idusage",
                    models.ForeignKey(
                        db_column="idusage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.usagevehicule",
                    ),
                ),
                (
                    "securite",
                    models.ForeignKey(
                        db_column="codealarme",
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.systemesecurite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de devis",
                "verbose_name_plural": "Détails de devis",
                "db_table": "stddevisdetail",
            },
        ),
        migrations.CreateModel(
            name="DetailEncaissement",
            fields=[
                (
                    "iddetailencaissement",
                    models.AutoField(
                        db_column="iddetailencaissement",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("indiceacompte", models.SmallIntegerField(db_column="indiceacompte")),
                (
                    "soldeinitial",
                    models.DecimalField(
                        db_column="soldeinitial", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "montantreglement",
                    models.DecimalField(
                        db_column="montantreglement", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "montantecart",
                    models.DecimalField(
                        db_column="montantecart", decimal_places=4, max_digits=19
                    ),
                ),
                ("ecart", models.BooleanField(db_column="ecart")),
                ("code_ecart", models.CharField(db_column="code_ecart", max_length=1)),
                (
                    "montant_encaissement",
                    models.DecimalField(
                        db_column="montant_encaissement",
                        decimal_places=4,
                        max_digits=19,
                    ),
                ),
                (
                    "dedcommission_intermediaire",
                    models.BooleanField(db_column="dedcommission_intermediaire"),
                ),
                (
                    "dedcommission_gestionnaire",
                    models.BooleanField(db_column="dedcommission_gestionnaire"),
                ),
                (
                    "dedcommission_coassurance",
                    models.BooleanField(db_column="dedcommission_coassurance"),
                ),
                (
                    "dedaccessoireintermediaire",
                    models.BooleanField(db_column="dedaccessoireintermediaire"),
                ),
                (
                    "dedaccessoiregestionnaire",
                    models.BooleanField(db_column="dedaccessoiregestionnaire"),
                ),
                (
                    "dedtaxecommission",
                    models.BooleanField(db_column="dedtaxecommission"),
                ),
                (
                    "dedtaxeaccessoire",
                    models.BooleanField(
                        blank=True,
                        db_column="dedtaxeaccessoire",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "comintermediaire",
                    models.DecimalField(
                        blank=True,
                        db_column="comintermediaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "comgestionnaire",
                    models.DecimalField(
                        blank=True,
                        db_column="comgestionnaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "comconseiller",
                    models.DecimalField(
                        blank=True,
                        db_column="comconseiller",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "comcoassurance",
                    models.DecimalField(
                        blank=True,
                        db_column="comcoassurance",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "accintermediaire",
                    models.DecimalField(
                        blank=True,
                        db_column="accintermediaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "accgestionnaire",
                    models.DecimalField(
                        blank=True,
                        db_column="accgestionnaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "dedcoassurance",
                    models.BooleanField(
                        blank=True, db_column="dedcoassurance", null=True
                    ),
                ),
                (
                    "primecedee",
                    models.DecimalField(
                        blank=True,
                        db_column="primecedee",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "taxe_commission_deduit",
                    models.DecimalField(
                        blank=True,
                        db_column="taxe_commission_deduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "taxeaccessoire_deduit",
                    models.DecimalField(
                        blank=True,
                        db_column="taxeaccessoire_deduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "impotdeduit",
                    models.DecimalField(
                        blank=True,
                        db_column="impotdeduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "encaissement",
                    models.ForeignKey(
                        db_column="idencaissement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.encaissement",
                    ),
                ),
                (
                    "numeroquittance",
                    models.ForeignKey(
                        db_column="numeroquittance",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.quittance",
                        to_field="numeroquittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'encaissement",
                "verbose_name_plural": "Lignes d'encaissement",
                "db_table": "stddetailencaissement",
            },
        ),
        migrations.CreateModel(
            name="ContratDetail",
            fields=[
                (
                    "idcontratdetail",
                    models.AutoField(
                        db_column="idcontratdetail", primary_key=True, serialize=False
                    ),
                ),
                ("idcontrat", models.IntegerField(db_column="idcontrat")),
                ("idassure", models.IntegerField(db_column="idassure")),
                ("idproduit", models.IntegerField(db_column="idproduit")),
                ("idoffre", models.IntegerField(db_column="idoffre")),
                ("idtarif", models.IntegerField(db_column="idtarif")),
                (
                    "codeusage",
                    models.CharField(
                        blank=True, db_column="codeusage", max_length=3, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_column="reference", max_length=3, null=True
                    ),
                ),
                (
                    "idcarrosserie",
                    models.IntegerField(
                        blank=True, db_column="idcarrosserie", null=True
                    ),
                ),
                (
                    "matricule",
                    models.CharField(db_column="matricule", default="", max_length=50),
                ),
                (
                    "puissancefiscale",
                    models.SmallIntegerField(
                        blank=True, db_column="puissancefiscale", null=True
                    ),
                ),
                ("nombreplace", models.SmallIntegerField(db_column="nombreplace")),
                (
                    "chargeutile",
                    models.DecimalField(
                        db_column="chargeutile", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "valeurneuve",
                    models.DecimalField(
                        db_column="valeurneuve", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "valeurvenale",
                    models.DecimalField(
                        db_column="valeurvenale", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "valeuraccessoire",
                    models.DecimalField(
                        db_column="valeuraccessoire", decimal_places=4, max_digits=19
                    ),
                ),
                ("remorque", models.BooleanField(db_column="remorque", default=False)),
                (
                    "matrem1",
                    models.CharField(db_column="matrem1", default="", max_length=50),
                ),
                (
                    "matrem2",
                    models.CharField(db_column="matrem2", default="", max_length=50),
                ),
                (
                    "extincteur",
                    models.BooleanField(db_column="extincteur", default=False),
                ),
                (
                    "idprofession",
                    models.IntegerField(
                        blank=True, db_column="idprofession", null=True
                    ),
                ),
                (
                    "conducteur",
                    models.CharField(
                        blank=True, db_column="conducteur", max_length=255, null=True
                    ),
                ),
                (
                    "assure",
                    models.CharField(
                        blank=True, db_column="assure", max_length=255, null=True
                    ),
                ),
                (
                    "adressecnd",
                    models.CharField(
                        blank=True,
                        db_column="adressecnd",
                        default="",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "villecnd",
                    models.IntegerField(blank=True, db_column="villecnd", null=True),
                ),
                ("sexe", models.CharField(db_column="sexe", default="M", max_length=1)),
                (
                    "datemec",
                    models.DateTimeField(blank=True, db_column="datemec", null=True),
                ),
                (
                    "nummoteur",
                    models.CharField(
                        blank=True, db_column="nummoteur", max_length=50, null=True
                    ),
                ),
                (
                    "numchassis",
                    models.CharField(
                        blank=True, db_column="numchassis", max_length=50, null=True
                    ),
                ),
                (
                    "nbreextinteur",
                    models.SmallIntegerField(
                        blank=True, db_column="nbreextinteur", null=True
                    ),
                ),
                ("idmarque", models.IntegerField(db_column="idmarque", default=0)),
                (
                    "typevehicule",
                    models.CharField(
                        blank=True, db_column="typevehicule", max_length=50, null=True
                    ),
                ),
                (
                    "modelevehicule",
                    models.CharField(
                        db_column="modelevehicule",
                        default="",
                        max_length=30,
                        verbose_name="Modèle du véhicule",
                    ),
                ),
                (
                    "attestation",
                    models.CharField(
                        db_column="attestation", default="", max_length=50
                    ),
                ),
                (
                    "typepermis",
                    models.CharField(
                        blank=True, db_column="typepermis", max_length=20, null=True
                    ),
                ),
                (
                    "permis",
                    models.CharField(
                        blank=True,
                        db_column="permis",
                        default="",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "datenaicnd",
                    models.DateTimeField(blank=True, db_column="datenaicnd", null=True),
                ),
                (
                    "iddelegation",
                    models.IntegerField(
                        blank=True, db_column="iddelegation", null=True
                    ),
                ),
                (
                    "agrement",
                    models.CharField(db_column="agrement", default="", max_length=50),
                ),
                (
                    "observation",
                    models.CharField(
                        db_column="observation", default="", max_length=50
                    ),
                ),
                (
                    "idolcontratdet",
                    models.IntegerField(db_column="idolcontratdet", default=0),
                ),
                (
                    "oldnumeropolice",
                    models.CharField(
                        db_column="oldnumeropolice", default="", max_length=50
                    ),
                ),
                (
                    "oldattestation",
                    models.CharField(
                        db_column="oldattestation", default="", max_length=50
                    ),
                ),
                ("oldmarque", models.IntegerField(db_column="oldmarque", default="")),
                (
                    "oldtypevehicule",
                    models.CharField(
                        db_column="oldtypevehicule", default="", max_length=50
                    ),
                ),
                (
                    "oldmatricule",
                    models.CharField(
                        db_column="oldmatricule", default="", max_length=50
                    ),
                ),
                (
                    "carteverte",
                    models.BooleanField(db_column="carteverte", default=False),
                ),
                (
                    "numcarteverte",
                    models.CharField(
                        db_column="numcarteverte", default="", max_length=50
                    ),
                ),
                (
                    "primeannuelle",
                    models.DecimalField(
                        db_column="primeannuelle",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "primenette",
                    models.DecimalField(
                        db_column="primenette",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "mt_delegation",
                    models.DecimalField(
                        db_column="mt_delegation",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "codecarburant",
                    models.CharField(
                        blank=True, db_column="codecarburant", max_length=10, null=True
                    ),
                ),
                (
                    "attestationprov",
                    models.CharField(
                        blank=True,
                        db_column="attestationprov",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pc_control",
                    models.BooleanField(db_column="pc_control", default=False),
                ),
                (
                    "cg_control",
                    models.BooleanField(db_column="cg_control", default=False),
                ),
                (
                    "numpccnd",
                    models.CharField(
                        blank=True,
                        db_column="numpccnd",
                        default="",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "pctype",
                    models.CharField(
                        db_column="pctype", default="000000000000", max_length=50
                    ),
                ),
                (
                    "taxeenregistrement",
                    models.DecimalField(
                        db_column="taxeenregistrement",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "idgenrevehicule",
                    models.ForeignKey(
                        db_column="idgenrevehicule",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.genrevehicule",
                        verbose_name="Id Genre Véhicule",
                    ),
                ),
                (
                    "idtypevehicule",
                    models.ForeignKey(
                        db_column="idtypevehicule",
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.typevehicule",
                        verbose_name="Id Type Véhicule",
                    ),
                ),
                (
                    "idusage",
                    models.ForeignKey(
                        db_column="idusage",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.usagevehicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de contrat",
                "verbose_name_plural": "Détails de contrat",
                "db_table": "stdcontratdetail",
            },
        ),
        migrations.CreateModel(
            name="AyantDroitIa",
            fields=[
                (
                    "id_ayant_droit",
                    models.AutoField(
                        db_column="idayantdroit",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Ayant-droit",
                    ),
                ),
                (
                    "id_assure",
                    models.IntegerField(db_column="idassure", verbose_name="Assuré"),
                ),
                (
                    "nom_ayant_droit",
                    models.CharField(
                        db_column="nomayantdroit", max_length=50, verbose_name="Nom"
                    ),
                ),
                (
                    "prenoms_ayant_droit",
                    models.CharField(
                        db_column="prenomsayantdroit",
                        max_length=60,
                        verbose_name="Prénoms",
                    ),
                ),
                (
                    "part",
                    models.DecimalField(
                        db_column="part",
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Part",
                    ),
                ),
                (
                    "id_qualite_ayant_droit",
                    models.ForeignKey(
                        db_column="idqualiteayantdroit",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.qualiteayantdroit",
                        verbose_name="Qualité",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayant-droit IA",
                "verbose_name_plural": "Ayant-droits IA",
                "db_table": "stdayantdroitia",
            },
        ),
        migrations.CreateModel(
            name="DevisDetGarantie",
            fields=[
                (
                    "IdDevisDetGarantie",
                    models.AutoField(
                        db_column="iddevisdetgarantie",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("IdDevisDet", models.IntegerField(db_column="iddevisdet")),
                ("Acquise", models.BooleanField(db_column="active")),
                (
                    "Capital",
                    models.DecimalField(
                        blank=True,
                        db_column="capital",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "Franchise",
                    models.DecimalField(
                        blank=True,
                        db_column="franchise",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "TexteFranchise",
                    models.CharField(
                        blank=True,
                        db_column="textefranchise",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "Formule",
                    models.SmallIntegerField(
                        blank=True, db_column="formule", null=True
                    ),
                ),
                (
                    "PrimeNette",
                    models.DecimalField(
                        db_column="primenette", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "old_acquise",
                    models.CharField(db_column="old_acquise", max_length=1),
                ),
                (
                    "old_capital",
                    models.DecimalField(
                        blank=True,
                        db_column="old_capital",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "old_franchise",
                    models.DecimalField(
                        blank=True,
                        db_column="old_franchise",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "old_formule",
                    models.SmallIntegerField(
                        blank=True, db_column="old_formule", null=True
                    ),
                ),
                (
                    "old_places",
                    models.SmallIntegerField(
                        blank=True, db_column="old_places", null=True
                    ),
                ),
                (
                    "old_primenette",
                    models.DecimalField(
                        db_column="old_primenette", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "deces",
                    models.DecimalField(
                        blank=True,
                        db_column="deces",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "ipp",
                    models.DecimalField(
                        blank=True,
                        db_column="ipp",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "fraismed",
                    models.DecimalField(
                        blank=True,
                        db_column="fraismed",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "hosp",
                    models.DecimalField(
                        blank=True,
                        db_column="hosp",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "minfranchise",
                    models.DecimalField(
                        db_column="minfranchise", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "maxfranchise",
                    models.DecimalField(
                        db_column="maxfranchise", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "primeannuelle",
                    models.DecimalField(
                        db_column="primeannuelle",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe", decimal_places=4, default=0, max_digits=19
                    ),
                ),
                (
                    "IdGarantie",
                    models.ForeignKey(
                        db_column="idgarantie",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_devis",
                        to="configuration_api.sousgarantie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garantie d'un devis",
                "verbose_name_plural": "Garanties d'un devis",
                "db_table": "stddevisdetgarantie",
                "unique_together": {("IdDevisDetGarantie", "IdDevisDet", "IdGarantie")},
            },
        ),
        migrations.CreateModel(
            name="DetailQuittance",
            fields=[
                (
                    "iddetquittance",
                    models.AutoField(
                        db_column="iddetquittance", primary_key=True, serialize=False
                    ),
                ),
                (
                    "tauxtaxe",
                    models.DecimalField(
                        db_column="tauxtaxe", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "tauxcommission",
                    models.DecimalField(
                        db_column="tauxcommission", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "primenette",
                    models.DecimalField(
                        db_column="primenette", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        db_column="commission", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "branche",
                    models.ForeignKey(
                        db_column="idbranche",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.branche",
                    ),
                ),
                (
                    "quittance",
                    models.ForeignKey(
                        db_column="idquittance",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.quittance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de quittance",
                "verbose_name_plural": "Lignes de quittance",
                "db_table": "stddetquittance",
                "unique_together": {
                    ("quittance", "branche", "tauxtaxe", "tauxcommission")
                },
            },
        ),
        migrations.CreateModel(
            name="ContratDetGarantie",
            fields=[
                (
                    "idcontratdetgarantie",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("idcontratdetail", models.IntegerField()),
                ("acquise", models.BooleanField()),
                (
                    "capital",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "franchise",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=19, null=True
                    ),
                ),
                (
                    "textefranchise",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("primeannuelle", models.DecimalField(decimal_places=4, max_digits=19)),
                ("primenette", models.DecimalField(decimal_places=4, max_digits=19)),
                ("taxe", models.DecimalField(decimal_places=4, max_digits=19)),
                ("minfranchise", models.DecimalField(decimal_places=4, max_digits=19)),
                ("maxfranchise", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "idgarantie",
                    models.ForeignKey(
                        db_column="idgarantie",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_contrat",
                        to="configuration_api.sousgarantie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Garantie souscrite",
                "verbose_name_plural": "Garanties souscrites",
                "db_table": "stdcontratdetgarantie",
                "unique_together": {
                    ("idcontratdetgarantie", "idcontratdetail", "idgarantie")
                },
            },
        ),
    ]
