# Generated by Django 4.1.4 on 2023-03-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="idquittance",
            field=models.ForeignKey(
                db_column="idquittance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.quittance",
            ),
        ),
    ]
