# Generated by Django 4.1.4 on 2023-03-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_contrat_idquittance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractForPremiumCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdContrat", models.IntegerField()),
                ("IdClient", models.IntegerField()),
                ("LibelleCategorie", models.CharField(max_length=100)),
                ("NumeroPolice", models.CharField(max_length=16)),
                ("NumeroAvenant", models.CharField(max_length=50)),
                ("NumeroQuittance", models.CharField(max_length=16)),
                ("NomClient", models.CharField(max_length=122)),
                ("DateEffet", models.DateField()),
                ("DateExpiration", models.DateField()),
                ("DateEmission", models.DateField()),
                ("Duree", models.IntegerField()),
                ("PrimeNette", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "TaxeEnregistrement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Commission", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Accessoire", models.DecimalField(decimal_places=4, max_digits=19)),
                ("PrimeTTC", models.DecimalField(decimal_places=4, max_digits=19)),
                ("Solde", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
