# Generated by Django 4.1.4 on 2023-03-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_contractforpremiumcollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quittance",
            name="quittanceanullation",
            field=models.ForeignKey(
                blank=True,
                db_column="idquittannul",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.quittance",
            ),
        ),
    ]
