# Generated by Django 4.1.4 on 2023-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0004_alter_quittance_quittanceanullation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratdetail",
            name="idolcontratdet",
            field=models.IntegerField(db_column="idoldcontratdet", default=0),
        ),
    ]
