# Generated by Django 4.1.4 on 2023-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0005_alter_contratdetail_idolcontratdet"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeContratPourEncaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referenceclient",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "referencecontrat",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EnregistrementEncaissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode_encaissement", models.IntegerField()),
                ("banque", models.IntegerField()),
                ("montant_total", models.DecimalField(decimal_places=4, max_digits=19)),
                ("numero_cheque", models.CharField(max_length=20)),
                ("reference_encaissement", models.CharField(max_length=40)),
                ("reference_compensation", models.CharField(max_length=10)),
                ("nom_emetteur", models.CharField(max_length=50)),
                ("liste_quittance", models.CharField(max_length=900)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
