# Generated by Django 4.1.4 on 2023-03-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0006_demandecontratpourencaissement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devisdetgarantie",
            name="Acquise",
            field=models.BooleanField(db_column="acquise"),
        ),
    ]
