# Generated by Django 4.1.4 on 2023-04-04 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("configuration_api", "0009_alter_zonecouverturesante_libellezone"),
        ("production", "0007_alter_devisdetgarantie_acquise"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReversementCompagnie",
            fields=[
                (
                    "id_reversement",
                    models.AutoField(
                        db_column="idreversement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Reversement",
                    ),
                ),
                (
                    "numero_reversement",
                    models.CharField(
                        db_column="numeroreversement",
                        max_length=16,
                        verbose_name="Numéro Reversement",
                    ),
                ),
                (
                    "date_reversement",
                    models.DateField(
                        db_column="datereversement", verbose_name="Date de reversement"
                    ),
                ),
                (
                    "montant_reversement",
                    models.DecimalField(
                        db_column="montantreversement",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Montant reversé",
                    ),
                ),
                (
                    "montant_en_attente",
                    models.DecimalField(
                        blank=True,
                        db_column="montantenattente",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "montant_deduit",
                    models.DecimalField(
                        blank=True,
                        db_column="montantdeduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(
                        blank=True, db_column="numerocheque", max_length=20, null=True
                    ),
                ),
                (
                    "compte_compensation",
                    models.CharField(
                        blank=True,
                        db_column="comptecompensation",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("date_saisie", models.DateTimeField(db_column="datesaisie")),
                ("piece_annulee", models.BooleanField(db_column="pieceannulee")),
                (
                    "date_annulation",
                    models.DateTimeField(
                        blank=True, db_column="dateannulation", null=True
                    ),
                ),
                (
                    "nom_annulation",
                    models.CharField(
                        blank=True, db_column="nomannulation", max_length=50, null=True
                    ),
                ),
                (
                    "motif_annulation",
                    models.CharField(
                        blank=True,
                        db_column="motifannulation",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "date_saisie_annulation",
                    models.DateTimeField(
                        blank=True, db_column="datesaisieannulation", null=True
                    ),
                ),
                (
                    "nom_tireur_cheque",
                    models.CharField(db_column="nomtireurcheque", max_length=50),
                ),
                (
                    "banque",
                    models.ForeignKey(
                        blank=True,
                        db_column="idbanque",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.banque",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.compagnie",
                        verbose_name="Compagnie",
                    ),
                ),
                (
                    "mode_reversement",
                    models.ForeignKey(
                        db_column="idmodereversement",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.modeencaissement",
                        verbose_name="Mode de reversement",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        db_column="idutilisateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversement de primes",
                "verbose_name_plural": "Reversements de primes",
                "db_table": "stdreversementcompagnie",
            },
        ),
        migrations.CreateModel(
            name="DetailReversement",
            fields=[
                (
                    "id_detail_reversement",
                    models.AutoField(
                        db_column="iddetailreversement",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        db_column="soldeinitial", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "montant_reverse",
                    models.DecimalField(
                        db_column="montantreverse",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Montant reversé",
                    ),
                ),
                (
                    "ded_commission_intermediaire",
                    models.BooleanField(db_column="dedcommission_intermediaire"),
                ),
                (
                    "ded_commission_gestionnaire",
                    models.BooleanField(db_column="dedcommission_gestionnaire"),
                ),
                (
                    "ded_commission_coassurance",
                    models.BooleanField(db_column="dedcommission_coassurance"),
                ),
                (
                    "ded_accessoire_intermediaire",
                    models.BooleanField(db_column="dedaccessoireintermediaire"),
                ),
                (
                    "ded_accessoire_gestionnaire",
                    models.BooleanField(db_column="dedaccessoiregestionnaire"),
                ),
                (
                    "ded_taxe_commission",
                    models.BooleanField(db_column="dedtaxecommission"),
                ),
                (
                    "ded_taxe_accessoire",
                    models.BooleanField(
                        blank=True,
                        db_column="dedtaxeaccessoire",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "com_intermediaire",
                    models.DecimalField(
                        blank=True,
                        db_column="comintermediaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "com_gestionnaire",
                    models.DecimalField(
                        blank=True,
                        db_column="comgestionnaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "com_conseiller",
                    models.DecimalField(
                        blank=True,
                        db_column="comconseiller",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "com_coassurance",
                    models.DecimalField(
                        blank=True,
                        db_column="comcoassurance",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "acc_intermediaire",
                    models.DecimalField(
                        blank=True,
                        db_column="accintermediaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "acc_gestionnaire",
                    models.DecimalField(
                        blank=True,
                        db_column="accgestionnaire",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "ded_coassurance",
                    models.BooleanField(
                        blank=True, db_column="dedcoassurance", null=True
                    ),
                ),
                (
                    "prime_cedee",
                    models.DecimalField(
                        blank=True,
                        db_column="primecedee",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "taxe_commission_deduit",
                    models.DecimalField(
                        blank=True,
                        db_column="taxe_commission_deduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "taxe_accessoire_deduit",
                    models.DecimalField(
                        blank=True,
                        db_column="taxeaccessoire_deduit",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                    ),
                ),
                (
                    "ligne_encaissement",
                    models.ForeignKey(
                        db_column="iddetailencaissement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.detailencaissement",
                    ),
                ),
                (
                    "reversement",
                    models.ForeignKey(
                        db_column="idreversement",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.reversementcompagnie",
                        verbose_name="Reversement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de reversement",
                "verbose_name_plural": "Lignes de reversement",
                "db_table": "stddetailreversement",
            },
        ),
    ]
