# Generated by Django 4.1.4 on 2023-04-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0008_reversementcompagnie_detailreversement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumCollectionInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NumeroRecu", models.CharField(max_length=16)),
                ("DateEncaissement", models.DateField()),
                ("NumeroCheque", models.CharField(max_length=20)),
                ("NomTireurCheque", models.CharField(max_length=60)),
                ("LibelleBanque", models.CharField(max_length=50)),
                ("LibelleModePaiement", models.CharField(max_length=60)),
                ("Reference", models.CharField(max_length=30)),
                (
                    "MontantEncaissement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("NumeroPolice", models.CharField(max_length=16)),
                ("DateEffet", models.DateField()),
                ("DateExpiration", models.DateField()),
                ("NomCompagnie", models.CharField(max_length=100)),
                ("NomAssure", models.CharField(max_length=60)),
                ("PrenomsAssure", models.CharField(max_length=60)),
                ("TelephoneAssure", models.CharField(max_length=20)),
                ("NumeroAvenant", models.CharField(max_length=50)),
                ("LibelleProduit", models.CharField(max_length=60)),
                ("PrimeTotale", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "VersementAnterieur",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "TotalVersement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Solde", models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
