# Generated by Django 4.1.4 on 2023-04-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0009_premiumcollectioninfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailencaissement",
            name="encaissement",
            field=models.ForeignKey(
                db_column="idencaissement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="production.encaissement",
            ),
        ),
    ]
