# Generated by Django 4.1.4 on 2023-04-22 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0010_alter_detailencaissement_encaissement"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumRemittanceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("NomClient", models.CharField(max_length=125)),
                ("LibelleProduit", models.CharField(max_length=80)),
                ("NumeroPolice", models.CharField(max_length=16)),
                ("NumeroAvenant", models.CharField(max_length=50)),
                ("DateEffet", models.DateField()),
                ("DateExpiration", models.DateField()),
                ("PrimeHT", models.DecimalField(decimal_places=4, max_digits=19)),
                ("PrimeTTC", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "MontantEncaissement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "AccessoireIntermediaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("TauxCommission", models.DecimalField(decimal_places=2, max_digits=5)),
                ("Commission", models.DecimalField(decimal_places=4, max_digits=19)),
                ("FraisGestion", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "CommissionDeduite",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("FraisDeduit", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "AccessoireDeduit",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "MontantReversement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("NomCompagnie", models.CharField(max_length=100)),
                ("DateReversement", models.DateField()),
                ("NumeroReversement", models.CharField(max_length=16)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.AlterField(
            model_name="detailreversement",
            name="reversement",
            field=models.ForeignKey(
                db_column="idreversement",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="production.reversementcompagnie",
                verbose_name="Reversement",
            ),
        ),
    ]
