# Generated by Django 4.1.4 on 2023-04-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0013_offresantepartarif"),
        ("production", "0011_premiumremittanceinfo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detailquittance",
            name="branche",
            field=models.ForeignKey(
                db_column="idbranchereassurance",
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.branche",
            ),
        ),
    ]
