# Generated by Django 4.1.4 on 2023-05-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0013_alter_detailquittance_branche"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssureIaInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_devis", models.IntegerField()),
                ("id_devis_detail", models.IntegerField()),
                ("id_assure", models.IntegerField()),
                ("nom", models.CharField(max_length=60)),
                ("prenoms", models.CharField(max_length=60, null=True)),
                ("date_naissance", models.DateField()),
                ("id_profession", models.IntegerField()),
                ("libelle_profession", models.CharField(max_length=150)),
                ("capital_deces", models.DecimalField(decimal_places=4, max_digits=19)),
                (
                    "capital_infirmite",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "capital_frais_traitement",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("telephone", models.CharField(max_length=20, null=True)),
                ("adresse_geographique", models.CharField(max_length=100, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
