# Generated by Django 4.1.4 on 2023-05-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0014_assureiainfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssureIaParDevisOuContrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdAssure", models.IntegerField()),
                ("IdDetail", models.IntegerField()),
                ("Nom", models.CharField(max_length=60)),
                ("Prenoms", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "AdressePostale",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "AdresseGeographique",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("DateNaissance", models.DateField(blank=True, null=True)),
                (
                    "LieuNaissance",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Profession", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
