# Generated by Django 4.1.4 on 2023-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0015_assureiapardevisoucontrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratdetgarantie",
            name="Formule",
            field=models.IntegerField(blank=True, db_column="formule", null=True),
        ),
        migrations.AddField(
            model_name="contratdetgarantie",
            name="deces",
            field=models.DecimalField(
                blank=True,
                db_column="deces",
                decimal_places=4,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contratdetgarantie",
            name="fraismed",
            field=models.DecimalField(
                blank=True,
                db_column="fraismed",
                decimal_places=4,
                max_digits=19,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contratdetgarantie",
            name="hosp",
            field=models.DecimalField(
                blank=True, db_column="hosp", decimal_places=4, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="contratdetgarantie",
            name="ipp",
            field=models.DecimalField(
                blank=True, db_column="ipp", decimal_places=4, max_digits=19, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devisdetgarantie",
            name="Formule",
            field=models.IntegerField(blank=True, db_column="formule", null=True),
        ),
    ]
