# Generated by Django 4.1.4 on 2023-05-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0016_contratdetgarantie_formule_contratdetgarantie_deces_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ayantdroitia",
            old_name="id_qualite_ayant_droit",
            new_name="qualite_ayant_droit",
        ),
    ]
