# Generated by Django 4.1.4 on 2023-05-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0017_rename_id_qualite_ayant_droit_ayantdroitia_qualite_ayant_droit",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="fga",
            field=models.DecimalField(
                db_column="fga", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="contratdetail",
            name="fga",
            field=models.DecimalField(
                db_column="fga", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="fga",
            field=models.DecimalField(
                db_column="fga", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="devisdetail",
            name="fga",
            field=models.DecimalField(
                db_column="fga", decimal_places=4, default=0, max_digits=19
            ),
        ),
    ]
