# Generated by Django 4.1.4 on 2023-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0018_contrat_fga_contratdetail_fga_devis_fga_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarantieSouscrite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idsousgarantie", models.IntegerField()),
                ("libellesousgarantie", models.CharField(max_length=100)),
                ("capital", models.DecimalField(decimal_places=4, max_digits=19)),
                ("primeannuelle", models.DecimalField(decimal_places=4, max_digits=19)),
                ("primenette", models.DecimalField(decimal_places=4, max_digits=19)),
                ("textefranchise", models.CharField(max_length=50)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
