# Generated by Django 4.1.4 on 2023-06-03 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0020_formulesecuriteroutiere"),
        ("production", "0019_garantiesouscrite"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratdetail",
            name="securite",
            field=models.ForeignKey(
                db_column="codealarme",
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.systemesecurite",
            ),
        ),
        migrations.AddField(
            model_name="contratdetail",
            name="taux_reduction",
            field=models.DecimalField(
                db_column="tauxreduction",
                decimal_places=2,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="Taux de réduction commerciale",
            ),
        ),
        migrations.AddField(
            model_name="devisdetail",
            name="taux_reduction",
            field=models.DecimalField(
                db_column="tauxreduction",
                decimal_places=2,
                default=0.0,
                max_digits=5,
                null=True,
                verbose_name="Taux de réduction commerciale",
            ),
        ),
        migrations.CreateModel(
            name="ComplementDevisDetailAuto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail Auto",
                    ),
                ),
                (
                    "taux_reduction_flotte",
                    models.DecimalField(
                        db_column="tauxreductionflotte",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de réduction flotte",
                    ),
                ),
                (
                    "bns",
                    models.DecimalField(
                        db_column="bns",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="BNS",
                    ),
                ),
                (
                    "carburant_autre_matiere",
                    models.BooleanField(
                        db_column="carburantautrematiere",
                        default=False,
                        null=True,
                        verbose_name="Carburant Autre Matière",
                    ),
                ),
                (
                    "transport_eleves",
                    models.BooleanField(
                        db_column="transporteleves",
                        default=False,
                        null=True,
                        verbose_name="Transport Elèves",
                    ),
                ),
                (
                    "transport_employes",
                    models.BooleanField(
                        db_column="transportemployes",
                        default=False,
                        null=True,
                        verbose_name="Transport Employes",
                    ),
                ),
                (
                    "transport_passager_supplementaire",
                    models.BooleanField(
                        db_column="transportpassagersupplementaire",
                        default=False,
                        null=True,
                        verbose_name="Transport Passager Supplementaire",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
                (
                    "formule_securite_routiere",
                    models.ForeignKey(
                        db_column="idformulesecuriteroutiere",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.formulesecuriteroutiere",
                        verbose_name="ID Formule Sécurité Routière",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetailauto",
            },
        ),
    ]
