# Generated by Django 4.1.4 on 2023-06-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0020_formulesecuriteroutiere"),
        (
            "production",
            "0020_contratdetail_securite_contratdetail_taux_reduction_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementContratDetailAuto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail Auto",
                    ),
                ),
                (
                    "taux_reduction_flotte",
                    models.DecimalField(
                        db_column="tauxreductionflotte",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de réduction flotte",
                    ),
                ),
                (
                    "bns",
                    models.DecimalField(
                        db_column="bns",
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        null=True,
                        verbose_name="BNS",
                    ),
                ),
                (
                    "carburant_autre_matiere",
                    models.BooleanField(
                        db_column="carburantautrematiere",
                        default=False,
                        null=True,
                        verbose_name="Carburant Autre Matière",
                    ),
                ),
                (
                    "transport_eleves",
                    models.BooleanField(
                        db_column="transporteleves",
                        default=False,
                        null=True,
                        verbose_name="Transport Elèves",
                    ),
                ),
                (
                    "transport_employes",
                    models.BooleanField(
                        db_column="transportemployes",
                        default=False,
                        null=True,
                        verbose_name="Transport Employes",
                    ),
                ),
                (
                    "transport_passager_supplementaire",
                    models.BooleanField(
                        db_column="transportpassagersupplementaire",
                        default=False,
                        null=True,
                        verbose_name="Transport Passager Supplementaire",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
                (
                    "formule_securite_routiere",
                    models.ForeignKey(
                        db_column="idformulesecuriteroutiere",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuration_api.formulesecuriteroutiere",
                        verbose_name="ID Formule Sécurité Routière",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetailauto",
            },
        ),
    ]
