# Generated by Django 4.1.4 on 2023-06-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0020_formulesecuriteroutiere"),
        ("production", "0021_complementcontratdetailauto"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementDevisDetailVoyage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail Voyage",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
                (
                    "zone_voyage",
                    models.ForeignKey(
                        db_column="idzonevoyage",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.zonevoyage",
                        verbose_name="ID Zone Voyage",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetailvoyage",
            },
        ),
        migrations.CreateModel(
            name="ComplementContratDetailVoyage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail Voyage",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
                (
                    "zone_voyage",
                    models.ForeignKey(
                        db_column="idzonevoyage",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.zonevoyage",
                        verbose_name="ID Zone Voyage",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetailvoyage",
            },
        ),
    ]
