# Generated by Django 4.1.4 on 2023-07-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0022_complementdevisdetailvoyage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="idduree",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="contrat",
            name="idterme",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="idduree",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="idterme",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
