# Generated by Django 4.1.4 on 2023-07-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0020_formulesecuriteroutiere"),
        ("production", "0023_contrat_idduree_contrat_idterme_devis_idduree_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complementcontratdetailvoyage",
            name="zone_voyage",
        ),
        migrations.RemoveField(
            model_name="complementdevisdetailvoyage",
            name="zone_voyage",
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="numero_attestation",
            field=models.CharField(
                blank=True,
                db_column="numeroattestation",
                default="",
                max_length=30,
                null=True,
                verbose_name="Numéro Attestation",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="numero_passeport",
            field=models.CharField(
                blank=True,
                db_column="numeropasseport",
                default="",
                max_length=30,
                null=True,
                verbose_name="Numéro Passeport",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="pays_destination",
            field=models.ForeignKey(
                db_column="idpaysdestination",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrats_pays_destination",
                to="configuration_api.pays",
                verbose_name="ID Pays Destination",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="pays_voyageur",
            field=models.ForeignKey(
                db_column="idpaysvoyageur",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contrats_pays_voyageur",
                to="configuration_api.pays",
                verbose_name="ID Pays Voyageur",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="reference_contrat",
            field=models.CharField(
                blank=True,
                db_column="referencecontrat",
                default="",
                max_length=50,
                null=True,
                verbose_name="Référence Contrat",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailvoyage",
            name="visa_schengen",
            field=models.BooleanField(
                blank=True,
                db_column="visaschengen",
                default=False,
                null=True,
                verbose_name="Schengen",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="numero_attestation",
            field=models.CharField(
                blank=True,
                db_column="numeroattestation",
                default="",
                max_length=30,
                null=True,
                verbose_name="Numéro Attestation",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="numero_passeport",
            field=models.CharField(
                blank=True,
                db_column="numeropasseport",
                default="",
                max_length=30,
                null=True,
                verbose_name="Numéro Passeport",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="pays_destination",
            field=models.ForeignKey(
                db_column="idpaysdestination",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devis_pays_destination",
                to="configuration_api.pays",
                verbose_name="ID Pays Destination",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="pays_voyageur",
            field=models.ForeignKey(
                db_column="idpaysvoyageur",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devis_pays_voyageur",
                to="configuration_api.pays",
                verbose_name="ID Pays Voyageur",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="reference_contrat",
            field=models.CharField(
                blank=True,
                db_column="referencecontrat",
                default="",
                max_length=50,
                null=True,
                verbose_name="Référence Contrat",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailvoyage",
            name="visa_schengen",
            field=models.BooleanField(
                blank=True,
                db_column="visaschengen",
                default=False,
                null=True,
                verbose_name="Schengen",
            ),
        ),
    ]
