# Generated by Django 4.1.4 on 2023-07-09 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0024_remove_complementcontratdetailvoyage_zone_voyage_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementDevisDetailDommage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail Dommage",
                    ),
                ),
                (
                    "taux_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="tauxprime",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de prime",
                    ),
                ),
                (
                    "montant_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="montantprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Montant de prime",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetaildommage",
            },
        ),
        migrations.CreateModel(
            name="ComplementContratDetailDommage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail Dommage",
                    ),
                ),
                (
                    "taux_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="tauxprime",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de prime",
                    ),
                ),
                (
                    "montant_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="montantprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Montant de prime",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetaildommage",
            },
        ),
    ]
