# Generated by Django 4.1.4 on 2023-07-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0025_complementdevisdetaildommage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementDevisDetailMrh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail MRH",
                    ),
                ),
                (
                    "presence_gardien",
                    models.BooleanField(
                        blank=True,
                        db_column="presencegardien",
                        default=False,
                        null=True,
                        verbose_name="Présence de gardien",
                    ),
                ),
                (
                    "occupant_locataire",
                    models.BooleanField(
                        blank=True,
                        db_column="occupantlocataire",
                        default=False,
                        null=True,
                        verbose_name="Occupant Locataire",
                    ),
                ),
                (
                    "valeur_loyer",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurloyer",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du loyer",
                    ),
                ),
                (
                    "valeur_contenu",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurcontenu",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du contenu",
                    ),
                ),
                (
                    "valeur_objet_precieux",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurobjetprecieux",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des objets précieux",
                    ),
                ),
                (
                    "valeur_materiel",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurmateriel",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du matériel",
                    ),
                ),
                (
                    "valeur_degat_batiment",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurdegatbatiment",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des dégâts au bâtiment",
                    ),
                ),
                (
                    "valeur_degat_contenu",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurdegatcontenu",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des dégâts au contenu",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        db_column="localisation",
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetailmrh",
            },
        ),
        migrations.CreateModel(
            name="ComplementContratDetailMrh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail MRH",
                    ),
                ),
                (
                    "presence_gardien",
                    models.BooleanField(
                        blank=True,
                        db_column="presencegardien",
                        default=False,
                        null=True,
                        verbose_name="Présence de gardien",
                    ),
                ),
                (
                    "occupant_locataire",
                    models.BooleanField(
                        blank=True,
                        db_column="occupantlocataire",
                        default=False,
                        null=True,
                        verbose_name="Occupant Locataire",
                    ),
                ),
                (
                    "valeur_loyer",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurloyer",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du loyer",
                    ),
                ),
                (
                    "valeur_contenu",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurcontenu",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du contenu",
                    ),
                ),
                (
                    "valeur_objet_precieux",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurobjetprecieux",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des objets précieux",
                    ),
                ),
                (
                    "valeur_materiel",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurmateriel",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur du matériel",
                    ),
                ),
                (
                    "valeur_degat_batiment",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurdegatbatiment",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des dégâts au bâtiment",
                    ),
                ),
                (
                    "valeur_degat_contenu",
                    models.DecimalField(
                        blank=True,
                        db_column="valeurdegatcontenu",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Valeur des dégâts au contenu",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        db_column="localisation",
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetailmrh",
            },
        ),
    ]
