# Generated by Django 4.1.4 on 2023-07-15 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0026_complementdevisdetailmrh_complementcontratdetailmrh"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementDevisDetailSante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail Santé",
                    ),
                ),
                (
                    "prime_famille",
                    models.DecimalField(
                        blank=True,
                        db_column="primefamille",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Famille",
                    ),
                ),
                (
                    "prime_affilie",
                    models.DecimalField(
                        blank=True,
                        db_column="primeaffilie",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Affilie",
                    ),
                ),
                (
                    "prime_globale",
                    models.DecimalField(
                        blank=True,
                        db_column="primeglobale",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Globale",
                    ),
                ),
                (
                    "montant_surprime",
                    models.DecimalField(
                        blank=True,
                        db_column="montantsurprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Montant Surprime",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetailsante",
            },
        ),
        migrations.CreateModel(
            name="ComplementContratDetailSante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail Santé",
                    ),
                ),
                (
                    "prime_famille",
                    models.DecimalField(
                        blank=True,
                        db_column="primefamille",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Famille",
                    ),
                ),
                (
                    "prime_affilie",
                    models.DecimalField(
                        blank=True,
                        db_column="primeaffilie",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Affilie",
                    ),
                ),
                (
                    "prime_globale",
                    models.DecimalField(
                        blank=True,
                        db_column="primeglobale",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Prime Globale",
                    ),
                ),
                (
                    "montant_surprime",
                    models.DecimalField(
                        blank=True,
                        db_column="montantsurprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Montant Surprime",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetailsante",
            },
        ),
    ]
