# Generated by Django 4.1.4 on 2023-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("production", "0027_complementdevisdetailsante_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quittance",
            name="police",
            field=models.CharField(
                db_column="numeropolice", max_length=50, verbose_name="Numéro Police"
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="numeropolice",
            field=models.CharField(db_column="numeropolice", max_length=50),
        ),
    ]
