# Generated by Django 4.1.4 on 2023-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0028_alter_contrat_numeropolice_alter_quittance_police"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encaissement",
            name="numeropiece",
            field=models.CharField(db_column="numeropiece", max_length=20),
        ),
    ]
