# Generated by Django 4.1.4 on 2023-07-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0021_assistanceautomobile"),
        ("production", "0029_alter_encaissement_numeropiece"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementcontratdetailauto",
            name="assistance_automobile",
            field=models.ForeignKey(
                db_column="idoptionassistance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.assistanceautomobile",
                verbose_name="ID Option Assistance",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailauto",
            name="assistance_automobile",
            field=models.ForeignKey(
                db_column="idoptionassistance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.assistanceautomobile",
                verbose_name="ID Option Assistance",
            ),
        ),
    ]
