# Generated by Django 4.1.4 on 2023-08-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0031_arreteexercice"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="motifannulation",
            field=models.CharField(
                blank=True, db_column="motifannulation", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="motifannulation",
            field=models.CharField(
                blank=True, db_column="motifannulation", max_length=255, null=True
            ),
        ),
    ]
