# Generated by Django 4.2.4 on 2023-08-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0032_contrat_motifannulation_devis_motifannulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="archive",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_archivage",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="operateur_archivage",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
