# Generated by Django 4.2.4 on 2023-08-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0033_devis_archive_devis_date_archivage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devis",
            name="date_archivage",
            field=models.DateTimeField(
                blank=True, db_column="datearchivage", null=True
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="operateur_archivage",
            field=models.IntegerField(
                blank=True, db_column="operateurarchivage", null=True
            ),
        ),
    ]
