# Generated by Django 4.2.4 on 2023-08-31 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0034_alter_devis_date_archivage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivageDevis",
            fields=[
                (
                    "id_archivage",
                    models.AutoField(
                        db_column="idarchivage", primary_key=True, serialize=False
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[("ARCHI", "ARCHIVAGE"), ("DESAR", "DESARCHIVAGE")],
                        db_column="typeoperation",
                        max_length=5,
                    ),
                ),
                ("date_archivage", models.DateTimeField(db_column="datearchivage")),
                (
                    "devis",
                    models.ForeignKey(
                        db_column="iddevis",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="production.devis",
                    ),
                ),
                (
                    "operateur_archivage",
                    models.ForeignKey(
                        db_column="operateurarchivage",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivage/Désarchivage de devis",
                "db_table": "stdarchivagedevis",
            },
        ),
        migrations.AddConstraint(
            model_name="archivagedevis",
            constraint=models.CheckConstraint(
                check=models.Q(("type_operation__in", ["ARCHI", "DESAR"])),
                name="archivage_devis_type_op_restreint",
            ),
        ),
    ]
