# Generated by Django 4.2.4 on 2023-09-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0035_archivagedevis_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idcontrat", models.IntegerField()),
                ("raisonsociale", models.CharField(max_length=100)),
                (
                    "adressecompagnie",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("idclient", models.IntegerField()),
                ("numeropolice", models.CharField(max_length=50)),
                ("numeroavenant", models.CharField(max_length=50)),
                ("nomclient", models.CharField(max_length=125)),
                (
                    "adresseclient",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dateeffet", models.DateField()),
                ("dateexpiration", models.DateField()),
                ("dateemission", models.DateField()),
                ("duree", models.IntegerField()),
                ("numeroimmatriculation", models.CharField(max_length=50)),
                (
                    "numeromoteur",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "numerochassis",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("libellecategorie", models.CharField(max_length=100)),
                ("libellemarque", models.CharField(max_length=60)),
                ("libellecarrosserie", models.CharField(max_length=100)),
                (
                    "titreclient",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professionclient",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("typeassure", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "typesouscripteur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "telephoneclient",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "mobileclient",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "adressegeographique",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("emailclient", models.CharField(max_length=125)),
                ("nomassure", models.CharField(max_length=125)),
                (
                    "adressepostaleassure",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "adressegeographiqueassure",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
