# Generated by Django 4.2.5 on 2024-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0036_infovehicule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratEcheance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_contrat", models.IntegerField()),
                ("numero_police", models.CharField(max_length=60)),
                ("numero_mobile", models.CharField(max_length=20)),
                ("date_expiration", models.DateField()),
                ("libelle_produit", models.CharField(max_length=60)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.CharField(max_length=255)),
                ("level_name", models.CharField(max_length=20)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
