# Generated by Django 4.2.5 on 2024-01-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0037_contratecheance_logrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Numero",
        ),
    ]
