# Generated by Django 4.2.5 on 2024-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0038_delete_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Numero",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idmodule", models.CharField(db_column="idmodule", max_length=5)),
                ("exercice", models.SmallIntegerField(db_column="exercice")),
                ("libelle", models.CharField(db_column="libelle", max_length=50)),
                ("numero", models.IntegerField(db_column="numero")),
                ("cloture", models.BooleanField(db_column="cloture")),
            ],
            options={
                "db_table": "stdnumero",
                "unique_together": {("idmodule", "exercice")},
            },
        ),
    ]
