# Generated by Django 4.2.5 on 2024-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0039_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementcontratdetailsante",
            name="montant_accessoire_manuel",
            field=models.DecimalField(
                blank=True,
                db_column="montantaccessoiremanuel",
                decimal_places=4,
                default=0,
                max_digits=19,
                null=True,
                verbose_name="Montant Accessoire Manuel",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailsante",
            name="montant_accessoire_manuel",
            field=models.DecimalField(
                blank=True,
                db_column="montantaccessoiremanuel",
                decimal_places=4,
                default=0,
                max_digits=19,
                null=True,
                verbose_name="Montant Accessoire Manuel",
            ),
        ),
    ]
