# Generated by Django 4.2.5 on 2024-03-05 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0047_typecontratsante"),
        (
            "production",
            "0040_complementcontratdetailsante_montant_accessoire_manuel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="complementcontratdetailsante",
            name="gestionnaire_sante",
            field=models.CharField(
                blank=True, db_column="gestionnairesante", max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailsante",
            name="taux_reduction_commerciale",
            field=models.DecimalField(
                blank=True,
                db_column="tauxreductioncommerciale",
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="Taux Réduction Commerciale",
            ),
        ),
        migrations.AddField(
            model_name="complementcontratdetailsante",
            name="type_contrat",
            field=models.ForeignKey(
                db_column="idtypecontrat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.typecontratsante",
                verbose_name="ID Type Contrat",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailsante",
            name="gestionnaire_sante",
            field=models.CharField(
                blank=True, db_column="gestionnairesante", max_length=60, null=True
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailsante",
            name="taux_reduction_commerciale",
            field=models.DecimalField(
                blank=True,
                db_column="tauxreductioncommerciale",
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="Taux Réduction Commerciale",
            ),
        ),
        migrations.AddField(
            model_name="complementdevisdetailsante",
            name="type_contrat",
            field=models.ForeignKey(
                db_column="idtypecontrat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.typecontratsante",
                verbose_name="ID Type Contrat",
            ),
        ),
    ]
