# Generated by Django 4.2.5 on 2024-04-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0041_complementcontratdetailsante_gestionnaire_sante_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementDevisDetailRC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Devis Détail RC",
                    ),
                ),
                (
                    "taux_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="tauxprime",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de prime",
                    ),
                ),
                (
                    "assiette_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="assietteprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Assiette de prime",
                    ),
                ),
                (
                    "nombre_participants",
                    models.IntegerField(
                        blank=True,
                        db_column="nombreparticipants",
                        default=0,
                        null=True,
                        verbose_name="Nombre de participants",
                    ),
                ),
                (
                    "id_domaine_activite",
                    models.IntegerField(
                        blank=True,
                        db_column="iddomaineactivite",
                        default=0,
                        null=True,
                        verbose_name="Domaine d'activités",
                    ),
                ),
                (
                    "id_activite",
                    models.IntegerField(
                        blank=True,
                        db_column="idactivite",
                        default=0,
                        null=True,
                        verbose_name="Activité",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        db_column="localisation",
                        max_length=60,
                        null=True,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True,
                        db_column="datedebut",
                        null=True,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "devis_detail",
                    models.ForeignKey(
                        db_column="iddevisdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devisdetail",
                        verbose_name="ID Devis Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementdevisdetailrc",
            },
        ),
        migrations.CreateModel(
            name="ComplementContratDetailRC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idcomplement",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Complément Contrat Détail RC",
                    ),
                ),
                (
                    "taux_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="tauxprime",
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de prime",
                    ),
                ),
                (
                    "assiette_prime",
                    models.DecimalField(
                        blank=True,
                        db_column="assietteprime",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        null=True,
                        verbose_name="Assiette de prime",
                    ),
                ),
                (
                    "nombre_participants",
                    models.IntegerField(
                        blank=True,
                        db_column="nombreparticipants",
                        default=0,
                        null=True,
                        verbose_name="Nombre de participants",
                    ),
                ),
                (
                    "id_domaine_activite",
                    models.IntegerField(
                        blank=True,
                        db_column="iddomaineactivite",
                        default=0,
                        null=True,
                        verbose_name="Domaine d'activités",
                    ),
                ),
                (
                    "id_activite",
                    models.IntegerField(
                        blank=True,
                        db_column="idactivite",
                        default=0,
                        null=True,
                        verbose_name="Activité",
                    ),
                ),
                (
                    "localisation",
                    models.CharField(
                        blank=True,
                        db_column="localisation",
                        max_length=60,
                        null=True,
                        verbose_name="Localisation",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True,
                        db_column="datedebut",
                        null=True,
                        verbose_name="Date de début",
                    ),
                ),
                (
                    "contrat_detail",
                    models.ForeignKey(
                        db_column="idcontratdetail",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.contratdetail",
                        verbose_name="ID Contrat Détail",
                    ),
                ),
            ],
            options={
                "db_table": "stdcomplementcontratdetailrc",
            },
        ),
    ]
