# Generated by Django 4.2.5 on 2024-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0042_complementdevisdetailrc_complementcontratdetailrc"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="numero_police_connexe",
            field=models.CharField(
                blank=True,
                db_column="numeropoliceconnexe",
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="numero_police_connexe",
            field=models.CharField(
                blank=True,
                db_column="numeropoliceconnexe",
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
