# Generated by Django 4.2.5 on 2024-06-03 21:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0043_contrat_numero_police_connexe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="encaissement",
            name="referencetransaction",
            field=models.UUIDField(
                db_column="referencetransaction",
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Reference Transaction Mobile",
            ),
        ),
    ]
