# Generated by Django 4.2.5 on 2024-06-03 21:52

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Encaissement = apps.get_model("production", "Encaissement")
    for row in Encaissement.objects.all():
        row.referencetransaction = uuid.uuid4()
        row.save(update_fields=["referencetransaction"])


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0044_encaissement_referencetransaction"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
