# Generated by Django 4.2.5 on 2024-06-03 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0045_auto_20240603_2152"),
    ]

    operations = [
        migrations.AlterField(
            model_name="encaissement",
            name="referencetransaction",
            field=models.UUIDField(
                db_column="referencetransaction",
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=True,
                verbose_name="Reference Transaction Mobile",
            ),
        ),
    ]
