# Generated by Django 4.2.13 on 2024-09-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0046_auto_20240603_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="id_police_pegas",
            field=models.CharField(
                blank=True,
                db_column="idpolicepegas",
                default="",
                max_length=14,
                null=True,
            ),
        ),
    ]
