# Generated by Django 4.2.13 on 2024-09-24 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0048_contrat_id_police_pegas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificatTransport",
            fields=[
                (
                    "id_certificat",
                    models.AutoField(
                        db_column="idcertificat",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Certificat",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        db_column="statut", max_length=20, verbose_name="Statut"
                    ),
                ),
                (
                    "numero_requete",
                    models.CharField(
                        db_column="numerorequete",
                        max_length=20,
                        unique=True,
                        verbose_name="No. Requête",
                    ),
                ),
                (
                    "date_requete",
                    models.DateField(
                        db_column="daterequete", verbose_name="Date Requête"
                    ),
                ),
                (
                    "reference_certificat",
                    models.CharField(
                        db_column="referencecertificat",
                        max_length=20,
                        verbose_name="Référence Certificat",
                    ),
                ),
                (
                    "date_certificat",
                    models.DateField(
                        db_column="datecertificat", verbose_name="Date Certificat"
                    ),
                ),
                (
                    "numero_police",
                    models.CharField(
                        db_column="numeropolice",
                        max_length=15,
                        verbose_name="Numéro Police d'Assurance",
                    ),
                ),
                (
                    "numero_fdi",
                    models.CharField(
                        blank=True,
                        db_column="numerofdi",
                        max_length=15,
                        null=True,
                        verbose_name="Numéro FDI",
                    ),
                ),
                (
                    "date_fdi",
                    models.DateField(
                        db_column="datefdi", null=True, verbose_name="Date FDI"
                    ),
                ),
                (
                    "assureur",
                    models.CharField(
                        db_column="assureur", max_length=255, verbose_name="Assureur"
                    ),
                ),
                (
                    "adresse_assureur",
                    models.CharField(
                        db_column="adresseassureur",
                        max_length=255,
                        verbose_name="Adresse Assureur",
                    ),
                ),
                (
                    "id_souscripteur_guce",
                    models.CharField(
                        blank=True,
                        db_column="idsouscripteurguce",
                        max_length=30,
                        null=True,
                        verbose_name="ID Souscripteur GUCE",
                    ),
                ),
                (
                    "nom_souscripteur",
                    models.CharField(
                        db_column="nomsouscripteur",
                        max_length=255,
                        verbose_name="Souscripteur",
                    ),
                ),
                (
                    "adresse_souscripteur",
                    models.CharField(
                        db_column="adressesouscripteur",
                        max_length=255,
                        verbose_name="Adresse souscripteur",
                    ),
                ),
                (
                    "assure",
                    models.CharField(
                        db_column="assure", max_length=255, verbose_name="Assuré"
                    ),
                ),
                (
                    "adresse_assure",
                    models.CharField(
                        db_column="adresseassure",
                        max_length=255,
                        verbose_name="Adresse Assuré",
                    ),
                ),
                (
                    "intermediaire",
                    models.CharField(
                        db_column="intermediaire",
                        max_length=60,
                        verbose_name="Intermédiaire",
                    ),
                ),
                (
                    "moyen_transport",
                    models.CharField(
                        db_column="moyentransport",
                        max_length=60,
                        verbose_name="Moyen de Transport",
                    ),
                ),
                (
                    "date_debut_voyage",
                    models.DateField(
                        db_column="datedebutvoyage", verbose_name="Date Début Voyage"
                    ),
                ),
                (
                    "voyage",
                    models.CharField(
                        db_column="voyage", max_length=120, verbose_name="Voyage"
                    ),
                ),
                (
                    "description_commerciale",
                    models.CharField(
                        db_column="descriptioncommerciale",
                        max_length=100,
                        verbose_name="Description Commerciale",
                    ),
                ),
                (
                    "marque_colis",
                    models.CharField(
                        db_column="marquecolis",
                        max_length=80,
                        verbose_name="Marque de Colis",
                    ),
                ),
                (
                    "numero_document_transport",
                    models.CharField(
                        db_column="numerodocumenttransport",
                        max_length=40,
                        verbose_name="Numéro Document Transport",
                    ),
                ),
                (
                    "reference_precedente",
                    models.CharField(
                        blank=True,
                        db_column="referenceprecedente",
                        max_length=20,
                        null=True,
                        verbose_name="Réf. Précédente",
                    ),
                ),
                (
                    "reference_subsequente",
                    models.CharField(
                        blank=True,
                        db_column="referencesubsequente",
                        max_length=20,
                        null=True,
                        verbose_name="Réf. Subséquente",
                    ),
                ),
                (
                    "valeur_assurance",
                    models.DecimalField(
                        db_column="valeurassurance",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Valeur Assurance",
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        db_column="primenette",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime Nette",
                    ),
                ),
                (
                    "accessoire",
                    models.DecimalField(
                        db_column="accessoire",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Accessories",
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Montant Taxe",
                    ),
                ),
                (
                    "prime_ttc",
                    models.DecimalField(
                        db_column="primettc",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime Totale",
                    ),
                ),
                (
                    "date_debut_periode",
                    models.DateField(
                        db_column="datedebutperiode", verbose_name="Date Début Periode"
                    ),
                ),
                (
                    "date_fin_periode",
                    models.DateField(
                        db_column="datefinperiode", verbose_name="Date Fin Periode"
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificat d'assurance",
                "verbose_name_plural": "Certificats d'assurance",
                "db_table": "stdcertificattransport",
            },
        ),
        migrations.CreateModel(
            name="HistoriqueImportationCertificat",
            fields=[
                (
                    "id_importation",
                    models.AutoField(
                        db_column="idimportation",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Importation",
                    ),
                ),
                (
                    "nom_fichier_excel",
                    models.CharField(
                        db_column="nomfichierexcel",
                        max_length=255,
                        verbose_name="Nom Fichier Excel",
                    ),
                ),
                (
                    "sha256_hash",
                    models.BinaryField(
                        db_column="sha256hash", verbose_name="Checksum Fichier"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "date_debut_periode",
                    models.DateField(
                        db_column="datedebutperiode", verbose_name="Début Periode"
                    ),
                ),
                (
                    "date_fin_periode",
                    models.DateField(
                        db_column="datefinperiode", verbose_name="Fin Periode"
                    ),
                ),
                (
                    "succes",
                    models.BooleanField(
                        db_column="succes", default=False, verbose_name="Succès"
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        db_column="idoperateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur Importation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'importation - Transport",
                "db_table": "stdhistoriqueimportationcertificat",
            },
        ),
        migrations.CreateModel(
            name="ImportationCertificatDevis",
            fields=[
                (
                    "id_importation_devis",
                    models.AutoField(
                        db_column="idimportationdevis",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Importation Devis",
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        db_column="iddevis",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.devis",
                        verbose_name="ID Devis",
                    ),
                ),
                (
                    "historique_importation",
                    models.ForeignKey(
                        db_column="idhistoriqueimportation",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="production.historiqueimportationcertificat",
                        verbose_name="ID Historique Importation",
                    ),
                ),
            ],
            options={
                "db_table": "stdimportationcertificatdevis",
            },
        ),
        migrations.AddConstraint(
            model_name="certificattransport",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin_periode__gt", models.F("date_debut_periode"))
                ),
                name="certificat_transport_debut_plus_grand_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="historiqueimportationcertificat",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("date_fin_periode__gt", models.F("date_debut_periode"))
                ),
                name="histo_import_debut_plus_grand_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="historiqueimportationcertificat",
            constraint=models.UniqueConstraint(
                fields=("date_debut_periode", "date_fin_periode"),
                name="histo_import_unique_for_period",
            ),
        ),
    ]
