# Generated by Django 4.2.13 on 2024-09-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0049_certificattransport_historiqueimportationcertificat_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="certificattransport",
            name="id_souscripteur_guce",
        ),
        migrations.AddField(
            model_name="certificattransport",
            name="id_client_uranus",
            field=models.IntegerField(
                blank=True,
                db_column="idclienturanus",
                null=True,
                verbose_name="ID Client URANUS",
            ),
        ),
    ]
