# Generated by Django 4.2.13 on 2024-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0050_remove_certificattransport_id_souscripteur_guce_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiqueimportationcertificat",
            name="sha256_hash",
            field=models.BinaryField(
                db_column="sha256hash", null=True, verbose_name="Checksum Fichier"
            ),
        ),
    ]
