# Generated by Django 4.2.13 on 2024-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0051_alter_historiqueimportationcertificat_sha256_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificattransport",
            name="description_commerciale",
            field=models.CharField(
                db_column="descriptioncommerciale",
                max_length=255,
                verbose_name="Description Commerciale",
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="marque_colis",
            field=models.CharField(
                db_column="marquecolis", max_length=255, verbose_name="Marque de Colis"
            ),
        ),
    ]
