# Generated by Django 4.2.13 on 2024-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0052_alter_certificattransport_description_commerciale_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificattransport",
            name="numero_document_transport",
            field=models.CharField(
                blank=True,
                db_column="numerodocumenttransport",
                max_length=40,
                null=True,
                verbose_name="Numéro Document Transport",
            ),
        ),
    ]
