# Generated by Django 4.2.13 on 2024-10-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0053_alter_certificattransport_numero_document_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="numero_police_compagnie",
            field=models.CharField(
                blank=True,
                db_column="numeropolicecompagnie",
                default="",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="numero_police_compagnie",
            field=models.CharField(
                blank=True,
                db_column="numeropolicecompagnie",
                default="",
                max_length=60,
                null=True,
            ),
        ),
    ]
