# Generated by Django 4.2.13 on 2024-11-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0054_contrat_numero_police_compagnie_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="contrat",
            constraint=models.CheckConstraint(
                check=models.Q(("dateexpiration__gte", models.F("dateeffet"))),
                name="contrat_date_expiration_plus_grande_date_effet",
            ),
        ),
        migrations.AddConstraint(
            model_name="devis",
            constraint=models.CheckConstraint(
                check=models.Q(("dateexpiration__gte", models.F("dateeffet"))),
                name="devis_date_expiration_plus_grande_date_effet",
            ),
        ),
    ]
