# Generated by Django 4.2.13 on 2025-10-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0055_contrat_contrat_date_expiration_plus_grande_date_effet_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="prime_imposee",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="prime_imposee",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
