# Generated by Django 4.2.13 on 2025-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0056_contrat_prime_imposee_devis_prime_imposee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="prime_imposee",
            field=models.BooleanField(
                blank=True, db_column="primeimposee", default=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="prime_imposee",
            field=models.BooleanField(
                blank=True, db_column="primeimposee", default=False, null=True
            ),
        ),
    ]
