# Generated by Django 4.2.13 on 2025-10-24 14:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0057_alter_contrat_prime_imposee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="date_consolidation",
            field=models.DateTimeField(
                blank=True, db_column="dateconsolidation", null=True
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, db_column="datecreation", null=True
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_modification",
            field=models.DateTimeField(
                auto_now=True, db_column="datemodification", null=True
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="devis_consolide",
            field=models.ForeignKey(
                blank=True,
                db_column="iddevisconsolide",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_sources",
                to="production.devis",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="statut",
            field=models.CharField(db_column="statut", default="ACTIF", max_length=50),
        ),
        migrations.CreateModel(
            name="HistoriqueConsolidation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="idhistoriqueconsolidation",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_devis_source",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        help_text="Liste des IDs des devis consolidés",
                        size=None,
                    ),
                ),
                (
                    "date_consolidation",
                    models.DateTimeField(
                        auto_now_add=True, db_column="dateconsolidation"
                    ),
                ),
                (
                    "id_utilisateur",
                    models.IntegerField(
                        blank=True, db_column="idutilisateur", null=True
                    ),
                ),
                (
                    "devis_consolide",
                    models.ForeignKey(
                        db_column="iddevisconsolide",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historiques_consolidation",
                        to="production.devis",
                    ),
                ),
            ],
            options={
                "db_table": "stdhistoriqueconsolidation",
                "ordering": ["-date_consolidation"],
            },
        ),
    ]
