# Generated by Django 4.2.13 on 2025-10-24 16:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0058_devis_date_consolidation_devis_date_creation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiqueconsolidation",
            name="id_devis_source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(),
                db_column="iddevissource",
                help_text="Liste des IDs des devis consolidés",
                size=None,
            ),
        ),
    ]
