# Generated by Django 4.2.13 on 2025-10-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0059_alter_historiqueconsolidation_id_devis_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devisdetail",
            name="iddevis",
            field=models.ForeignKey(
                db_column="iddevis",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="production.devis",
            ),
        ),
    ]
