# Generated by Django 4.2.13 on 2025-11-07 18:45

from django.db import migrations
from uranus.utils.migrations import load_sql_from_app


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0060_alter_devisdetail_iddevis"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_app(__file__, "procedures/sp_correction_devis_ia.sql"),
            reverse_sql=(
                "DROP PROCEDURE IF EXISTS public.sp_correction_devis_ia("
                "INT, NUMERIC, NUMERIC, CHARACTER VARYING)"
            ),
        )
    ]
