# Generated by Django 4.2.13 on 2025-11-10 10:41

from django.db import migrations
from uranus.utils.migrations import load_sql_from_app


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0061_sp_correction_devis_ia"),
    ]

    operations = [
        migrations.RunSQL(
            sql=load_sql_from_app(__file__, "functions/fn_liste_vehicule_flotte.sql"),
            reverse_sql=load_sql_from_app(
                __file__, "functions/fn_liste_vehicule_flotte_reverse.sql"
            ),
        )
    ]
