# Generated by Django 4.2.13 on 2025-11-10 23:17

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0062_fn_liste_vehicule_flotte"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "procedures/sp_correction_devis_ia.sql",
                "procedures/sp_correction_devis_ia_reverse.sql",
            ),
        )
    ]
