# Generated by Django 4.2.13 on 2025-11-11 09:02

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0063_update_sp_correction_devis_ia"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "functions/fn_liste_contrat_encaissement.sql",
                "functions/fn_liste_contrat_encaissement_reverse.sql",
            ),
        )
    ]
