# Generated by Django 4.2.13 on 2025-11-11 12:38

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0064_fn_liste_contrat_encaissement"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "functions/fn_quittance_contrat.sql",
                "functions/fn_quittance_contrat_reverse.sql",
            )
        )
    ]
