# Generated by Django 4.2.13 on 2025-11-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0065_fn_quittance_contrat"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="cedeao",
            field=models.DecimalField(
                db_column="cedeao", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="cedeao",
            field=models.DecimalField(
                db_column="cedeao", decimal_places=4, default=0, max_digits=19
            ),
        ),
    ]
