# Generated by Django 4.2.13 on 2025-11-24 11:53

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0066_contrat_cedeao_devis_cedeao"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "raw/contrat_devis_cedeao_default_zero.sql",
                "raw/contrat_devis_cedeao_default_zero_reverse.sql",
            )
        )
    ]
