# Generated by Django 4.2.13 on 2025-11-24 13:01

from django.db import migrations
from uranus.utils.migrations import load_sql_pair

class Migration(migrations.Migration):

    dependencies = [
        ("production", "0067_contrat_devis_cedeao_default_zero"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "functions/fn_get_prime_cedeao.sql",
                "functions/fn_get_prime_cedeao_reverse.sql",
            )
        )
        ]
