# Generated by Django 4.2.13 on 2025-11-24 13:18

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0068_fn_get_prime_cedeao"),
    ]

    operations = [
        
        migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "procedures/sp_finalisation_devis.sql",
                "procedures/sp_finalisation_devis_reverse.sql",
            )
        )
    ]
