# Generated by Django 4.2.13 on 2025-11-24 13:25

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0069_sp_finalisation_devis"),
    ]

    operations = [
        
            migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "procedures/sp_confirmation_devis.sql",
                "procedures/sp_confirmation_devis_reverse.sql",
            )
        )
    ]
