# Generated by Django 4.2.13 on 2025-11-24 13:40

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0070_sp_confirmation_devis"),
    ]

    operations = [
        
               
            migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "functions/fn_quittance_contrat.sql",
                "functions/fn_quittance_contrat_reverse.sql",
            )
        )
    ]
