# Generated by Django 4.2.13 on 2025-11-24 13:47

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0071_fn_quittance_contrat"),
    ]

    
    operations = [
        
               
            migrations.RunSQL(
            *load_sql_pair(
                __file__,
                "functions/fn_quittance_proposition.sql",
                "functions/fn_quittance_proposition_reverse.sql",
            )
        )
    ]
