# Generated by Django 4.2.13 on 2025-11-26 00:00

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0073_fn_get_valeur_venale_vehicule"),
    ]

    operations = [
        
        migrations.RunSQL(
            *load_sql_pair(__file__,
                           "functions/fn_get_code_genre_vehicule.sql",
                           "functions/fn_get_code_genre_vehicule_reverse.sql",
                           )
        )
    ]
