# Generated by Django 4.2.13 on 2025-11-26 00:16

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0074_fn_get_code_genre_vehicule"),
    ]

    operations = [
        
        migrations.RunSQL(*load_sql_pair(__file__,
                                         "procedures/sp_avenant_creation_devis_initial.sql",
                                         "procedures/sp_avenant_creation_devis_initial_reverse.sql"
                                         )
                          
                          )
    ]
