# Generated by Django 4.2.13 on 2025-12-01 13:04

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0075_sp_avenant_creation_devis_initial"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'functions/fn_get_date_expiration.sql', 'functions/fn_get_date_expiration_reverse.sql'))
    ]
