# Generated by Django 4.2.13 on 2025-12-01 13:43

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0076_fn_get_date_expiration"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'functions/fn_get_nouvelle_periode_couverture.sql', 'functions/fn_get_nouvelle_periode_couverture_reverse.sql'))
    ]
