# Generated by Django 4.2.13 on 2025-12-01 14:12

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0077_fn_get_nouvelle_periode_couverture"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'procedures/sp_avenant_renouvellement.sql', 'procedures/sp_avenant_renouvellement_reverse.sql'))
    ]