# Generated by Django 4.2.13 on 2025-12-02 12:54

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0078_sp_avenant_renouvellement"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'procedures/sp_avenant_initiation.sql', 'procedures/sp_avenant_initiation_reverse.sql'))
    ]
