# Generated by Django 4.2.13 on 2025-12-02 13:03

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0079_sp_avenant_initiation"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'procedures/sp_avenant_renouvellement.sql', 'procedures/sp_avenant_renouvellement_reverse.sql'))
    ]
