# Generated by Django 4.2.13 on 2025-12-03 11:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_alter_client_matricule"),
        ("production", "0080_sp_avenant_renouvellement"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceFacture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "annee",
                    models.IntegerField(
                        help_text="Année pour la séquence (e.g., 2025)"
                    ),
                ),
                (
                    "mois",
                    models.IntegerField(help_text="Mois pour la séquence (1 à 12)"),
                ),
                (
                    "dernier_numero_devis",
                    models.IntegerField(
                        default=0,
                        help_text="Le dernier numéro séquentiel attribué aux factures proforma pour ce mois et cette année.",
                    ),
                ),
                (
                    "dernier_numero_contrat",
                    models.IntegerField(
                        default=0,
                        help_text="Le dernier numéro séquentiel attribué aux factures de contrat pour ce mois et cette année.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Séquence de factures mensuelle",
                "verbose_name_plural": "Séquences de factures mensuelles",
                "db_table": "stdsequencefacture",
                "unique_together": {("annee", "mois")},
            },
        ),
        migrations.CreateModel(
            name="Maison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_maison",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("adresse", models.TextField()),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=100)),
                (
                    "usage_habitation",
                    models.CharField(
                        choices=[
                            (
                                "proprietaire_occupant_total",
                                "Propriétaire occupant total",
                            ),
                            (
                                "proprietaire_occupant_partiel",
                                "Propriétaire occupant partiel",
                            ),
                            (
                                "proprietaire_non_occupant_meuble",
                                "Propriétaire non occupant - Location meublée",
                            ),
                            ("proprietaire_non_occupant", "Propriétaire non occupant"),
                            ("locataire_meuble", "Locataire en meublé"),
                            ("locataire_partiel", "Locataire partiel"),
                            ("logement_fonction", "Logement de fonction"),
                            ("locataire", "Locataire"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "valeur_maison",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "cout_location_mensuel",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "surface_m2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("nombre_pieces", models.IntegerField(blank=True, null=True)),
                ("annee_construction", models.IntegerField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maisons",
                        to="customer.client",
                    ),
                ),
            ],
            options={
                "db_table": "maison",
                "ordering": ["-date_creation"],
            },
        ),
    ]
