# Generated by Django 4.2.13 on 2025-12-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0081_sequencefacture_maison"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sequencefacture",
            name="dernier_numero_contrat",
            field=models.IntegerField(
                db_column="derniernumerocontrat",
                default=0,
                help_text="Le dernier numéro séquentiel attribué aux factures de contrat pour ce mois et cette année.",
            ),
        ),
        migrations.AlterField(
            model_name="sequencefacture",
            name="dernier_numero_devis",
            field=models.IntegerField(
                db_column="derniernumerodevis",
                default=0,
                help_text="Le dernier numéro séquentiel attribué aux factures proforma pour ce mois et cette année.",
            ),
        ),
    ]
