# Generated by Django 4.2.13 on 2025-12-03 13:10

from django.db import migrations
from uranus.utils.migrations import load_sql_pair

class Migration(migrations.Migration):

    dependencies = [
        ("production", "0082_alter_sequencefacture_dernier_numero_contrat_and_more"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'functions/fn_generer_numero_facture.sql', 'functions/fn_generer_numero_facture_reverse.sql'))
        
    ]
