# Generated by Django 4.2.13 on 2025-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0083_fn_generer_numero_facture"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="numero_facture",
            field=models.CharField(
                blank=True,
                db_column="numerofacture",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="numero_facture",
            field=models.CharField(
                blank=True,
                db_column="numerofacture",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
