# Generated by Django 4.2.13 on 2025-12-03 15:10

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0084_contrat_numero_facture_devis_numero_facture"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'functions/set_numero_facture_before_insert.sql', 'functions/set_numero_facture_before_insert_reverse.sql'))
    ]
