# Generated by Django 4.2.13 on 2025-12-03 15:22

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0085_set_numero_facture_before_insert"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'triggers/trg_numerotation_facture_devis.sql', 'triggers/trg_numerotation_facture_devis_reverse.sql'))
    ]
