# Generated by Django 4.2.13 on 2025-12-03 15:22

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0086_trg_numerotation_facture_devis"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'triggers/trg_numerotation_facture_contrat.sql', 'triggers/trg_numerotation_facture_contrat_reverse.sql'))
    ]
