# Generated by Django 4.2.13 on 2025-12-04 00:09

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0087_trg_numerotation_facture_contrat"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'functions/fn_quittance_contrat', from_version=1, to_version=2))
    ]
