# Generated by Django 4.2.13 on 2025-12-04 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "configuration_api",
            "0056_alter_genrevehicule_codegenre_depreciationvehicule_and_more",
        ),
        ("production", "0089_fn_quittance_proposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="reversementcompagnie",
            name="date_validation",
            field=models.DateTimeField(
                blank=True, db_column="datevalidation", null=True
            ),
        ),
        migrations.AddField(
            model_name="reversementcompagnie",
            name="utilisateur_validation",
            field=models.ForeignKey(
                blank=True,
                db_column="idutilisateurvalidation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validations_reversement",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reversementcompagnie",
            name="valide",
            field=models.BooleanField(db_column="valide", default=False),
        ),
        migrations.AlterField(
            model_name="reversementcompagnie",
            name="date_reversement",
            field=models.DateField(
                blank=True,
                db_column="datereversement",
                null=True,
                verbose_name="Date de reversement",
            ),
        ),
        migrations.AlterField(
            model_name="reversementcompagnie",
            name="mode_reversement",
            field=models.ForeignKey(
                blank=True,
                db_column="idmodereversement",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="configuration_api.modeencaissement",
                verbose_name="Mode de reversement",
            ),
        ),
        migrations.AlterField(
            model_name="reversementcompagnie",
            name="nom_tireur_cheque",
            field=models.CharField(
                blank=True, db_column="nomtireurcheque", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reversementcompagnie",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                db_column="idutilisateur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enregistrements_reversement",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
