# Generated by Django 4.2.13 on 2025-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0090_reversementcompagnie_date_validation_and_more"),
    ]

    operations = [
        # On corrige le montant du règlement avant de définir la constrainte: cette mise à jour est irreversible
        migrations.RunSQL(
            sql="""
                UPDATE public.stddetailencaissement
                SET montantreglement = montant_encaissement
                WHERE montantreglement > montant_encaissement;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddConstraint(
            model_name="detailencaissement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("montant_encaissement__gte", models.F("montantreglement"))
                ),
                name="enc_montant_encaissement_gte_montantreglement",
            ),
        ),
    ]
