# Generated by Django 4.2.13 on 2025-12-04 22:04

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0091_detailencaissement_enc_montant_encaissement_gte_montantreglement",
        ),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'procedures/sp_enregistrement_reversement', from_version=1, to_version=2))
    ]
