# Generated by Django 4.2.13 on 2025-12-05 05:45

from django.db import migrations
from uranus.utils.migrations import load_sql_from_app


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0092_sp_enregistrement_reversement"),
    ]

    operations = [
        migrations.RunSQL(sql=load_sql_from_app(__file__,'procedures/sp_validation_reversement/v1.sql'), reverse_sql="DROP PROCEDURE IF EXISTS public.sp_validation_reversement;")
    ]
