# Generated by Django 4.2.13 on 2025-12-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0056_alter_genrevehicule_codegenre_depreciationvehicule_and_more",
        ),
        ("customer", "0011_alter_client_matricule"),
        ("production", "0093_sp_validation_reversement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="idavenant",
            field=models.ForeignKey(
                db_column="idavenant",
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.avenant",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="idclient",
            field=models.ForeignKey(
                db_column="idclient",
                on_delete=django.db.models.deletion.CASCADE,
                to="customer.client",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="idcompagnie",
            field=models.ForeignKey(
                blank=True,
                db_column="idcompagnie",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.compagnie",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="iddevis",
            field=models.ForeignKey(
                db_column="iddevis",
                on_delete=django.db.models.deletion.CASCADE,
                to="production.devis",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="idintermediaire",
            field=models.ForeignKey(
                db_column="idintermediaire",
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.intermediaire",
            ),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="idproduit",
            field=models.ForeignKey(
                db_column="idproduit",
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.produit",
            ),
        ),
    ]
