# Generated by Django 4.2.13 on 2025-12-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0094_alter_contrat_idavenant_alter_contrat_idclient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="idcontratannulation",
            field=models.IntegerField(
                blank=True, db_column="idcontratannulation", null=True
            ),
        ),
    ]
