# Generated by Django 4.2.13 on 2025-12-06 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0095_alter_contrat_idcontratannulation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="encaissement",
            options={
                "ordering": ["-dateencaissement"],
                "verbose_name": "Encaissement",
                "verbose_name_plural": "Encaissements",
            },
        ),
        migrations.RemoveField(
            model_name="encaissement",
            name="idutilisateur",
        ),
        migrations.AddField(
            model_name="encaissement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="encaissement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="encaissement",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                db_column="idutilisateur",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="encaissements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="encaissement",
            index=models.Index(
                fields=["numeropiece"], name="stdencaisse_numerop_e8b48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encaissement",
            index=models.Index(
                fields=["piece_annulee", "dateencaissement"],
                name="stdencaisse_piece_a_98b509_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encaissement",
            index=models.Index(
                fields=["utilisateur", "dateencaissement"],
                name="stdencaisse_idutili_aae444_idx",
            ),
        ),
    ]
