# Generated by Django 4.2.13 on 2025-12-06 23:10

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0096_alter_encaissement_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'procedures/sp_annulation_encaissement', from_version=1, to_version=2))
    ]
