# Generated by Django 4.2.13 on 2025-12-07 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0098_sp_enregistrement_encaissement"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="detailencaissement",
            name="enc_montant_encaissement_gte_montantreglement",
        ),
    ]
