# Generated by Django 4.2.13 on 2025-12-07 00:15

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0099_remove_detailencaissement_enc_montant_encaissement_gte_montantreglement",
        ),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'functions/fn_encaissement_check_montant_encaissement.sql', 'functions/fn_encaissement_check_montant_encaissement_reverse.sql'))
    ]
