# Generated by Django 4.2.13 on 2025-12-07 00:28

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0100_fn_encaissement_check_montant_encaissement"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'triggers/trg_encaissement_check_montant_encaissement.sql', 'triggers/trg_encaissement_check_montant_encaissement_reverse.sql'))
    ]
