# Generated by Django 4.2.13 on 2025-12-09 09:27

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0101_trg_encaissement_check_montant_encaissement"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'functions/fn_get_devis', from_version=1, to_version=2))
    ]
