# Generated by Django 4.2.13 on 2025-12-10 18:44

from django.db import migrations
from uranus.utils.migrations import load_sql_pair   


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0102_fn_get_devis"),
    ]

    operations = [
        
        migrations.RunSQL(*load_sql_pair(__file__, 'indexes/index_fn_get_devis.sql', 'indexes/index_fn_get_devis_reverse.sql'))
    ]
