# Generated by Django 4.2.13 on 2025-12-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0103_index_fn_get_devis"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Maison",
        ),
    ]
