# Generated by Django 4.2.13 on 2025-12-18 09:35

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0104_delete_maison"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'functions/fn_liste_contrat_encaissement', from_version=1, to_version=2))
    ]
