# Generated by Django 4.2.13 on 2025-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0105_fn_liste_contrat_encaissement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devisdetail",
            name="auteur",
            field=models.BooleanField(default=False),
        ),
    ]
