# Generated by Django 4.2.13 on 2026-01-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0106_alter_devisdetail_auteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrat",
            name="taux_commission",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="quittance",
            name="taux_commission",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="contrat",
            name="idquittance",
            field=models.OneToOneField(
                db_column="idquittance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrat",
                to="production.quittance",
            ),
        ),
    ]
