# Generated by Django 4.2.13 on 2026-01-21 09:18

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0107_contrat_taux_commission_quittance_taux_commission_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'functions/fn_init_client_comptes', from_version=0, to_version=1))
    ]
