# Generated by Django 4.2.13 on 2026-01-21 09:40

from django.db import migrations
from uranus.utils.migrations import load_sql_pair


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0108_fn_init_client_comptes"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_pair(__file__, 'triggers/trg_initialisation_comptes_client.sql', 'triggers/trg_initialisation_comptes_client_reverse.sql'))
    ]
