# Generated by Django 4.2.13 on 2026-01-21 11:32

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0109_trg_initialisation_comptes_client"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'procedures/sp_enregistrement_encaissement', from_version=2, to_version=3))
    ]
