# Generated by Django 4.2.13 on 2026-01-21 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0110_sp_enregistrement_encaissement"),
    ]

    operations = [
        migrations.AddField(
            model_name="devisdetail",
            name="iddevisorigine",
            field=models.ForeignKey(
                db_column="iddevisorigine",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="details_origine",
                to="production.devis",
            ),
        ),
    ]
