# Generated by Django 4.2.13 on 2026-01-21 14:24

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0111_devisdetail_iddevisorigine"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'procedures/sp_consolidation_devis', from_version=1, to_version=2))
    ]
