# Generated by Django 4.2.13 on 2026-01-21 14:40

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0112_sp_consolidation_devis"),
    ]

    operations = [
        migrations.RunSQL(*load_sql_upgrade(__file__, 'procedures/sp_annulation_consolidation_devis', from_version=0, to_version=1))
    ]
