# Generated by Django 4.2.13 on 2026-01-28 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("configuration_api", "0060_parametrage_complement_mrh"),
        ("production", "0113_sp_annulation_consolidation_devis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id_cheque",
                    models.AutoField(
                        db_column="idcheque", primary_key=True, serialize=False
                    ),
                ),
                (
                    "numero_cheque",
                    models.CharField(db_column="numerocheque", max_length=50),
                ),
                (
                    "montant_initial",
                    models.DecimalField(
                        db_column="montantinitial", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "solde_disponible",
                    models.DecimalField(
                        db_column="soldedisponible", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "date_saisie",
                    models.DateTimeField(auto_now_add=True, db_column="datesaisie"),
                ),
                (
                    "banque",
                    models.ForeignKey(
                        db_column="idbanque",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuration_api.banque",
                    ),
                ),
            ],
            options={
                "db_table": "stdcheque",
            },
        ),
        migrations.CreateModel(
            name="ChequeOperation",
            fields=[
                (
                    "id_operation",
                    models.AutoField(
                        db_column="idoperation", primary_key=True, serialize=False
                    ),
                ),
                ("id_encaissement", models.IntegerField(db_column="idencaissement")),
                (
                    "montant_operation",
                    models.DecimalField(
                        db_column="montantoperation", decimal_places=4, max_digits=19
                    ),
                ),
                ("date_operation", models.DateField(db_column="dateoperation")),
                (
                    "date_saisie",
                    models.DateTimeField(auto_now_add=True, db_column="datesaisie"),
                ),
                (
                    "cheque",
                    models.ForeignKey(
                        db_column="idcheque",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="production.cheque",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        db_column="idutilisateur",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stdchequeoperation",
            },
        ),
        migrations.AddConstraint(
            model_name="cheque",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("montant_initial__gte", models.F("solde_disponible")),
                    ("solde_disponible__gte", 0),
                ),
                name="check_solde_coherence",
            ),
        ),
        migrations.AddConstraint(
            model_name="cheque",
            constraint=models.CheckConstraint(
                check=models.Q(("montant_initial__gt", 0)),
                name="check_montant_initial_positif",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cheque",
            unique_together={("numero_cheque", "banque")},
        ),
    ]
