# Generated by Django 4.2.13 on 2026-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "production",
            "0114_cheque_chequeoperation_cheque_check_solde_coherence_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpositionPrime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_imposition",
                    models.CharField(
                        choices=[
                            ("DEVIS", "Devis (global)"),
                            ("MAISON", "Maison (individuelle)"),
                        ],
                        help_text="DEVIS pour imposition globale, MAISON pour imposition individuelle",
                        max_length=20,
                        verbose_name="Type d'imposition",
                    ),
                ),
                (
                    "id_cible",
                    models.IntegerField(
                        help_text="ID du devis (si DEVIS) ou ID du DevisDetail (si MAISON)",
                        verbose_name="ID de la cible",
                    ),
                ),
                (
                    "montant_impose",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Montant de la prime NETTE imposée (en FCFA)",
                        max_digits=19,
                        verbose_name="Montant imposé",
                    ),
                ),
                (
                    "ancien_montant_nette",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Prime nette avant l'imposition",
                        max_digits=19,
                        null=True,
                        verbose_name="Ancien montant prime nette",
                    ),
                ),
                (
                    "ancien_montant_ttc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Prime TTC avant l'imposition",
                        max_digits=19,
                        null=True,
                        verbose_name="Ancien montant prime TTC",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de l'utilisateur qui a imposé la prime",
                        null=True,
                        verbose_name="ID utilisateur",
                    ),
                ),
                (
                    "user_nom",
                    models.CharField(
                        blank=True,
                        help_text="Nom complet de l'utilisateur",
                        max_length=200,
                        null=True,
                        verbose_name="Nom utilisateur",
                    ),
                ),
                (
                    "date_imposition",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date et heure de l'imposition",
                        verbose_name="Date d'imposition",
                    ),
                ),
                (
                    "motif",
                    models.TextField(
                        blank=True,
                        help_text="Raison de l'imposition (ex: négociation commerciale)",
                        null=True,
                        verbose_name="Motif",
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="TRUE si l'imposition est active, FALSE si levée",
                        verbose_name="Actif",
                    ),
                ),
                (
                    "date_levee",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure où l'imposition a été levée",
                        null=True,
                        verbose_name="Date de levée",
                    ),
                ),
                (
                    "levee_par_user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="ID de l'utilisateur qui a levé l'imposition",
                        null=True,
                        verbose_name="Levée par user ID",
                    ),
                ),
                (
                    "levee_par_user_nom",
                    models.CharField(
                        blank=True,
                        help_text="Nom de l'utilisateur qui a levé l'imposition",
                        max_length=200,
                        null=True,
                        verbose_name="Levée par user nom",
                    ),
                ),
                (
                    "motif_levee",
                    models.TextField(
                        blank=True,
                        help_text="Raison de la levée de l'imposition",
                        null=True,
                        verbose_name="Motif de levée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imposition de prime MRH",
                "verbose_name_plural": "Impositions de prime MRH",
                "db_table": "stdmrh_imposition_prime",
                "ordering": ["-date_imposition"],
            },
        ),
        migrations.AddField(
            model_name="devis",
            name="prime_imposee_date",
            field=models.DateTimeField(
                blank=True,
                db_column="primeimposeedate",
                help_text="Date et heure de l'imposition de la prime",
                null=True,
                verbose_name="Date imposition prime",
            ),
        ),
        migrations.AddField(
            model_name="devisdetail",
            name="prime_imposee",
            field=models.BooleanField(
                db_column="primeimposee",
                default=False,
                help_text="Indique si la prime de cette maison est imposée (non recalculable)",
                verbose_name="Prime imposée",
            ),
        ),
        migrations.AddField(
            model_name="devisdetail",
            name="prime_imposee_date",
            field=models.DateTimeField(
                blank=True,
                db_column="primeimposeedate",
                help_text="Date et heure de l'imposition de la prime",
                null=True,
                verbose_name="Date imposition prime",
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="prime_imposee",
            field=models.BooleanField(
                blank=True,
                db_column="primeimposee",
                default=False,
                help_text="Indique si la prime globale du devis est imposée (non recalculable)",
                null=True,
                verbose_name="Prime imposée",
            ),
        ),
        migrations.AddIndex(
            model_name="devis",
            index=models.Index(
                fields=["prime_imposee"], name="idx_devis_prime_imposee"
            ),
        ),
        migrations.AddIndex(
            model_name="devisdetail",
            index=models.Index(fields=["prime_imposee"], name="idx_dd_prime_imposee"),
        ),
        migrations.AddIndex(
            model_name="impositionprime",
            index=models.Index(
                fields=["type_imposition", "id_cible"], name="idx_impo_type_cible"
            ),
        ),
        migrations.AddIndex(
            model_name="impositionprime",
            index=models.Index(fields=["actif"], name="idx_impo_actif"),
        ),
        migrations.AddIndex(
            model_name="impositionprime",
            index=models.Index(fields=["-date_imposition"], name="idx_impo_date"),
        ),
    ]
