# Generated by Django 4.2.13 on 2026-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0115_impositionprime_devis_prime_imposee_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ayantdroitia",
            name="nom_ayant_droit",
            field=models.CharField(
                db_column="nomayantdroit", max_length=80, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="ayantdroitia",
            name="prenoms_ayant_droit",
            field=models.CharField(
                db_column="prenomsayantdroit", max_length=80, verbose_name="Prénoms"
            ),
        ),
    ]
