# Generated by Django 4.2.13 on 2026-02-04 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0116_alter_ayantdroitia_nom_ayant_droit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportsHistorique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hash_fichier",
                    models.CharField(
                        db_index=True,
                        help_text="Hash SHA256 du fichier pour détecter les doublons",
                        max_length=64,
                        unique=True,
                        verbose_name="Hash du fichier",
                    ),
                ),
                (
                    "nom_fichier",
                    models.CharField(max_length=255, verbose_name="Nom du fichier"),
                ),
                (
                    "taille_fichier",
                    models.BigIntegerField(
                        help_text="Taille en octets", verbose_name="Taille du fichier"
                    ),
                ),
                (
                    "date_import",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Date d'import",
                    ),
                ),
                (
                    "user_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="ID de l'utilisateur ayant effectué l'import",
                        null=True,
                        verbose_name="ID Utilisateur",
                    ),
                ),
                (
                    "mode_import",
                    models.CharField(
                        default="creer_seulement",
                        help_text="creer_seulement, mettre_a_jour, erreur_si_doublon, ignorer_silencieux",
                        max_length=50,
                        verbose_name="Mode d'import",
                    ),
                ),
                (
                    "nb_assures_total",
                    models.IntegerField(
                        default=0,
                        help_text="Nombre total de lignes dans le fichier",
                        verbose_name="Nombre total d'assurés",
                    ),
                ),
                (
                    "nb_assures_nouveaux",
                    models.IntegerField(default=0, verbose_name="Assurés créés"),
                ),
                (
                    "nb_assures_ignores",
                    models.IntegerField(
                        default=0,
                        help_text="Assurés ignorés car déjà existants",
                        verbose_name="Assurés ignorés",
                    ),
                ),
                (
                    "nb_assures_mis_a_jour",
                    models.IntegerField(default=0, verbose_name="Assurés mis à jour"),
                ),
                (
                    "nb_erreurs",
                    models.IntegerField(default=0, verbose_name="Nombre d'erreurs"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("REUSSI", "Réussi"),
                            ("ECHOUE", "Échoué"),
                            ("PARTIEL", "Partiel"),
                            ("REFUSE", "Refusé"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "details_erreur",
                    models.TextField(
                        blank=True, null=True, verbose_name="Détails de l'erreur"
                    ),
                ),
                (
                    "id_devis",
                    models.IntegerField(
                        blank=True,
                        help_text="ID du devis créé lors de l'import",
                        null=True,
                        verbose_name="ID Devis",
                    ),
                ),
                (
                    "duree_secondes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Durée (secondes)",
                    ),
                ),
                (
                    "details_json",
                    models.JSONField(
                        blank=True,
                        help_text="Détails complets de l'import en JSON",
                        null=True,
                        verbose_name="Détails JSON",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import d'assurés",
                "verbose_name_plural": "Historique des imports",
                "db_table": "stdimports_historique",
                "ordering": ["-date_import"],
                "indexes": [
                    models.Index(fields=["hash_fichier"], name="idx_imports_hash"),
                    models.Index(fields=["-date_import"], name="idx_imports_date"),
                    models.Index(fields=["user_id"], name="idx_imports_user"),
                    models.Index(fields=["statut"], name="idx_imports_statut"),
                ],
            },
        ),
    ]
