# Generated by Django 4.2.13 on 2026-02-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0117_importshistorique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratdetail",
            name="conducteur",
            field=models.TextField(
                blank=True, db_column="conducteur", max_length=2048, null=True
            ),
        ),
        migrations.AlterField(
            model_name="devisdetail",
            name="conducteur",
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
    ]
