# Generated by Django 4.2.13 on 2026-02-13 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0118_alter_contratdetail_conducteur_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier",
                    models.FileField(
                        help_text="Fichier PDF ou image (JPG, PNG)",
                        upload_to="pieces_jointes/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("nom_original", models.CharField(max_length=255)),
                ("type_fichier", models.CharField(max_length=50)),
                ("taille", models.IntegerField(help_text="Taille en octets")),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "db_table": "pieces_jointes",
            },
        ),
        migrations.AddField(
            model_name="contrat",
            name="piece_jointe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contrats",
                to="production.piecejointe",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="piece_jointe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis",
                to="production.piecejointe",
            ),
        ),
    ]
