# Generated by Django 4.2.13 on 2026-02-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0063_chk_libelle_format_stddomaineactivite"),
        ("production", "0119_piecejointe_contrat_piece_jointe_devis_piece_jointe"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="devisdetgarantie",
            unique_together={("IdDevisDet", "IdGarantie")},
        ),
    ]
