# Generated by Django 4.2.13 on 2026-02-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0120_alter_devisdetgarantie_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devisdetgarantie",
            name="IdDevisDet",
            field=models.ForeignKey(
                db_column="iddevisdet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garanties",
                to="production.devisdetail",
            ),
        ),
    ]
