# Generated by Django 4.2.13 on 2026-02-21 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0121_alter_devisdetgarantie_iddevisdet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratdetgarantie",
            name="idcontratdetail",
            field=models.ForeignKey(
                db_column="idcontratdetail",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garanties",
                to="production.contratdetail",
            ),
        ),
    ]
