# Generated by Django 4.2.13 on 2026-02-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0122_alter_contratdetgarantie_idcontratdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratdetgarantie",
            name="tauxfranchise",
            field=models.DecimalField(
                blank=True,
                db_column="tauxfranchise",
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devisdetgarantie",
            name="tauxfranchise",
            field=models.DecimalField(
                blank=True,
                db_column="tauxfranchise",
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contratdetail",
            name="idcontrat",
            field=models.ForeignKey(
                db_column="idcontrat",
                on_delete=django.db.models.deletion.CASCADE,
                to="production.contrat",
            ),
        ),
    ]
