# Generated by Django 4.2.13 on 2026-03-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0123_contratdetgarantie_tauxfranchise_and_more"),
    ]

    operations = []
