# Generated by Django 4.2.17 on 2026-04-15 13:48

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade



class Migration(migrations.Migration):

    """
    ajout de la condition lien_affilie = 'A' AND avant le EXISTS dans la branche ELSE (mise à jour), ligne ~142 du corps de la procédure
    """
  
    dependencies = [
        ("production", "0124_sp_creation_devis_sante"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_saisie_affilie_sante",
                from_version=1,
                to_version=2,
            )
        )
    ]
