# Generated by Django 4.2.17 on 2026-04-24 14:44

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade

class Migration(migrations.Migration):

    dependencies = [
        ("production", "0125_sp_saisie_affilie_sante"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_creation_devis_ia",
                from_version=1,
                to_version=2,
            )
        )
    ]
