# Generated by Django 4.2.17 on 2026-04-24 14:45

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade

class Migration(migrations.Migration):

    dependencies = [
        ("production", "0127_sp_enregistrement_assure_ia"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_finalisation_devis",
                from_version=1,
                to_version=2,
            )
        )
    ]
