# Generated by Django 4.2.17 on 2026-04-26 17:26

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0130_sp_avenant_creation_devis_initial"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "functions/fn_get_nouvelle_periode_couverture",
                from_version=1,
                to_version=2,
            )
        )
    ]
