# Generated by Django 4.2.17 on 2026-05-04 14:58

from django.db import migrations
from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0131_fn_get_nouvelle_periode_couverture"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_avenant_incorporation",
                from_version=1,
                to_version=2,
            )
        )
    ]
