# Generated by Django 4.2.13 on 2026-05-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0124_sp_creation_devis_voyage"),
        ("production", "0131_fn_get_nouvelle_periode_couverture"),
    ]

    operations = []
