# Generated by Django 4.2.13 on 2026-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0132_merge_20260512_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificattransport",
            name="accessoire_afs_ci",
            field=models.DecimalField(
                db_column="accessoireafsci",
                decimal_places=4,
                default=500,
                max_digits=19,
                null=True,
                verbose_name="Accessoires AFS-CI",
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="adresse_assure",
            field=models.TextField(
                db_column="adresseassure", verbose_name="Adresse Assuré"
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="adresse_assureur",
            field=models.TextField(
                db_column="adresseassureur", verbose_name="Adresse Assureur"
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="adresse_souscripteur",
            field=models.TextField(
                db_column="adressesouscripteur",
                verbose_name="Adresse souscripteur",
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="assure",
            field=models.CharField(
                db_column="assure", max_length=512, verbose_name="Assuré"
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="assureur",
            field=models.CharField(
                db_column="assureur", max_length=512, verbose_name="Assureur"
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="description_commerciale",
            field=models.TextField(
                db_column="descriptioncommerciale",
                verbose_name="Description Commerciale",
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="nom_souscripteur",
            field=models.CharField(
                db_column="nomsouscripteur",
                max_length=512,
                verbose_name="Souscripteur",
            ),
        ),
        migrations.AlterField(
            model_name="certificattransport",
            name="voyage",
            field=models.CharField(
                db_column="voyage", max_length=255, verbose_name="Voyage"
            ),
        ),
    ]
