# Generated by Django 4.2.13 on 2026-05-13 22:24

from django.db import migrations

from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0133_certificattransport_accessoire_afs_ci_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_generation_devis_transport_client",
                from_version=1,
                to_version=2,
            )
        )
    ]


####################################################################################


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0130_sp_avenant_creation_devis_initial"),
    ]
