# Generated by Django 4.2.13 on 2026-05-14 14:40

from django.db import migrations

from uranus.utils.migrations import load_sql_upgrade


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0133_certificattransport_accessoire_afs_ci_and_more"),
        ("production", "0134_sp_generation_devis_transport_client"),
    ]

    operations = [
        migrations.RunSQL(
            *load_sql_upgrade(
                __file__,
                "procedures/sp_generation_contrat_transport",
                from_version=1,
                to_version=2,
            )
        )
    ]
