# Generated by Django 4.2.13 on 2026-05-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0132_sp_avenant_incorporation"),
        ("production", "0135_sp_generation_contrat_transport"),
    ]

    operations = []
