# Generated by Django 4.2.17 on 2026-05-18 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0132_sp_avenant_incorporation"),
        ("production", "0135_sp_generation_contrat_transport"),
    ]

    operations = []
