# Generated by Django 4.2.13 on 2026-09-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0139_fn_get_accessoire_suppression_plus1_offre154"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contrat",
            name="auteur",
            field=models.BooleanField(db_column="auteur", default=False),
        ),
        migrations.AlterField(
            model_name="contratdetail",
            name="oldmarque",
            field=models.IntegerField(db_column="oldmarque", default=0),
        ),
        migrations.AlterField(
            model_name="detailencaissement",
            name="dedtaxeaccessoire",
            field=models.BooleanField(
                blank=True, db_column="dedtaxeaccessoire", null=True
            ),
        ),
        migrations.AlterField(
            model_name="detailreversement",
            name="ded_taxe_accessoire",
            field=models.BooleanField(
                blank=True, db_column="dedtaxeaccessoire", null=True
            ),
        ),
    ]
