# Generated by Django 4.2.13 on 2026-09-25 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("production", "0141_fn_calcul_prime_prorata_bns_bris_glace_toits"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brouillon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_brouillon",
                    models.CharField(
                        choices=[
                            ("DEVIS_AUTO", "Devis automobile"),
                            ("AVENANT", "Modification de contrat"),
                        ],
                        default="DEVIS_AUTO",
                        max_length=30,
                    ),
                ),
                ("libelle", models.CharField(blank=True, default="", max_length=255)),
                ("etape", models.PositiveSmallIntegerField(default=1)),
                ("donnees", models.JSONField(default=dict)),
                (
                    "iddevis",
                    models.IntegerField(
                        blank=True,
                        help_text="Devis existant en cours de modification",
                        null=True,
                    ),
                ),
                (
                    "idcontrat",
                    models.IntegerField(
                        blank=True,
                        help_text="Contrat en cours de modification",
                        null=True,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="brouillons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brouillon",
                "verbose_name_plural": "Brouillons",
                "db_table": "lephare_brouillon",
                "ordering": ["-date_modification"],
            },
        ),
    ]
