// Realistic Mock Data for LE PHARE – Logiciel Métier de Courtage & Sinistres V2

export const mockUsers = [
  {
    id: 1,
    username: 'admin',
    email: 'direction.generale@lephare-ci.com',
    first_name: 'Franck',
    last_name: 'Gnogouri',
    role: 'ADMIN',
    role_code: 'DIR_GEN',
    role_label: 'Direction Générale & Arbitrage Stratégique',
    avatar: 'FG',
    is_active: true,
  },
  {
    id: 2,
    username: 'dir_technique',
    email: 'production@lephare-ci.com',
    first_name: 'Valérie',
    last_name: 'Brou',
    role: 'USER',
    role_code: 'DIR_TECH',
    role_label: 'Direction Technique & Souscription',
    avatar: 'VB',
    is_active: true,
  },
  {
    id: 3,
    username: 'dir_sinistres',
    email: 'sinistres@lephare-ci.com',
    first_name: 'Dr. Marcelle',
    last_name: 'Yao',
    role: 'USER',
    role_code: 'DIR_SINISTRES',
    role_label: 'Direction Sinistres & Gestion Déléguée',
    avatar: 'MY',
    is_active: true,
  },
  {
    id: 4,
    username: 'comptable',
    email: 'tresorerie@lephare-ci.com',
    first_name: 'Jean-Marc',
    last_name: 'Kouame',
    role: 'USER',
    role_code: 'FINANCE',
    role_label: 'Finance, Trésorerie & Encaissements',
    avatar: 'JK',
    is_active: true,
  },
  {
    id: 5,
    username: 'commercial',
    email: 'commercial@lephare-ci.com',
    first_name: 'Awa',
    last_name: 'Kone',
    role: 'USER',
    role_code: 'COMMERCIAL',
    role_label: 'Conseillère Commerciale & CRM',
    avatar: 'AK',
    is_active: true,
  },
  {
    id: 6,
    username: 'backoffice',
    email: 'backoffice@lephare-ci.com',
    first_name: 'Mamadou',
    last_name: 'Diarra',
    role: 'USER',
    role_code: 'BACKOFFICE',
    role_label: 'Gestionnaire BackOffice & Émissions',
    avatar: 'MD',
    is_active: true,
  },
  {
    id: 7,
    username: 'conformite',
    email: 'audit@lephare-ci.com',
    first_name: 'Me. Suzanne',
    last_name: 'Ekra',
    role: 'ADMIN',
    role_code: 'CONFORMITE',
    role_label: 'Conformité CIMA & Contrôle Interne',
    avatar: 'SE',
    is_active: true,
  },
  {
    id: 8,
    username: 'apporteur',
    email: 'toure.apporteur@partenaire-lephare.ci',
    first_name: 'Amadou',
    last_name: 'Touré',
    role: 'USER',
    role_code: 'APPORTEUR',
    role_label: 'Réseau Apporteur d\'Affaires Partenaire',
    avatar: 'AT',
    is_active: true,
  },
];

export const mockClients = [
  {
    id: 1,
    IdClient: 1,
    codeclient: 'CLI-2024-001',
    Matricule: 'CLI-2024-001',
    numero_assure: 'ASS-202401-0001',
    cle_unique: 'CLI-CI-001-KOUAME',
    nom: 'KOUAME',
    Nom: 'KOUAME',
    prenom: 'Yao Patrick',
    Prenoms: 'Yao Patrick',
    nomcomplet: 'KOUAME Yao Patrick',
    typeclient: 'Particulier',
    Particulier: 'V',
    IdQualite: 1,
    civilite: 'Monsieur',
    DateNaissance: '1985-06-14',
    LieuNaissance: 'Abidjan Cocody',
    CniPat: 'CI00293849102',
    telephone: '+225 27 22 40 10 11',
    Telephone: '+225 27 22 40 10 11',
    mobile: '+225 07 08 09 10 11',
    Mobile: '+225 07 08 09 10 11',
    fixe: '+225 27 22 40 10 11',
    Fixe: '+225 27 22 40 10 11',
    fax: '',
    Fax: '',
    email: 'yao.kouame@gmail.com',
    Email: 'yao.kouame@gmail.com',
    adresse: 'Cocody Riviera 3, Rue Sainte Famille',
    Adresse1: 'Cocody Riviera 3, Rue Sainte Famille',
    Adresse2: 'Villa 142, Résidence Les Palmiers',
    IdVille: 1,
    ville: 'Abidjan',
    CodePostal: '01 BP 4512 Abidjan 01',
    IdProfession: 9,
    profession: 'Ingénieur Télécoms',
    libelleprofession: 'Ingénieur Télécoms',
    IdSecteurActivite: 8,
    secteur_activite: 'Technologies & Télécoms',
    Responsable: '',
    Fonction: 'Chef de Projet Réseaux',
    Vip: 'V',
    is_vip: true,
    Statut: 'V',
    statut_libelle: 'Actif',
    idtypeclient: 1,
    idtypeclient_id: 1,
    type_souscripteur: 'Personne Physique',
    idtypeassure: 1,
    idtypeassure_id: 1,
    type_assure: 'Personne Physique',
    IdCategorie: 1,
    IdProfil: 1,
    Reconquete: 'N',
    CreeCie: 'V',
    Rib: 'CI092 01001 002348571029 45',
    NumeroCompte: 'CPT-411-0001',
    Solde: '0',
    Avoir: '0',
    ExonereDeTaxes: false,
    ExonereDeAccess: false,
    contrats_actifs: 3,
    devis_en_cours: 1,
    total_primes: '1 450 000 FCFA',
  },
  {
    id: 2,
    IdClient: 2,
    codeclient: 'CLI-2024-002',
    Matricule: 'CLI-2024-002',
    numero_assure: 'ASS-202401-0002',
    cle_unique: 'CLI-CI-002-SIL',
    nom: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE (SIL)',
    Nom: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE (SIL)',
    prenom: '',
    Prenoms: '',
    nomcomplet: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE (SIL)',
    typeclient: 'Entreprise',
    Particulier: 'F',
    IdQualite: 4,
    civilite: 'Société',
    DateNaissance: null,
    LieuNaissance: '',
    CniPat: 'CI-ABJ-2018-B-14529',
    telephone: '+225 27 21 22 23 24',
    Telephone: '+225 27 21 22 23 24',
    mobile: '+225 05 06 07 08 09',
    Mobile: '+225 05 06 07 08 09',
    fixe: '+225 27 21 22 23 24',
    Fixe: '+225 27 21 22 23 24',
    fax: '+225 27 21 22 23 25',
    Fax: '+225 27 21 22 23 25',
    email: 'contact@sil-ci.com',
    Email: 'contact@sil-ci.com',
    adresse: 'Zone Industrielle de Vridi, Boulevard du Port',
    Adresse1: 'Zone Industrielle de Vridi, Boulevard du Port',
    Adresse2: 'Quai N°4, Entrepôt Principal',
    IdVille: 1,
    ville: 'Abidjan',
    CodePostal: '15 BP 890 Abidjan 15',
    IdProfession: 10,
    profession: 'Transport & Logistique',
    libelleprofession: 'Transport & Logistique',
    IdSecteurActivite: 2,
    secteur_activite: 'Transport & Logistique',
    Responsable: 'M. KOFFI N\'Dri Emmanuel',
    Fonction: 'Directeur Général',
    Vip: 'V',
    is_vip: true,
    Statut: 'V',
    statut_libelle: 'Actif',
    idtypeclient: 2,
    idtypeclient_id: 2,
    type_souscripteur: 'Personne Morale',
    idtypeassure: 2,
    idtypeassure_id: 2,
    type_assure: 'Personne Morale',
    IdCategorie: 2,
    IdProfil: 2,
    Reconquete: 'N',
    CreeCie: 'V',
    Rib: 'CI034 01002 018472948190 28',
    NumeroCompte: 'CPT-411-0002',
    Solde: '28650000',
    Avoir: '0',
    ExonereDeTaxes: false,
    ExonereDeAccess: false,
    contrats_actifs: 14,
    devis_en_cours: 2,
    total_primes: '28 650 000 FCFA',
  },
  {
    id: 3,
    IdClient: 3,
    codeclient: 'CLI-2024-003',
    Matricule: 'CLI-2024-003',
    numero_assure: 'ASS-202402-0003',
    cle_unique: 'CLI-CI-003-BAKAYOKO',
    nom: 'BAKAYOKO',
    Nom: 'BAKAYOKO',
    prenom: 'Fatoumata',
    Prenoms: 'Fatoumata',
    nomcomplet: 'BAKAYOKO Fatoumata',
    typeclient: 'Particulier',
    Particulier: 'V',
    IdQualite: 2,
    civilite: 'Madame',
    DateNaissance: '1990-11-22',
    LieuNaissance: 'Bouaké',
    CniPat: 'CI00481928401',
    telephone: '+225 27 21 35 44 55',
    Telephone: '+225 27 21 35 44 55',
    mobile: '+225 05 44 55 66 77',
    Mobile: '+225 05 44 55 66 77',
    fixe: '',
    Fixe: '',
    fax: '',
    Fax: '',
    email: 'f.bakayoko@yahoo.fr',
    Email: 'f.bakayoko@yahoo.fr',
    adresse: 'Marcory Résidentiel, Rue des Majorettes',
    Adresse1: 'Marcory Résidentiel, Rue des Majorettes',
    Adresse2: 'Immeuble Orchidée, Appt B2',
    IdVille: 1,
    ville: 'Abidjan',
    CodePostal: '26 BP 112 Abidjan 26',
    IdProfession: 8,
    profession: 'Médecin Généraliste',
    libelleprofession: 'Médecin Généraliste',
    IdSecteurActivite: 5,
    secteur_activite: 'Services & Santé',
    Responsable: '',
    Fonction: 'Médecin Chef',
    Vip: 'N',
    is_vip: false,
    Statut: 'V',
    statut_libelle: 'Actif',
    idtypeclient: 1,
    idtypeclient_id: 1,
    type_souscripteur: 'Personne Physique',
    idtypeassure: 1,
    idtypeassure_id: 1,
    type_assure: 'Personne Physique',
    IdCategorie: 1,
    IdProfil: 1,
    Reconquete: 'N',
    CreeCie: 'V',
    Rib: 'CI059 01004 009283748291 19',
    NumeroCompte: 'CPT-411-0003',
    Solde: '0',
    Avoir: '0',
    ExonereDeTaxes: false,
    ExonereDeAccess: false,
    contrats_actifs: 2,
    devis_en_cours: 0,
    total_primes: '890 000 FCFA',
  },
  {
    id: 4,
    IdClient: 4,
    codeclient: 'CLI-2024-004',
    Matricule: 'CLI-2024-004',
    numero_assure: 'ASS-202402-0004',
    cle_unique: 'CLI-CI-004-BTP',
    nom: 'BTP AFRIQUE HOLDING',
    Nom: 'BTP AFRIQUE HOLDING',
    prenom: '',
    Prenoms: '',
    nomcomplet: 'BTP AFRIQUE HOLDING',
    typeclient: 'Entreprise',
    Particulier: 'F',
    IdQualite: 4,
    civilite: 'Société',
    DateNaissance: null,
    LieuNaissance: '',
    CniPat: 'CI-ABJ-2015-B-9874',
    telephone: '+225 25 30 31 32 33',
    Telephone: '+225 25 30 31 32 33',
    mobile: '+225 07 40 50 60 70',
    Mobile: '+225 07 40 50 60 70',
    fixe: '+225 25 30 31 32 33',
    Fixe: '+225 25 30 31 32 33',
    fax: '+225 25 30 31 32 34',
    Fax: '+225 25 30 31 32 34',
    email: 'secretariat@btp-afrique.com',
    Email: 'secretariat@btp-afrique.com',
    adresse: 'Plateau Immeuble Trade Center',
    Adresse1: 'Plateau Immeuble Trade Center',
    Adresse2: '8ème étage, Aile Nord',
    IdVille: 1,
    ville: 'Abidjan',
    CodePostal: '01 BP 2901 Abidjan 01',
    IdProfession: 10,
    profession: 'Bâtiment & Travaux Publics',
    libelleprofession: 'Bâtiment & Travaux Publics',
    IdSecteurActivite: 3,
    secteur_activite: 'Bâtiment & Travaux Publics (BTP)',
    Responsable: 'Mme DIOMANDÉ Fanta',
    Fonction: 'Présidente Directrice Générale',
    Vip: 'V',
    is_vip: true,
    Statut: 'V',
    statut_libelle: 'Actif',
    idtypeclient: 2,
    idtypeclient_id: 2,
    type_souscripteur: 'Personne Morale',
    idtypeassure: 2,
    idtypeassure_id: 2,
    type_assure: 'Personne Morale',
    IdCategorie: 2,
    IdProfil: 3,
    Reconquete: 'N',
    CreeCie: 'V',
    Rib: 'CI012 01005 092837461928 32',
    NumeroCompte: 'CPT-411-0004',
    Solde: '42100000',
    Avoir: '0',
    ExonereDeTaxes: false,
    ExonereDeAccess: false,
    contrats_actifs: 8,
    devis_en_cours: 3,
    total_primes: '42 100 000 FCFA',
  },
];

export const mockQuotes = [
  {
    id: 101,
    numerodevis: 'DEV-AUTO-2024-089',
    produit: 'Automobile Particulier',
    branche: 'Auto',
    client_nom: 'KOUAME Yao Patrick',
    compagnie: 'NSIA Assurances',
    prime_nette: 385000,
    accessoires: 15000,
    taxes: 52000,
    prime_totale: 452000,
    date_emission: '2024-10-14',
    statut: 'Validé',
    statut_badge: 'emerald',
  },
  {
    id: 102,
    numerodevis: 'DEV-FLOTTE-2024-012',
    produit: 'Flotte Automobile (12 Véhicules)',
    branche: 'Auto Flotte',
    client_nom: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE',
    compagnie: 'SUNU Assurances',
    prime_nette: 5800000,
    accessoires: 50000,
    taxes: 819000,
    prime_totale: 6669000,
    date_emission: '2024-10-12',
    statut: 'En cours',
    statut_badge: 'amber',
  },
  {
    id: 103,
    numerodevis: 'DEV-MRH-2024-045',
    produit: 'Multi-Risques Habitation Villa',
    branche: 'MRH',
    client_nom: 'BAKAYOKO Fatoumata',
    compagnie: 'SANLAM Assurances',
    prime_nette: 210000,
    accessoires: 10000,
    taxes: 28600,
    prime_totale: 248600,
    date_emission: '2024-10-10',
    statut: 'Consolidé',
    statut_badge: 'blue',
  },
  {
    id: 104,
    numerodevis: 'DEV-SANTE-2024-007',
    produit: 'Santé Entreprise Groupe',
    branche: 'Santé',
    client_nom: 'BTP AFRIQUE HOLDING',
    compagnie: 'ALLIANZ CI',
    prime_nette: 14500000,
    accessoires: 75000,
    taxes: 0,
    prime_totale: 14575000,
    date_emission: '2024-10-08',
    statut: 'En attente dérogation',
    statut_badge: 'rose',
  },
];

export const mockContracts = [
  {
    id: 42,
    numeropolice: '2001320230038V',
    client_nom: 'BALLO ZOUMANAN',
    produit: 'Multirisques Habitation (MRH)',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-07-16',
    date_expiration: '2024-07-15',
    prime_totale: 3125,
    montant_encaisse: 3125,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 34,
    numeropolice: '2001124230032H',
    client_nom: 'KALAPO EPSE MAMBO ADAM',
    produit: 'Assurance Santé Groupe',
    compagnie: 'SUNU ASSURANCES',
    date_effet: '2023-08-02',
    date_expiration: '2024-08-01',
    prime_totale: 790560,
    montant_encaisse: 790560,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 30,
    numeropolice: '2001202230028Y',
    client_nom: 'DRO OUATTARA',
    produit: 'Automobile Tous Risques',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-07-08',
    date_expiration: '2024-07-07',
    prime_totale: 481349,
    montant_encaisse: 481349,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 28,
    numeropolice: '2001201230026V',
    client_nom: 'DRO OUATTARA',
    produit: 'Automobile Tiers & Vol',
    compagnie: 'SUNU ASSURANCES',
    date_effet: '2023-08-01',
    date_expiration: '2024-01-31',
    prime_totale: 748371,
    montant_encaisse: 748371,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 27,
    numeropolice: '2001201230025T',
    client_nom: 'HAMZA EPSE BAMBA TAHAR FATOUMATA',
    produit: 'Automobile Premium',
    compagnie: 'SUNU ASSURANCES',
    date_effet: '2023-08-01',
    date_expiration: '2024-07-31',
    prime_totale: 1372733,
    montant_encaisse: 1372733,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 21,
    numeropolice: '2001124230020R',
    client_nom: 'ASSALE LOUISE',
    produit: 'Assurance Santé Cadres',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-07-22',
    date_expiration: '2024-07-21',
    prime_totale: 2431080,
    montant_encaisse: 2431080,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 12,
    numeropolice: '2001201230011P',
    client_nom: 'ASSY PATRICK',
    produit: 'Automobile RC & Défense Recours',
    compagnie: 'AMSA ASSURANCES',
    date_effet: '2023-06-23',
    date_expiration: '2024-06-22',
    prime_totale: 401038,
    montant_encaisse: 401038,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 6,
    numeropolice: '2001203230005A',
    client_nom: 'KOFFI KOFFI MARTIAL',
    produit: 'Automobile Flotte VP',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-05-31',
    date_expiration: '2024-05-30',
    prime_totale: 1695882,
    montant_encaisse: 1695882,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 4,
    numeropolice: '2001119230003W',
    client_nom: 'MONKEY D',
    produit: 'Individuelle Accident (IA)',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-05-23',
    date_expiration: '2024-05-22',
    prime_totale: 212970,
    montant_encaisse: 212970,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
  {
    id: 1,
    numeropolice: '2001201230000B',
    client_nom: 'DJOMAN KOFFI',
    produit: 'Automobile Grande Flotte Entreprise',
    compagnie: 'NSIA ASSURANCES',
    date_effet: '2023-05-23',
    date_expiration: '2024-05-22',
    prime_totale: 8023712,
    montant_encaisse: 8023712,
    statut_encaissement: 'Soldé',
    statut: 'En cours',
    statut_badge: 'emerald',
  },
];

export const mockAsaciCertificates = [
  {
    id: 1,
    police: 'POL-AUTO-2024-00128',
    immatriculation: '4589 KL 01',
    assure: 'KOUAME Yao Patrick',
    genre: 'Tourisme (VP)',
    numero_attestation: 'CRT-ASACI-2024-994821',
    code_securite: 'A8B9-9941',
    date_emission: '2024-01-15',
    date_expiration: '2025-01-14',
    statut_asaci: 'Validée & Générée',
    statut_badge: 'emerald',
  },
  {
    id: 2,
    police: 'POL-FLOT-2024-00045',
    immatriculation: '1234 HJ 01',
    assure: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE',
    genre: 'Camion Tracteur (PL)',
    numero_attestation: 'CRT-ASACI-2024-994822',
    code_securite: 'C3X1-4420',
    date_emission: '2024-03-01',
    date_expiration: '2025-02-28',
    statut_asaci: 'Validée & Générée',
    statut_badge: 'emerald',
  },
  {
    id: 3,
    police: 'POL-AUTO-2024-00199',
    immatriculation: '7741 MN 01',
    assure: 'KOFFI Emmanuel',
    genre: 'Tourisme (VP)',
    numero_attestation: 'En attente serveur ASACI',
    code_securite: '-',
    date_emission: '2024-10-14',
    date_expiration: '2025-10-13',
    statut_asaci: 'En cours de traitement',
    statut_badge: 'amber',
  },
];

export const mockDerogations = [
  {
    id: 1,
    type_operation: 'ANNUL_ENC',
    type_label: "Annulation d'encaissement",
    objet: 'Erreur montant chèque quittance Q-2024-991',
    demandeur_nom: 'Jean-Marc Kouame',
    date_demande: '2024-10-14 09:30',
    approbateur_nom: 'Franck Gnogouri (Direction)',
    statut: 'PENDING',
    statut_label: 'En attente',
    statut_badge: 'amber',
    code_jeton: null,
  },
  {
    id: 2,
    type_operation: 'REMISE_FLOTTE',
    type_label: 'Remise commerciale exceptionnelle (15%)',
    objet: 'Devis Flotte BTP AFRIQUE HOLDING',
    demandeur_nom: 'Awa Kone',
    date_demande: '2024-10-12 14:15',
    approbateur_nom: 'Franck Gnogouri',
    statut: 'APPROVED',
    statut_label: 'Approuvée',
    statut_badge: 'emerald',
    code_jeton: 'FLT-8892-OK',
  },
  {
    id: 3,
    type_operation: 'AVENANT_RETROACTIF',
    type_label: "Modification date d'effet rétroactive",
    objet: 'Demande client pour dossier leasing banque',
    demandeur_nom: 'Awa Kone',
    date_demande: '2024-10-09 11:00',
    approbateur_nom: 'Franck Gnogouri',
    statut: 'REJECTED',
    statut_label: 'Rejetée',
    statut_badge: 'rose',
    code_jeton: null,
  },
];

export const mockCommissions = {
  kpis: {
    total_commissions_dues: '18 450 000 FCFA',
    total_paye: '12 800 000 FCFA',
    reste_a_payer: '5 650 000 FCFA',
    nombre_apporteurs_actifs: 24,
  },
  affaires: [
    {
      id: 1,
      apporteur: 'Cabinet Courtage Ivoire Assur',
      contrat: 'POL-FLOT-2024-00045',
      client: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE',
      prime_nette: 12400000,
      taux_commission: '12%',
      montant_commission: 1488000,
      statut: 'Payé',
      statut_badge: 'emerald',
    },
    {
      id: 2,
      apporteur: 'M. Touré Amadou (Agent Général)',
      contrat: 'POL-AUTO-2024-00128',
      client: 'KOUAME Yao Patrick',
      prime_nette: 385000,
      taux_commission: '10%',
      montant_commission: 38500,
      statut: 'En attente',
      statut_badge: 'amber',
    },
    {
      id: 3,
      apporteur: 'Global Finance & Insurance',
      contrat: 'POL-MRH-2024-00092',
      client: 'BAKAYOKO Fatoumata',
      prime_nette: 210000,
      taux_commission: '15%',
      montant_commission: 31500,
      statut: 'Payé',
      statut_badge: 'emerald',
    },
  ],
};

export const mockAdminStats = {
  kpis: {
    chiffre_affaires_global: '345 800 000 FCFA',
    taux_recouvrement: '89.4%',
    contrats_actifs: 1480,
    sinistres_en_cours: 42,
    devis_convertis_taux: '68%',
    reversements_a_valider: '24 500 000 FCFA',
  },
  cima_e1: [
    { code_branche: '01', branche: 'Automobile & Responsabilité Civile', emissions: 185400000, encaissements: 168200000, commissions: 22400000 },
    { code_branche: '02', branche: 'Incendie, Accidents & Risques Divers (IARD)', emissions: 64200000, encaissements: 58900000, commissions: 8900000 },
    { code_branche: '03', branche: 'Santé, Maladie & Accidents Corporels', emissions: 72100000, encaissements: 62000000, commissions: 7800000 },
    { code_branche: '04', branche: 'Transport & Facultés Maritimes / Aériennes', emissions: 24100000, encaissements: 21500000, commissions: 3200000 },
  ],
  cima_e2: [
    { code_branche: '01', branche: 'Automobile & RC', arrieres_debut: 24500000, encaissements_arrieres: 18200000, annulations: 1500000, arrieres_fin: 4800000 },
    { code_branche: '02', branche: 'IARD Risques Divers', arrieres_debut: 8900000, encaissements_arrieres: 6500000, annulations: 400000, arrieres_fin: 2000000 },
    { code_branche: '03', branche: 'Santé Groupe', arrieres_debut: 12000000, encaissements_arrieres: 11200000, annulations: 0, arrieres_fin: 800000 },
    { code_branche: '04', branche: 'Transport & Facultés', arrieres_debut: 3500000, encaissements_arrieres: 3100000, annulations: 100000, arrieres_fin: 300000 },
  ],
};

// ============================================================================
// MODULE I : MOTEUR DES CONVENTIONS ASSUREURS PARTENAIRES (CdC Section 1 & 13)
// ============================================================================
export const mockConventions = [
  {
    id: 1,
    code: 'CONV-ALLIANZ-2024',
    compagnie: 'Allianz Côte d\'Ivoire Assurances',
    sigle: 'ALLIANZ',
    statut: 'Actif',
    date_effet: '01/01/2024',
    date_echeance: '31/12/2026',
    delai_reversement_jours: 30, // Règle CIMA
    mandat_encaissement: true,
    seuil_delegation_sinistre: 5000000, // 5 000 000 FCFA
    taux_participation_beneficiaire: '15%',
    commissions: {
      auto: '12%',
      mrh: '18%',
      sante: '10%',
      transport: '10%',
    },
    contact_referent: 'M. Kouassi Jean (Directeur Réseau Courtage)',
    telephone: '+225 27 20 25 15 00',
    email: 'courtage.ci@allianz.com',
  },
  {
    id: 2,
    code: 'CONV-NSIA-2023',
    compagnie: 'NSIA Assurances Côte d\'Ivoire',
    sigle: 'NSIA',
    statut: 'Actif',
    date_effet: '01/03/2023',
    date_echeance: '28/02/2027',
    delai_reversement_jours: 30,
    mandat_encaissement: true,
    seuil_delegation_sinistre: 6000000, // 6 000 000 FCFA
    taux_participation_beneficiaire: '20%',
    commissions: {
      auto: '13%',
      mrh: '20%',
      sante: '12%',
      transport: '11%',
    },
    contact_referent: 'Mme Bamba Aïcha (Directrice Technique Partenaires)',
    telephone: '+225 27 20 31 98 00',
    email: 'partenariats.ci@groupensia.com',
  },
  {
    id: 3,
    code: 'CONV-AMSA-2024',
    compagnie: 'AMSA Assurances Côte d\'Ivoire',
    sigle: 'AMSA',
    statut: 'Actif',
    date_effet: '15/01/2024',
    date_echeance: '31/12/2025',
    delai_reversement_jours: 30,
    mandat_encaissement: true,
    seuil_delegation_sinistre: 3500000,
    taux_participation_beneficiaire: '10%',
    commissions: {
      auto: '11%',
      mrh: '15%',
      sante: '9%',
      transport: '8%',
    },
    contact_referent: 'M. Diabaté Lamine (Chef Département Courtage)',
    telephone: '+225 27 20 20 88 88',
    email: 'courtage@amsaassurances.ci',
  },
  {
    id: 4,
    code: 'CONV-SUNU-2024',
    compagnie: 'SUNU Assurances IARD CI',
    sigle: 'SUNU',
    statut: 'Actif',
    date_effet: '01/02/2024',
    date_echeance: '31/12/2026',
    delai_reversement_jours: 30,
    mandat_encaissement: true,
    seuil_delegation_sinistre: 4000000,
    taux_participation_beneficiaire: '12%',
    commissions: {
      auto: '12%',
      mrh: '17%',
      sante: '10%',
      transport: '9%',
    },
    contact_referent: 'M. N\'Dri Christian (Responsable Souscription Réseau)',
    telephone: '+225 27 20 31 12 12',
    email: 'cotedivoire.assurances@sunu-group.com',
  },
  {
    id: 5,
    code: 'CONV-C3MED-2024',
    compagnie: 'C3MEDICAL France & International',
    sigle: 'C3MEDICAL',
    statut: 'Actif',
    date_effet: '01/06/2024',
    date_echeance: '31/12/2027',
    delai_reversement_jours: 45,
    mandat_encaissement: false,
    seuil_delegation_sinistre: 15000000,
    taux_participation_beneficiaire: '8%',
    commissions: {
      sante: '8%',
      evacuation: '12%',
    },
    contact_referent: 'Dr. Jerome Faure (Directeur Partenariats Afrique)',
    telephone: '+33 1 84 25 60 00',
    email: 'partenaires@c3medical.com',
  },
];

// ============================================================================
// MODULE H : GESTION DÉLÉGUÉE DES SINISTRES (CdC Section 5 & 7)
// ============================================================================
export const mockClaims = [
  {
    id: 1,
    numero_sinistre: 'SIN-2026-00124',
    police_ref: 'POL-AUTO-2024-00128',
    client_nom: 'KOUAME Yao Patrick',
    branche: 'Automobile',
    compagnie: 'NSIA Assurances',
    convention_ref: 'CONV-NSIA-2023',
    date_survenance: '02/09/2026',
    date_declaration: '03/09/2026',
    lieu: 'Carrefour Duncan, Cocody, Abidjan',
    circonstances: 'Collision arrière par un tiers non identifié à l\'arrêt au feu rouge.',
    garantie_mobilisee: 'Dommages Collision & Défense Recours',
    evaluation_initiale: 1450000,
    franchise: 50000,
    plafond_delegation: 6000000,
    statut: 'En cours d\'expertise',
    statut_badge: 'amber',
    expert: 'Cabinet CECI Experts Auto',
    pieces_requises: [
      { id: 1, label: 'Déclaration formelle signée', recu: true },
      { id: 2, label: 'Copie Permis de conduire & Carte grise', recu: true },
      { id: 3, label: 'Constat amiable d\'accident', recu: true },
      { id: 4, label: 'Devis estimatif de réparation agréé', recu: true },
      { id: 5, label: 'Rapport d\'expertise chiffré', recu: false },
    ],
    indemnite_reglee: 0,
    recours_engage: false,
    gestionnaire: 'Dr. Marcelle Yao',
  },
  {
    id: 2,
    numero_sinistre: 'SIN-2026-00119',
    police_ref: 'POL-MRH-2024-00092',
    client_nom: 'BAKAYOKO Fatoumata',
    branche: 'Habitation (MRH)',
    compagnie: 'Allianz Côte d\'Ivoire Assurances',
    convention_ref: 'CONV-ALLIANZ-2024',
    date_survenance: '28/08/2026',
    date_declaration: '29/08/2026',
    lieu: 'Villa 142, Zone 4C, Marcory, Abidjan',
    circonstances: 'Rupture de canalisation d\'eau dans la salle de bain ayant endommagé le parquet et les meubles.',
    garantie_mobilisee: 'Dégâts des Eaux & Biens Immobiliers',
    evaluation_initiale: 850000,
    franchise: 30000,
    plafond_delegation: 5000000,
    statut: 'Prise en charge validée',
    statut_badge: 'emerald',
    expert: 'Cabinet Ivoirien d\'Expertise Immobilière',
    pieces_requises: [
      { id: 1, label: 'Déclaration détaillée des dommages', recu: true },
      { id: 2, label: 'Factures d\'achat des biens endommagés', recu: true },
      { id: 3, label: 'Rapport de recherche de fuite', recu: true },
      { id: 4, label: 'Rapport d\'expertise contradictoire', recu: true },
    ],
    indemnite_reglee: 820000,
    recours_engage: false,
    gestionnaire: 'Dr. Marcelle Yao',
  },
  {
    id: 3,
    numero_sinistre: 'SIN-2026-00105',
    police_ref: 'POL-FLOT-2024-00045',
    client_nom: 'SOCIÉTÉ IVOIRIENNE DE LOGISTIQUE',
    branche: 'Automobile Flotte',
    compagnie: 'AMSA Assurances',
    convention_ref: 'CONV-AMSA-2024',
    date_survenance: '15/08/2026',
    date_declaration: '16/08/2026',
    lieu: 'Autoroute du Nord PK 45',
    circonstances: 'Projection de gravillons ayant fissuré le pare-brise du camion porteur.',
    garantie_mobilisee: 'Bris de Glaces Flotte',
    evaluation_initiale: 320000,
    franchise: 0,
    plafond_delegation: 3500000,
    statut: 'Clôturé & Réglé',
    statut_badge: 'blue',
    expert: 'Centre France Pare-Brise Abidjan',
    pieces_requises: [
      { id: 1, label: 'Ordre de réparation immédiat', recu: true },
      { id: 2, label: 'Facture acquittée pose pare-brise', recu: true },
      { id: 3, label: 'Bon de livraison matériel', recu: true },
    ],
    indemnite_reglee: 320000,
    recours_engage: false,
    gestionnaire: 'Mamadou Diarra',
  },
  {
    id: 4,
    numero_sinistre: 'SIN-2026-00098',
    police_ref: 'POL-SANTE-2024-00033',
    client_nom: 'ENTREPRISE AGRO-INDUSTRIELLE DU SUD',
    branche: 'Santé Groupe',
    compagnie: 'SUNU Assurances',
    convention_ref: 'CONV-SUNU-2024',
    date_survenance: '05/08/2026',
    date_declaration: '06/08/2026',
    lieu: 'CHU de Treichville',
    circonstances: 'Accident de travail avec intervention chirurgicale orthopédique d\'urgence pour un collaborateur.',
    garantie_mobilisee: 'Hospitalisation & Chirurgie Lourde',
    evaluation_initiale: 2100000,
    franchise: 0,
    plafond_delegation: 4000000,
    statut: 'Recours engagé',
    statut_badge: 'purple',
    expert: 'Médecin Conseil LE PHARE',
    pieces_requises: [
      { id: 1, label: 'Certificat médical initial', recu: true },
      { id: 2, label: 'Feuille de soins & factures cliniques', recu: true },
      { id: 3, label: 'Rapport médical sous pli confidentiel', recu: true },
    ],
    indemnite_reglee: 2100000,
    recours_engage: true,
    montant_recours: 1800000,
    gestionnaire: 'Dr. Marcelle Yao',
  },
];

// ============================================================================
// MODULE C : CRM & PIPELINE COMMERCIAL LEADS (CdC Section 5 & 7)
// ============================================================================
export const mockLeads = [
  {
    id: 1,
    nom_prospect: 'IVOIRE BTP & TRAVAUX PUBLICS',
    type: 'Entreprise',
    contact_principal: 'M. Soro Amadou (Directeur Général)',
    telephone: '+225 07 48 90 12 34',
    email: 'a.soro@ivoirebtp.ci',
    secteur: 'Génie Civil & Construction',
    produit_cible: 'Flotte Automobile (32 engins) + TRC',
    compagnie_envisagee: 'Allianz CI',
    prime_estimee: 18500000,
    etape: 'Proposition émise',
    probabilite: 75,
    date_creation: '20/08/2026',
    prochaine_relance: '08/09/2026',
    commercial_assigne: 'Awa Kone',
    notes: 'Devis remis en mains propres. Attente de confirmation du conseil d\'administration.',
  },
  {
    id: 2,
    nom_prospect: 'CLINIQUE MÉDICALE SAINTE-MARIE',
    type: 'Entreprise',
    contact_principal: 'Dr. Koffi Paul (Directeur Médical)',
    telephone: '+225 05 06 12 34 56',
    email: 'direction@clinique-saintemarie.ci',
    secteur: 'Santé & Soins',
    produit_cible: 'Santé Groupe (85 agents) & Responsabilité Professionnelle',
    compagnie_envisagee: 'NSIA Assurances',
    prime_estimee: 32000000,
    etape: 'Négociation',
    probabilite: 90,
    date_creation: '12/08/2026',
    prochaine_relance: '07/09/2026',
    commercial_assigne: 'Awa Kone',
    notes: 'Ajustement des taux de couverture optique et dentaire demandé par les délégués du personnel.',
  },
  {
    id: 3,
    nom_prospect: 'PHARMACIE DES LAGUNES',
    type: 'Professionnel',
    contact_principal: 'Mme Touré Kady (Pharmacienne Titulaire)',
    telephone: '+225 01 02 03 04 05',
    email: 'contact@pharmaciedeslagunes.ci',
    secteur: 'Commerce & Santé',
    produit_cible: 'Multirisque Professionnelle + Perte d\'Exploitation',
    compagnie_envisagee: 'AMSA Assurances',
    prime_estimee: 2400000,
    etape: 'Qualifié',
    probabilite: 50,
    date_creation: '28/08/2026',
    prochaine_relance: '11/09/2026',
    commercial_assigne: 'Jean-Marc Kouame',
    notes: 'Visite des locaux effectuée. Inventaire du stock en cours de chiffrage.',
  },
  {
    id: 4,
    nom_prospect: 'TRANSPORTS EXPRESS ABIDJAN (TEA)',
    type: 'Entreprise',
    contact_principal: 'M. Ouattara Bakary (Responsable Parc)',
    telephone: '+225 07 11 22 33 44',
    email: 'b.ouattara@tea-transports.ci',
    secteur: 'Transport & Messagerie',
    produit_cible: 'RC Transport & Marchandises Transportées',
    compagnie_envisagee: 'SUNU Assurances',
    prime_estimee: 9800000,
    etape: 'Contacté',
    probabilite: 30,
    date_creation: '01/09/2026',
    prochaine_relance: '09/09/2026',
    commercial_assigne: 'Awa Kone',
    notes: 'Premier rendez-vous exploratoire réalisé en visioconférence.',
  },
  {
    id: 5,
    nom_prospect: 'M. N\'Dri Fabrice',
    type: 'Particulier VIP',
    contact_principal: 'M. N\'Dri Fabrice',
    telephone: '+225 07 99 88 77 66',
    email: 'f.ndri@cabinet-ndri.ci',
    secteur: 'Professions Libérales (Avocat)',
    produit_cible: 'Tous Risques Porsche Cayenne Turbo + MRH Standing',
    compagnie_envisagee: 'Allianz CI',
    prime_estimee: 1850000,
    etape: 'Gagné',
    probabilite: 100,
    date_creation: '15/08/2026',
    prochaine_relance: 'Affaire conclue',
    commercial_assigne: 'Awa Kone',
    notes: 'Affaire transformée en contrat POL-AUTO-2024-00142.',
  },
];

// ============================================================================
// MODULE K : CONFORMITÉ RÉGLEMENTAIRE CIMA & AUDIT TRAIL (CdC Section 5.1 & 7)
// ============================================================================
export const mockCompliance = {
  agrement: {
    numero: 'A-042/CIMA/DGTCP',
    numero_agrement: 'A-042/CIMA/DGTCP',
    arrete_ministeriel: 'Arrêté N° 0142/MEF/DGTCP/DA',
    date_octroi: '15/04/2018',
    date_delivrance: '15/04/2018',
    dernier_audit: '15/01/2026',
    prochaine_revue: '15/01/2027',
    autorite: 'Direction Générale du Trésor & Commission de Contrôle CIMA',
    validite: 'Permanente sous réserve de conformité annuelle',
    statut: 'Conforme & En Règle',
    statut_badge: 'emerald',
    pieces_probantes: ['Arrêté ministériel d\'agrément', 'Extrait RCCM CI-ABJ-2018-B-1142', 'Statuts certifiés'],
  },
  garantie_financiere: {
    organisme: 'Société Générale Côte d\'Ivoire (SGCI)',
    banque: 'Société Générale Côte d\'Ivoire (SGCI)',
    type_caution: 'Caution bancaire solidaire obligatoire CIMA (Livre V)',
    montant: 50000000, // 50 000 000 FCFA
    montant_caution: 50000000,
    date_effet: '01/01/2026',
    date_echeance: '31/12/2026',
    echeance: '31/12/2026',
    jours_restants: 116,
    statut: 'Garantie Active & Conforme',
    statut_badge: 'emerald',
  },
  rccm: 'CI-ABJ-03-2018-B14-04982',
  compte_sequestre: 'SGCI CI008 01112 012345678901 45',
  audit_logs: [
    {
      id: 1,
      horodatage: '05/09/2026 17:42:15',
      utilisateur: 'Franck Gnogouri (admin)',
      role: 'DIR_GEN',
      action: 'APPROBATION_DEROGATION',
      objet: 'Police Automobile POL-AUTO-2024-00128',
      details: 'Octroi d\'une réduction commerciale de 12% sur garantie Vol/Incendie.',
      ip: '192.168.1.11',
      statut: 'SUCCÈS',
    },
    {
      id: 2,
      horodatage: '05/09/2026 15:20:04',
      utilisateur: 'Dr. Marcelle Yao (dir_sinistres)',
      role: 'DIR_SINISTRES',
      action: 'VALIDATION_PRISE_EN_CHARGE_SINISTRE',
      objet: 'Sinistre Délégué SIN-2026-00119 (Allianz CI)',
      details: 'Validation de l\'indemnisation dégât des eaux pour 820 000 FCFA sous mandat délégué LE PHARE.',
      ip: '192.168.1.14',
      statut: 'SUCCÈS',
    },
    {
      id: 3,
      horodatage: '04/09/2026 11:35:48',
      utilisateur: 'Jean-Marc Kouame (comptable)',
      role: 'FINANCE',
      action: 'ENCAISSEMENT_PRIME',
      objet: 'Quittance QTT-2024-00892',
      details: 'Enregistrement chèque N° 7845120 Société Générale de 1 250 000 FCFA.',
      ip: '192.168.1.18',
      statut: 'SUCCÈS',
    },
    {
      id: 4,
      horodatage: '03/09/2026 09:12:30',
      utilisateur: 'Valérie Brou (dir_technique)',
      role: 'DIR_TECH',
      action: 'CREATION_CONTRAT_DEFINITIF',
      objet: 'Police Habitation POL-MRH-2024-00092',
      details: 'Consolidation du devis en contrat définitif après vérification des pièces justificatives.',
      ip: '192.168.1.22',
      statut: 'SUCCÈS',
    },
    {
      id: 5,
      horodatage: '02/09/2026 16:05:11',
      utilisateur: 'Me. Suzanne Ekra (conformite)',
      role: 'CONFORMITE',
      action: 'AUDIT_COMMISSIONS_CIMA',
      objet: 'Contrôle du délai 30 jours pour règlements assureurs',
      details: 'Génération du rapport d\'audit des commissions en attente NSIA et AMSA.',
      ip: '192.168.1.30',
      statut: 'SUCCÈS',
    },
  ],
};
mockCompliance.journal_audit = mockCompliance.audit_logs;

// ============================================================================
// MODULE J : GED INSTITUTIONNELLE & PIÈCES PROBANTES (CdC Section 5 & 6.8)
// ============================================================================
export const mockDocuments = [
  {
    id: 1,
    titre: 'Contrat Signé & Conditions Particulières - KOUAME Yao',
    categorie: 'Contrats',
    reference: 'POL-AUTO-2024-00128',
    client: 'KOUAME Yao Patrick',
    type_fichier: 'PDF',
    taille: '1.8 Mo',
    date_upload: '01/09/2026',
    statut_conformite: 'Validé & Probant',
    auteur: 'Mamadou Diarra',
  },
  {
    id: 2,
    titre: 'Carte Grise Véhicule 4892 KH 01 - Toyota Prado',
    categorie: 'Pièces d\'Identification',
    reference: 'POL-AUTO-2024-00128',
    client: 'KOUAME Yao Patrick',
    type_fichier: 'PDF',
    taille: '640 Ko',
    date_upload: '01/09/2026',
    statut_conformite: 'Validé & Conforme',
    auteur: 'Awa Kone',
  },
  {
    id: 3,
    titre: 'Rapport d\'Expertise Sinistre Dégât des Eaux',
    categorie: 'Sinistres',
    reference: 'SIN-2026-00119',
    client: 'BAKAYOKO Fatoumata',
    type_fichier: 'PDF',
    taille: '3.2 Mo',
    date_upload: '29/08/2026',
    statut_conformite: 'Signé par Expert Agréé',
    auteur: 'Dr. Marcelle Yao',
  },
  {
    id: 4,
    titre: 'Bordereau de Reversement Quittances Août 2026 - NSIA CI',
    categorie: 'Bordereaux Financiers',
    reference: 'REV-NSIA-2024-08',
    client: 'NSIA Assurances',
    type_fichier: 'XLSX',
    taille: '450 Ko',
    date_upload: '31/08/2026',
    statut_conformite: 'Validé par Finance',
    auteur: 'Jean-Marc Kouame',
  },
  {
    id: 5,
    titre: 'Protocole de Mandat Délégué Sinistres Allianz CI',
    categorie: 'Conventions',
    reference: 'CONV-ALLIANZ-2024',
    client: 'Allianz Côte d\'Ivoire',
    type_fichier: 'PDF',
    taille: '4.5 Mo',
    date_upload: '15/01/2024',
    statut_conformite: 'Convention Cadre Juridique',
    auteur: 'Franck Gnogouri',
  },
];

export const mockCashReceipts = [
  {
    id: 1,
    receipt_number: 'REC-2026-00142',
    police_number: 'POL-AUTO-2024-00128',
    client: 'KOUAME Yao Patrick',
    amount: 320000,
    payment_date: '2026-09-02',
    payment_method: 'Virement Bancaire SGCI',
    statut: 'Encaissé & Réconcilié',
  },
  {
    id: 2,
    receipt_number: 'REC-2026-00139',
    police_number: 'POL-MRH-2024-00085',
    client: 'BAKAYOKO Fatoumata',
    amount: 175000,
    payment_date: '2026-08-25',
    payment_method: 'Chèque NSIA Banque',
    statut: 'Encaissé & Réconcilié',
  },
  {
    id: 3,
    receipt_number: 'REC-2026-00128',
    police_number: 'POL-SANTE-2024-00042',
    client: 'KOUAME Yao Patrick',
    amount: 450000,
    payment_date: '2026-08-10',
    payment_method: 'Virement Ecobank',
    statut: 'Encaissé & Réconcilié',
  },
];

export const mockReceipts = mockCashReceipts;

export const mockCimaE1 = [
  { code_branche: '01', branche: 'Automobile & Responsabilité Civile', emissions: 185400000, encaissements: 168200000, commissions: 22400000 },
  { code_branche: '02', branche: 'Incendie, Accidents & Risques Divers (IARD)', emissions: 64200000, encaissements: 58900000, commissions: 8900000 },
  { code_branche: '03', branche: 'Santé, Maladie & Accidents Corporels', emissions: 72100000, encaissements: 62000000, commissions: 7800000 },
  { code_branche: '04', branche: 'Transport & Facultés Maritimes / Aériennes', emissions: 24100000, encaissements: 21500000, commissions: 3200000 },
];

export const mockCimaE2 = [
  {
    code_branche: '01',
    branche: 'Automobile & RC',
    assureur: 'Allianz Côte d\'Ivoire',
    primes_encaissees: 112000000,
    commissions_brutes: 14500000,
    delai_moyen_reversement: '22 jours',
    statut_cima: 'Conforme (< 30j)',
    arrieres_debut: 24500000,
    encaissements_arrieres: 18200000,
    annulations: 1500000,
    arrieres_fin: 4800000,
  },
  {
    code_branche: '02',
    branche: 'IARD Risques Divers',
    assureur: 'NSIA Assurances CI',
    primes_encaissees: 98500000,
    commissions_brutes: 12800000,
    delai_moyen_reversement: '25 jours',
    statut_cima: 'Conforme (< 30j)',
    arrieres_debut: 8900000,
    encaissements_arrieres: 6500000,
    annulations: 400000,
    arrieres_fin: 2000000,
  },
  {
    code_branche: '03',
    branche: 'Santé Groupe',
    assureur: 'AMSA Assurances CI',
    primes_encaissees: 64200000,
    commissions_brutes: 7700000,
    delai_moyen_reversement: '28 jours',
    statut_cima: 'Conforme (< 30j)',
    arrieres_debut: 12000000,
    encaissements_arrieres: 11200000,
    annulations: 0,
    arrieres_fin: 800000,
  },
  {
    code_branche: '04',
    branche: 'Transport & Facultés',
    assureur: 'SUNU Assurances IARD',
    primes_encaissees: 71100000,
    commissions_brutes: 8500000,
    delai_moyen_reversement: '19 jours',
    statut_cima: 'Conforme (< 30j)',
    arrieres_debut: 3500000,
    encaissements_arrieres: 3100000,
    annulations: 100000,
    arrieres_fin: 300000,
  },
];


