# Generated by Django 4.1.4 on 2023-03-21 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="garantierisque",
            name="ForfaitTaxe",
            field=models.DecimalField(
                db_column="forfaittaxe",
                decimal_places=4,
                max_digits=19,
                null=True,
                verbose_name="Forfait Taxe",
            ),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="IdGarantie",
            field=models.ForeignKey(
                db_column="idgarantie",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="risques",
                related_query_name="risquesavec",
                to="configuration_api.garantie",
            ),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="IdRisque",
            field=models.ForeignKey(
                db_column="idrisque",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garanties",
                related_query_name="garantiesavec",
                to="configuration_api.risque",
            ),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="TauxTaxe",
            field=models.FloatField(db_column="tauxtaxe", verbose_name="Taux Taxe"),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="TauxTaxeGroupe",
            field=models.FloatField(
                db_column="tauxtaxegroupe", verbose_name="Taux Taxe Groupe"
            ),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="ValiditeMax",
            field=models.DateField(db_column="validitemax", verbose_name="Valide au"),
        ),
        migrations.AlterField(
            model_name="garantierisque",
            name="ValiditeMin",
            field=models.DateField(db_column="validitemin", verbose_name="Valide du"),
        ),
        migrations.AlterField(
            model_name="groupeutilisateur",
            name="Active",
            field=models.CharField(
                db_column="active",
                max_length=1,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="groupeutilisateur",
            name="DateCreation",
            field=models.DateTimeField(auto_now_add=True, db_column="datecreation"),
        ),
        migrations.AlterField(
            model_name="groupeutilisateur",
            name="DescriptionGroupe",
            field=models.TextField(
                blank=True, db_column="descriptiongroupe", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="groupeutilisateur",
            name="IdGroupe",
            field=models.AutoField(
                db_column="idgroupe", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="groupeutilisateur",
            name="LibelleGroupe",
            field=models.CharField(db_column="libellegroupe", max_length=60),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="Nom",
            field=models.CharField(db_column="nom", max_length=60),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="NomConnexion",
            field=models.CharField(db_column="nomconnexion", max_length=60),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="Prenoms",
            field=models.CharField(db_column="prenoms", max_length=60),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserASACICode",
            field=models.CharField(
                blank=True, db_column="userasacicode", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserId",
            field=models.AutoField(
                db_column="userid", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserLienPhoto",
            field=models.CharField(
                blank=True, db_column="userlienphoto", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserMail",
            field=models.EmailField(db_column="usermail", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserPassword",
            field=models.CharField(db_column="userpassword", max_length=255),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserSexe",
            field=models.CharField(
                blank=True,
                db_column="usersexe",
                max_length=1,
                null=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="UserTelephone",
            field=models.CharField(
                blank=True, db_column="usertelephone", max_length=20, null=True
            ),
        ),
        migrations.AlterModelTable(
            name="garantierisque",
            table="stdgarantierisque",
        ),
        migrations.AlterModelTable(
            name="groupeutilisateur",
            table="stdgroupeutilisateur",
        ),
        migrations.AlterModelTable(
            name="utilisateur",
            table="stdutilisateur",
        ),
    ]
