# Generated by Django 4.1.4 on 2023-03-24 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0002_alter_garantierisque_forfaittaxe_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessoireCourtierParCompagnie",
            fields=[
                (
                    "IdAccessoireCourtier",
                    models.AutoField(
                        db_column="idaccessoirecourtier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "PrimeMin",
                    models.DecimalField(
                        db_column="primemin", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "PrimeMax",
                    models.DecimalField(
                        db_column="primemax", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "Forfait",
                    models.DecimalField(
                        db_column="forfait", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "Accessoires",
                    models.DecimalField(
                        db_column="accessoires",
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                    ),
                ),
                (
                    "IdCompagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                    ),
                ),
            ],
            options={
                "db_table": "stdaccessoirecourtierparcompagnie",
            },
        ),
    ]
