# Generated by Django 4.1.4 on 2023-03-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0003_accessoirecourtierparcompagnie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sousgarantie",
            name="LibelleSousGarantie",
            field=models.CharField(
                db_column="libellesousgarantie",
                max_length=100,
                verbose_name="Libellé S/Garantie",
            ),
        ),
    ]
