# Generated by Django 4.1.4 on 2023-03-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0004_alter_sousgarantie_libellesousgarantie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offre",
            name="LibelleOffre",
            field=models.CharField(
                blank=True,
                db_column="libelleoffre",
                max_length=100,
                null=True,
                verbose_name="Libellé Offre",
            ),
        ),
    ]
