# Generated by Django 4.1.4 on 2023-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0006_alter_offre_libelleoffre"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegeSante",
            fields=[
                (
                    "idcollege",
                    models.AutoField(
                        db_column="idcollege",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Collège",
                    ),
                ),
                (
                    "libellecollege",
                    models.CharField(
                        db_column="libellecollege",
                        max_length=60,
                        verbose_name="Libellé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collège",
                "verbose_name_plural": "Collèges",
                "db_table": "stdcollege",
            },
        ),
        migrations.CreateModel(
            name="LienJuridiqueSante",
            fields=[
                (
                    "codelien",
                    models.CharField(
                        max_length=1,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code Lien Juridique",
                    ),
                ),
                ("libellelien", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Lien Juridique",
                "verbose_name_plural": "Liens Juridiques",
                "db_table": "stdlienjuridique",
            },
        ),
    ]
