# Generated by Django 4.1.4 on 2023-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0007_collegesante_lienjuridiquesante"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneCouvertureSante",
            fields=[
                (
                    "idzone",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Zone Couverture",
                    ),
                ),
                (
                    "codezone",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="Code Zone Couverture"
                    ),
                ),
                (
                    "libellezone",
                    models.CharField(max_length=30, verbose_name="Nom Zone Couverture"),
                ),
            ],
            options={
                "verbose_name": "Zone de couverture",
                "verbose_name_plural": "Zones de couverture",
                "db_table": "stdzonecouverturesante",
            },
        ),
    ]
