# Generated by Django 4.1.4 on 2023-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0008_zonecouverturesante"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zonecouverturesante",
            name="libellezone",
            field=models.CharField(max_length=40, verbose_name="Nom Zone Couverture"),
        ),
    ]
