# Generated by Django 4.1.4 on 2023-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0009_alter_zonecouverturesante_libellezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="tauxtaxegarantieproduit",
            name="tauxtaxegroupe",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
