# Generated by Django 4.1.4 on 2023-04-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0010_tauxtaxegarantieproduit_tauxtaxegroupe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tauxtaxegarantieproduit",
            name="garantie",
            field=models.ForeignKey(
                db_column="idgarantie",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.sousgarantie",
                verbose_name="Garantie",
            ),
        ),
    ]
