# Generated by Django 4.1.4 on 2023-04-17 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0011_alter_tauxtaxegarantieproduit_garantie"),
    ]

    operations = [
        migrations.AddField(
            model_name="offre",
            name="TarifOffre",
            field=models.ForeignKey(
                db_column="idtarif",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.tarif",
            ),
        ),
        migrations.AddField(
            model_name="offre",
            name="ZoneCouverture",
            field=models.ForeignKey(
                db_column="idzonecouverture",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.zonecouverturesante",
            ),
        ),
    ]
