# Generated by Django 4.1.4 on 2023-04-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0012_offre_tarifoffre_offre_zonecouverture"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffreSanteParTarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdOffre", models.IntegerField()),
                ("LibelleOffre", models.CharField(max_length=80)),
                ("IdZoneCouverture", models.IntegerField(null=True)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
