# Generated by Django 4.1.4 on 2023-05-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0013_offresantepartarif"),
    ]

    operations = [
        migrations.AddField(
            model_name="offregarantie",
            name="FranchiseMaximum",
            field=models.DecimalField(
                db_column="franchisemaximum", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="offregarantie",
            name="FranchiseMinimum",
            field=models.DecimalField(
                db_column="franchiseminimum", decimal_places=4, default=0, max_digits=19
            ),
        ),
        migrations.AddField(
            model_name="offregarantie",
            name="IdCompagnie",
            field=models.ForeignKey(
                db_column="idcompagnie",
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.compagnie",
                verbose_name="Compagnie",
            ),
        ),
        migrations.AddField(
            model_name="offregarantie",
            name="TauxFranchise",
            field=models.DecimalField(
                db_column="tauxfranchise", decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
