# Generated by Django 4.1.4 on 2023-05-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0014_offregarantie_franchisemaximum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GarantiePourOffre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdGarantie", models.IntegerField()),
                ("IdSousGarantie", models.IntegerField()),
                ("CodeSousGarantie", models.CharField(max_length=5)),
                ("LibelleSousGarantie", models.CharField(max_length=100)),
                ("TauxFranchise", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "FranchiseMinimum",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "FranchiseMaximum",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("Choix", models.BooleanField()),
            ],
            options={
                "managed": False,
            },
        ),
    ]
