# Generated by Django 4.1.4 on 2023-05-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0015_garantiepouroffre"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReductionFlotte",
            fields=[
                (
                    "id_reduction_flotte",
                    models.AutoField(
                        db_column="idreductionflotte",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Réduction Flotte",
                    ),
                ),
                (
                    "nombre_minimum",
                    models.IntegerField(
                        db_column="nombreminimum", verbose_name="Nombre Minimum"
                    ),
                ),
                (
                    "nombre_maximum",
                    models.IntegerField(
                        db_column="nombremaximum", verbose_name="Nombre Maximum"
                    ),
                ),
                (
                    "taux_reduction",
                    models.DecimalField(
                        db_column="tauxreduction",
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Taux Réduction",
                    ),
                ),
                (
                    "reduction_tarifaire",
                    models.DecimalField(
                        db_column="reductiontarifaire",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Réduction Tarifaire",
                    ),
                ),
                (
                    "reduction_commerciale",
                    models.DecimalField(
                        db_column="reductioncommerciale",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Réduction Commerciale",
                    ),
                ),
                (
                    "debut_validite",
                    models.DateField(
                        db_column="debutvalidite", verbose_name="Début Validité"
                    ),
                ),
                (
                    "fin_validite",
                    models.DateField(
                        db_column="finvalidite", verbose_name="Fin Validité"
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="idproduit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "db_table": "stdreductionflotte",
            },
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("nombre_maximum__gte", models.F("nombre_minimum"))),
                name="check_nombre_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("fin_validite__gte", models.F("debut_validite"))),
                name="check_debut_validite",
            ),
        ),
    ]
