# Generated by Django 4.1.4 on 2023-05-16 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0016_reductionflotte_reductionflotte_check_nombre_minimum_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reductionflotte",
            name="check_nombre_minimum",
        ),
        migrations.RemoveConstraint(
            model_name="reductionflotte",
            name="check_debut_validite",
        ),
        migrations.AddField(
            model_name="reductionflotte",
            name="compagnie",
            field=models.ForeignKey(
                db_column="idcompagnie",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.compagnie",
                verbose_name="Compagnie",
            ),
        ),
        migrations.AlterField(
            model_name="reductionflotte",
            name="reduction_commerciale",
            field=models.DecimalField(
                db_column="reductioncommerciale",
                decimal_places=4,
                default=0,
                max_digits=19,
                verbose_name="Réduction Commerciale",
            ),
        ),
        migrations.AlterField(
            model_name="reductionflotte",
            name="reduction_tarifaire",
            field=models.DecimalField(
                db_column="reductiontarifaire",
                decimal_places=4,
                default=0,
                max_digits=19,
                verbose_name="Réduction Tarifaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("nombre_maximum__gte", models.F("nombre_minimum"))),
                name="reduction_flotte_check_nombre_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("fin_validite__gte", models.F("debut_validite"))),
                name="reduction_flotte_check_debut_validite",
            ),
        ),
    ]
