# Generated by Django 4.1.4 on 2023-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0017_remove_reductionflotte_check_nombre_minimum_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reductionflotte",
            name="reduction_commerciale",
        ),
        migrations.RemoveField(
            model_name="reductionflotte",
            name="reduction_tarifaire",
        ),
        migrations.AddField(
            model_name="reductionflotte",
            name="taux_reduction_commerciale",
            field=models.DecimalField(
                db_column="tauxreductioncommerciale",
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Réduction Commerciale",
            ),
        ),
        migrations.AddField(
            model_name="reductionflotte",
            name="taux_reduction_tarifaire",
            field=models.DecimalField(
                db_column="tauxreductiontarifaire",
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="Réduction Tarifaire",
            ),
        ),
    ]
