# Generated by Django 4.1.4 on 2023-05-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0018_remove_reductionflotte_reduction_commerciale_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("taux_reduction__gte", 0)),
                name="reduction_flotte_check_tx_red_cima",
            ),
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("taux_reduction_tarifaire__gte", 0)),
                name="reduction_flotte_check_tx_red_tarifaire",
            ),
        ),
        migrations.AddConstraint(
            model_name="reductionflotte",
            constraint=models.CheckConstraint(
                check=models.Q(("taux_reduction_commerciale__gte", 0)),
                name="reduction_flotte_check_tx_red_commerciale",
            ),
        ),
    ]
