# Generated by Django 4.1.4 on 2023-05-20 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0019_reductionflotte_reduction_flotte_check_tx_red_cima_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FormuleSecuriteRoutiere",
            fields=[
                (
                    "id_formule",
                    models.AutoField(
                        db_column="idformule",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Formule Sécurité Routière",
                    ),
                ),
                (
                    "libelle_formule",
                    models.CharField(
                        db_column="libelleformule",
                        max_length=80,
                        verbose_name="Libellé Formule",
                    ),
                ),
                (
                    "capital_deces",
                    models.DecimalField(
                        db_column="capitaldeces",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Capital Décès",
                    ),
                ),
                (
                    "capital_ipp",
                    models.DecimalField(
                        db_column="capitalipp",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Capital Infirmité Permanente",
                    ),
                ),
                (
                    "capital_ft",
                    models.DecimalField(
                        db_column="capitalft",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Capital Frais Traitement",
                    ),
                ),
                (
                    "nombre_place",
                    models.IntegerField(
                        db_column="nombreplace",
                        default=0,
                        verbose_name="Nombre de places",
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        db_column="primenette",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime Nette",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                        verbose_name="Compagnie",
                    ),
                ),
            ],
            options={
                "db_table": "stdformulesecuriteroutiere",
            },
        ),
    ]
