# Generated by Django 4.1.4 on 2023-07-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0020_formulesecuriteroutiere"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssistanceAutomobile",
            fields=[
                (
                    "id_option",
                    models.AutoField(
                        db_column="idoption",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Option",
                    ),
                ),
                (
                    "libelle_option",
                    models.CharField(
                        db_column="libelleoption",
                        max_length=50,
                        verbose_name="Libellé Option",
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        db_column="primenette",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime Nette",
                    ),
                ),
                (
                    "id_compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                        verbose_name="ID Compagnie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option d'assistance automobile",
                "verbose_name_plural": "Options d'assistance automobile",
                "db_table": "stdassistanceautomobile",
            },
        ),
    ]
