# Generated by Django 4.1.4 on 2023-07-31 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0022_avenantproduit_produit_avenants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="avenants",
        ),
        migrations.DeleteModel(
            name="AvenantProduit",
        ),
    ]
