# Generated by Django 4.1.4 on 2023-07-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0023_remove_produit_avenants_delete_avenantproduit"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvenantProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commentaires",
                    models.CharField(
                        db_column="commentaires",
                        default="",
                        max_length=100,
                        null=True,
                        verbose_name="Commentaires",
                    ),
                ),
                (
                    "flotte",
                    models.BooleanField(db_column="flotte", verbose_name="Flotte"),
                ),
                ("mono", models.BooleanField(db_column="mono", verbose_name="Mono")),
                (
                    "avenant",
                    models.ForeignKey(
                        db_column="idavenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.avenant",
                        verbose_name="ID Avenant",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="idproduit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.produit",
                        verbose_name="ID Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avenants d'un produit",
                "verbose_name_plural": "Avenants d'un produit",
                "db_table": "stdavenantproduit",
                "unique_together": {("avenant", "produit")},
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="avenants",
            field=models.ManyToManyField(
                through="configuration_api.AvenantProduit",
                to="configuration_api.avenant",
            ),
        ),
    ]
