# Generated by Django 4.1.4 on 2023-07-31 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0024_avenantproduit_produit_avenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArreteExercice",
            fields=[
                (
                    "id_arrete",
                    models.AutoField(
                        db_column="idarrete",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Arrêté Exercice",
                    ),
                ),
                (
                    "exercice",
                    models.IntegerField(
                        db_column="exercice",
                        unique=True,
                        verbose_name="Exercice d'inventaire",
                    ),
                ),
                (
                    "arriere",
                    models.DecimalField(
                        db_column="arriere",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Arriérés de l'exercice",
                    ),
                ),
                (
                    "arriere_reporte",
                    models.DecimalField(
                        db_column="arrierereporte",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Arriérés reportés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêté d'exercice",
                "verbose_name_plural": "Arrêtés d'exercice",
                "db_table": "stdarreteexercice",
            },
        ),
    ]
