# Generated by Django 4.1.4 on 2023-08-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0025_arreteexercice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ArreteExercice",
        ),
    ]
