# Generated by Django 4.1.4 on 2023-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0026_delete_arreteexercice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pays",
            name="zone",
        ),
    ]
