# Generated by Django 4.1.4 on 2023-08-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0027_remove_pays_zone"),
    ]

    operations = [
        migrations.AddField(
            model_name="zonevoyage",
            name="compagnie",
            field=models.ForeignKey(
                blank=True,
                db_column="id_compagnie",
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuration_api.compagnie",
                verbose_name="Compagnie",
            ),
        ),
        migrations.AddField(
            model_name="zonevoyage",
            name="pays",
            field=models.ManyToManyField(
                db_table="stdzonevoyagepays",
                related_name="zonesvoyage",
                to="configuration_api.pays",
            ),
        ),
    ]
