# Generated by Django 4.1.4 on 2023-08-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0028_zonevoyage_compagnie_zonevoyage_pays"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="zonevoyage",
            name="pays",
        ),
    ]
