# Generated by Django 4.1.4 on 2023-08-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("configuration_api", "0029_remove_zonevoyage_pays"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneVoyagePrime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_minimum",
                    models.PositiveIntegerField(
                        db_column="duree_minimum", verbose_name="Durée minimum"
                    ),
                ),
                (
                    "duree_maximum",
                    models.PositiveIntegerField(
                        db_column="duree_maximum", verbose_name="Durée maximum"
                    ),
                ),
                (
                    "age_minimum",
                    models.PositiveIntegerField(
                        db_column="age_minimum", verbose_name="Âge minimum"
                    ),
                ),
                (
                    "age_maximum",
                    models.PositiveIntegerField(
                        db_column="age_maximum", verbose_name="Âge maximum"
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        db_column="prime_nette",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime nette",
                    ),
                ),
                (
                    "accessoire",
                    models.DecimalField(
                        db_column="accessoire",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Accessoire",
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Taxe",
                    ),
                ),
                (
                    "prime_ttc",
                    models.DecimalField(
                        db_column="prime_ttc",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime TTC",
                    ),
                ),
                (
                    "prime_nette_ristourne",
                    models.DecimalField(
                        db_column="prime_nette_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime nette (ristourne)",
                    ),
                ),
                (
                    "taxe_ristourne",
                    models.DecimalField(
                        db_column="taxe_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Taxe (ristourne)",
                    ),
                ),
                (
                    "prime_ttc_ristourne",
                    models.DecimalField(
                        db_column="prime_ttc_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime TTC (ristourne)",
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        db_column="id_tarif",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primesvoyage",
                        to="configuration_api.tarif",
                        verbose_name="Tarif",
                    ),
                ),
                (
                    "zone_voyage",
                    models.ForeignKey(
                        db_column="id_zone",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primesvoyage",
                        to="configuration_api.zonevoyage",
                        verbose_name="Zone de voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche de prime",
                "verbose_name_plural": "Tranches de prime",
                "db_table": "stdzonevoyageprime",
            },
        ),
        migrations.CreateModel(
            name="ZoneVoyagePays",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        db_column="id_pays",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.pays",
                        verbose_name="Pays de destination",
                    ),
                ),
                (
                    "zone_voyage",
                    models.ForeignKey(
                        db_column="id_zone",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.zonevoyage",
                        verbose_name="Zone de voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation Pays - Zone",
                "verbose_name_plural": "Relations Pays - Zone",
                "db_table": "stdzonevoyagepays",
            },
        ),
        migrations.AddField(
            model_name="zonevoyage",
            name="pays",
            field=models.ManyToManyField(
                related_name="zonesvoyage",
                through="configuration_api.ZoneVoyagePays",
                to="configuration_api.pays",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprime",
            constraint=models.UniqueConstraint(
                fields=(
                    "tarif",
                    "zone_voyage",
                    "duree_minimum",
                    "duree_maximum",
                    "age_minimum",
                    "age_maximum",
                ),
                name="zone_voyage_prime_tranche_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprime",
            constraint=models.CheckConstraint(
                check=models.Q(("age_minimum__lte", models.F("age_maximum"))),
                name="zone_voyage_prime_check_age",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprime",
            constraint=models.CheckConstraint(
                check=models.Q(("duree_minimum__lte", models.F("duree_maximum"))),
                name="zone_voyage_prime_check_duree",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyagepays",
            constraint=models.UniqueConstraint(
                fields=("zone_voyage", "pays"), name="unique_zone_voyage_pays"
            ),
        ),
    ]
