# Generated by Django 4.1.4 on 2023-08-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0030_zonevoyageprime_zonevoyagepays_zonevoyage_pays_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zonevoyagepays",
            name="unique_zone_voyage_pays",
        ),
        migrations.AddConstraint(
            model_name="zonevoyagepays",
            constraint=models.UniqueConstraint(
                fields=("zone_voyage", "pays"), name="zone_voyage_pays_unique"
            ),
        ),
    ]
