# Generated by Django 4.1.4 on 2023-08-27 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0031_remove_zonevoyagepays_unique_zone_voyage_pays_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="zonevoyageprime",
            name="zone_voyage_prime_check_age",
        ),
        migrations.RemoveConstraint(
            model_name="zonevoyageprime",
            name="zone_voyage_prime_check_duree",
        ),
    ]
