# Generated by Django 4.1.4 on 2023-08-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0032_remove_zonevoyageprime_zone_voyage_prime_check_age_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="zonevoyageprime",
            constraint=models.CheckConstraint(
                check=models.Q(("age_minimum__lte", models.F("age_maximum"))),
                name="zone_voyage_prime_check_age",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprime",
            constraint=models.CheckConstraint(
                check=models.Q(("duree_minimum__lte", models.F("duree_maximum"))),
                name="zone_voyage_prime_check_duree",
            ),
        ),
    ]
