# Generated by Django 4.1.4 on 2023-08-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0033_zonevoyageprime_zone_voyage_prime_check_age_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PaysZone",
            fields=[
                (
                    "pays_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="configuration_api.pays",
                    ),
                ),
                ("id_zone", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
            bases=("configuration_api.pays",),
        ),
    ]
