# Generated by Django 4.1.4 on 2023-08-30 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0034_payszone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaysZone",
        ),
    ]
