# Generated by Django 4.1.4 on 2023-08-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0035_delete_payszone"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaysZone",
            fields=[
                (
                    "id_pays",
                    models.BigIntegerField(
                        db_column="id_pays",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Pays",
                    ),
                ),
                (
                    "libelle_pays",
                    models.CharField(
                        db_column="libelle_pays",
                        default="",
                        max_length=50,
                        verbose_name="Libellé",
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        db_column="nationalite",
                        max_length=60,
                        verbose_name="Nationalité",
                    ),
                ),
                ("id_zone", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
    ]
