# Generated by Django 4.2.4 on 2023-09-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0036_payszone"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessoire",
            name="compagnie",
            field=models.ForeignKey(
                db_column="idcompagnie",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuration_api.compagnie",
                verbose_name="Compagnie",
            ),
        ),
    ]
