# Generated by Django 4.2.4 on 2023-09-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0037_accessoire_compagnie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="accessoire",
            unique_together={("produit", "compagnie", "primemin")},
        ),
    ]
