# Generated by Django 4.2.5 on 2023-09-24 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0038_alter_accessoire_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DelaiAvisEcheance",
            fields=[
                (
                    "id_delai_avis_echeance",
                    models.AutoField(
                        db_column="iddelaiavisecheance",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Délai Avis",
                    ),
                ),
                (
                    "flotte",
                    models.PositiveIntegerField(
                        db_column="flotte",
                        default=0,
                        verbose_name="Délai pour une flotte",
                    ),
                ),
                (
                    "mono",
                    models.PositiveIntegerField(
                        db_column="mono",
                        default=0,
                        verbose_name="Délai pour un contrat mono",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        db_column="idproduit",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.produit",
                        verbose_name="Produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Délai d'avis d'échéance",
                "verbose_name_plural": "Délais d'avis d'échéance",
                "db_table": "stddelaiavisecheance",
            },
        ),
    ]
