# Generated by Django 4.2.5 on 2023-09-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0039_delaiavisecheance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametreSite",
            fields=[
                (
                    "id_parametre_site",
                    models.AutoField(
                        db_column="idparametresite",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Paramètre Site",
                    ),
                ),
                (
                    "raison_sociale",
                    models.CharField(
                        db_column="raisonsociale",
                        max_length=50,
                        verbose_name="Raison Sociale",
                    ),
                ),
                (
                    "indicatif_pays",
                    models.CharField(
                        db_column="indicatifpays",
                        max_length=3,
                        verbose_name="Indicatif Téléphonique International",
                    ),
                ),
                (
                    "longueur_numero_telephone",
                    models.PositiveSmallIntegerField(
                        db_column="longueurnumtel", verbose_name="Longueur N° Téléphone"
                    ),
                ),
                (
                    "prefixe_mobile",
                    models.CharField(
                        db_column="prefixemobile",
                        max_length=200,
                        verbose_name="Préfixe Mobile",
                    ),
                ),
                (
                    "adresse_geographique",
                    models.CharField(
                        db_column="adressegeographique",
                        default="",
                        max_length=100,
                        verbose_name="Adresse géographique",
                    ),
                ),
                (
                    "adresse_postale",
                    models.CharField(
                        db_column="adressepostale",
                        default="",
                        max_length=50,
                        verbose_name="Adresse postale",
                    ),
                ),
                (
                    "telephone_fixe",
                    models.CharField(
                        db_column="telephonefixe",
                        default="",
                        max_length=20,
                        verbose_name="Numéro Téléphone Fixe",
                    ),
                ),
                (
                    "telephone_mobile",
                    models.CharField(
                        db_column="telephonemobile",
                        default="",
                        max_length=20,
                        verbose_name="Numéro Téléphone Mobile",
                    ),
                ),
                (
                    "nom_expediteur_mobile",
                    models.CharField(
                        db_column="nomexpediteur",
                        default="",
                        max_length=11,
                        verbose_name="Nom d'expéditeur mobile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre Site",
                "db_table": "stdparametresite",
            },
        ),
    ]
