# Generated by Django 4.2.5 on 2023-09-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0040_parametresite"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametresite",
            name="longueur_prefixe_mobile",
            field=models.PositiveSmallIntegerField(
                db_column="longueurprefixemobile",
                default=2,
                verbose_name="Longueur Préfixe Mobile",
            ),
        ),
    ]
