# Generated by Django 4.2.5 on 2023-09-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0041_parametresite_longueur_prefixe_mobile"),
    ]

    operations = [
        migrations.AddField(
            model_name="delaiavisecheance",
            name="duree_contrat_maximum",
            field=models.PositiveIntegerField(
                db_column="dureecontratmaximum",
                default=31,
                verbose_name="Durée Contrat Max",
            ),
        ),
        migrations.AddField(
            model_name="delaiavisecheance",
            name="duree_contrat_minimum",
            field=models.PositiveIntegerField(
                db_column="dureecontratminimum",
                default=1,
                verbose_name="Durée Contrat Min",
            ),
        ),
        migrations.AddConstraint(
            model_name="delaiavisecheance",
            constraint=models.UniqueConstraint(
                fields=("produit", "duree_contrat_minimum"),
                name="delai_avis_echeance_unique_produit_duree",
            ),
        ),
        migrations.AddConstraint(
            model_name="delaiavisecheance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("duree_contrat_maximum__gte", models.F("duree_contrat_minimum"))
                ),
                name="delai_avis_echeance_check_duree_min_max",
            ),
        ),
    ]
