# Generated by Django 4.2.5 on 2023-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0042_delaiavisecheance_duree_contrat_maximum_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delaiavisecheance",
            name="flotte",
        ),
        migrations.RemoveField(
            model_name="delaiavisecheance",
            name="mono",
        ),
        migrations.AddField(
            model_name="delaiavisecheance",
            name="delai_flotte",
            field=models.PositiveIntegerField(
                db_column="delaiflotte", default=0, verbose_name="Délai pour une flotte"
            ),
        ),
        migrations.AddField(
            model_name="delaiavisecheance",
            name="delai_mono",
            field=models.PositiveIntegerField(
                db_column="delaimono",
                default=0,
                verbose_name="Délai pour un contrat mono",
            ),
        ),
    ]
