# Generated by Django 4.2.5 on 2024-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0043_remove_delaiavisecheance_flotte_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecteurActivite",
            fields=[
                (
                    "IdSecteurActivite",
                    models.AutoField(
                        db_column="idsecteuractivite",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Secteur Activité",
                    ),
                ),
                (
                    "Libelle",
                    models.CharField(
                        db_column="libelle",
                        max_length=100,
                        verbose_name="Libellé Secteur Activité",
                    ),
                ),
            ],
            options={
                "db_table": "stdsecteuractivite",
            },
        ),
        migrations.AddField(
            model_name="qualite",
            name="TypePersonne",
            field=models.IntegerField(
                db_column="typepersonne", default=1, verbose_name="Type Personne"
            ),
        ),
    ]
