# Generated by Django 4.2.5 on 2024-02-27 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0044_secteuractivite_qualite_typepersonne"),
    ]

    operations = [
        migrations.CreateModel(
            name="OffreCollegeSante",
            fields=[
                (
                    "idoffrecollege",
                    models.AutoField(
                        db_column="idoffrecollege",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Offre Collège",
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        db_column="idcollege",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.collegesante",
                        verbose_name="Collège",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        db_column="idoffre",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.offre",
                        verbose_name="Offre",
                    ),
                ),
            ],
            options={
                "db_table": "stdoffrecollege",
            },
        ),
        migrations.AddConstraint(
            model_name="offrecollegesante",
            constraint=models.UniqueConstraint(
                fields=("offre", "college"), name="offrecollege_unique_offre_college"
            ),
        ),
    ]
