# Generated by Django 4.2.5 on 2024-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0045_offrecollegesante_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compagnie",
            name="Active",
            field=models.BooleanField(
                db_column="active", default=True, verbose_name="Active"
            ),
        ),
    ]
