# Generated by Django 4.2.5 on 2024-03-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0046_compagnie_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeContratSante",
            fields=[
                (
                    "id_type_contrat",
                    models.AutoField(
                        db_column="idtypecontrat",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Type Contrat",
                    ),
                ),
                ("libelle", models.CharField(db_column="libelle", max_length=30)),
            ],
            options={
                "verbose_name": "Type de contrat santé",
                "verbose_name_plural": "Types de contrat santé",
                "db_table": "stdtypecontratsante",
            },
        ),
    ]
