# Generated by Django 4.2.5 on 2024-04-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0047_typecontratsante"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeGarantieRC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdOffre", models.IntegerField()),
                (
                    "CapitalDommageCorporel",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "CapitalDommageMateriel",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                (
                    "CapitalIntoxicationAlimentaire",
                    models.DecimalField(decimal_places=4, max_digits=19),
                ),
                ("AssiettePrime", models.DecimalField(decimal_places=4, max_digits=19)),
                ("TauxPrime", models.DecimalField(decimal_places=2, max_digits=5)),
                ("TauxReduction", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
