# Generated by Django 4.2.5 on 2024-04-19 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0048_demandegarantierc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SousGarantieOrdre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.IntegerField(db_column="ordre")),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                    ),
                ),
                (
                    "sous_garantie",
                    models.ForeignKey(
                        db_column="idsousgarantie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.sousgarantie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordre d'affichage des garanties",
                "db_table": "stdsousgarantieordre",
            },
        ),
        migrations.AddConstraint(
            model_name="sousgarantieordre",
            constraint=models.UniqueConstraint(
                fields=("sous_garantie", "compagnie"),
                name="unique_sousgarantie_compagnie",
            ),
        ),
    ]
