# Generated by Django 4.2.5 on 2024-04-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0049_sousgarantieordre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sousgarantieordre",
            name="libelle_sous_garantie",
            field=models.CharField(
                db_column="libellesousgarantie",
                default="",
                max_length=100,
                verbose_name="Libellé S/Garantie",
            ),
        ),
    ]
