# Generated by Django 4.2.5 on 2024-04-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0050_sousgarantieordre_libelle_sous_garantie"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnteteSousGarantie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="identete",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_entete",
                    models.CharField(
                        db_column="codeentete",
                        max_length=5,
                        unique=True,
                        verbose_name="Code Entête",
                    ),
                ),
                (
                    "libelle_entete",
                    models.CharField(
                        db_column="libelleentete",
                        max_length=100,
                        verbose_name="Libellé Entête",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                        verbose_name="Compagnie",
                    ),
                ),
            ],
            options={
                "db_table": "stdentetesousgarantie",
            },
        ),
        migrations.CreateModel(
            name="RegroupementSousGarantie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entete",
                    models.ForeignKey(
                        db_column="codeentete",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.entetesousgarantie",
                        to_field="code_entete",
                        verbose_name="Code Entête",
                    ),
                ),
                (
                    "sous_garantie",
                    models.ForeignKey(
                        db_column="idsousgarantie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.sousgarantie",
                        verbose_name="Sous-Garantie",
                    ),
                ),
            ],
            options={
                "db_table": "stdregroupementsousgarantie",
            },
        ),
        migrations.AddConstraint(
            model_name="regroupementsousgarantie",
            constraint=models.UniqueConstraint(
                fields=("entete", "sous_garantie"),
                name="regroupementsousgrantie_unique",
            ),
        ),
    ]
