# Generated by Django 4.2.5 on 2024-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0051_entetesousgarantie_regroupementsousgarantie_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="modeencaissement",
            name="ordreaffichage",
            field=models.CharField(
                blank=True, db_column="ordreaffichage", max_length=2, null=True
            ),
        ),
    ]
