# Generated by Django 4.2.13 on 2024-06-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0052_modeencaissement_ordreaffichage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoneVoyagePrimeNsia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duree_minimum",
                    models.PositiveIntegerField(
                        db_column="duree_minimum", verbose_name="Durée minimum"
                    ),
                ),
                (
                    "duree_maximum",
                    models.PositiveIntegerField(
                        db_column="duree_maximum", verbose_name="Durée maximum"
                    ),
                ),
                (
                    "age_minimum",
                    models.PositiveIntegerField(
                        db_column="age_minimum", verbose_name="Âge minimum"
                    ),
                ),
                (
                    "age_maximum",
                    models.PositiveIntegerField(
                        db_column="age_maximum", verbose_name="Âge maximum"
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        db_column="prime_nette",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime nette",
                    ),
                ),
                (
                    "accessoire",
                    models.DecimalField(
                        db_column="accessoire",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Accessoire",
                    ),
                ),
                (
                    "taxe",
                    models.DecimalField(
                        db_column="taxe",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Taxe",
                    ),
                ),
                (
                    "prime_ttc",
                    models.DecimalField(
                        db_column="prime_ttc",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime TTC",
                    ),
                ),
                (
                    "prime_nette_ristourne",
                    models.DecimalField(
                        db_column="prime_nette_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime nette (ristourne)",
                    ),
                ),
                (
                    "taxe_ristourne",
                    models.DecimalField(
                        db_column="taxe_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Taxe (ristourne)",
                    ),
                ),
                (
                    "prime_ttc_ristourne",
                    models.DecimalField(
                        db_column="prime_ttc_ristourne",
                        decimal_places=4,
                        max_digits=19,
                        verbose_name="Prime TTC (ristourne)",
                    ),
                ),
                (
                    "offre",
                    models.ForeignKey(
                        db_column="id_offre",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primesvoyagensia",
                        to="configuration_api.offre",
                        verbose_name="Offre",
                    ),
                ),
                (
                    "zone_voyage",
                    models.ForeignKey(
                        db_column="id_zone",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primesvoyagensia",
                        to="configuration_api.zonevoyage",
                        verbose_name="Zone de voyage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche de prime NSIA",
                "verbose_name_plural": "Tranches de prime NSIA",
                "db_table": "stdzonevoyageprimensia",
            },
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprimensia",
            constraint=models.UniqueConstraint(
                fields=(
                    "offre",
                    "zone_voyage",
                    "duree_minimum",
                    "duree_maximum",
                    "age_minimum",
                    "age_maximum",
                ),
                name="zone_voyage_prime_nsia_tranche_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprimensia",
            constraint=models.CheckConstraint(
                check=models.Q(("age_minimum__lte", models.F("age_maximum"))),
                name="zone_voyage_prime_nsia_check_age",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonevoyageprimensia",
            constraint=models.CheckConstraint(
                check=models.Q(("duree_minimum__lte", models.F("duree_maximum"))),
                name="zone_voyage_prime_nsia_check_duree",
            ),
        ),
    ]
