# Generated by Django 4.2.13 on 2024-10-17 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0053_zonevoyageprimensia_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntermediaireCompagnie",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "codeintermediaire",
                    models.CharField(
                        db_column="codeintermediaire",
                        max_length=10,
                        verbose_name="Code Intermediaire",
                    ),
                ),
                (
                    "numchar",
                    models.SmallIntegerField(
                        db_column="numchar", default=0, verbose_name="NumChar"
                    ),
                ),
                (
                    "seriedevis",
                    models.IntegerField(
                        blank=True,
                        db_column="seriedevis",
                        null=True,
                        verbose_name="Serie devis",
                    ),
                ),
                (
                    "seriecontrat",
                    models.IntegerField(
                        blank=True,
                        db_column="seriecontrat",
                        null=True,
                        verbose_name="Serie contrat",
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        db_column="idcompagnie",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                        verbose_name="Compagnie",
                    ),
                ),
                (
                    "intermediaire",
                    models.ForeignKey(
                        db_column="idintermediaire",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.intermediaire",
                        verbose_name="Intermediaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation Intermédiaire Compagnie",
                "verbose_name_plural": "Relations Intermédiaire Compagnie",
                "db_table": "stdintermediairecompagnie",
            },
        ),
        migrations.AddConstraint(
            model_name="intermediairecompagnie",
            constraint=models.UniqueConstraint(
                fields=("intermediaire", "compagnie"),
                name="relation_intermediaire_compagnie_unique",
            ),
        ),
    ]
