# Generated by Django 4.2.13 on 2024-10-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0054_intermediairecompagnie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediaire",
            name="numero_rccm",
            field=models.CharField(
                blank=True,
                db_column="numerorccm",
                max_length=40,
                null=True,
                verbose_name="Numéro Registre Commerce",
            ),
        ),
    ]
