# Generated by Django 4.2.13 on 2025-11-25 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0055_intermediaire_numero_rccm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genrevehicule",
            name="CodeGenre",
            field=models.CharField(
                db_column="codegenre",
                max_length=50,
                unique=True,
                verbose_name="Code Genre",
            ),
        ),
        migrations.CreateModel(
            name="DepreciationVehicule",
            fields=[
                (
                    "iddepreciation",
                    models.AutoField(
                        db_column="iddepreciation",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Dépréciation",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        db_column="taux",
                        decimal_places=2,
                        max_digits=4,
                        verbose_name="Taux de dépréciation",
                    ),
                ),
                (
                    "mois",
                    models.SmallIntegerField(
                        db_column="mois", verbose_name="Nombre de mois"
                    ),
                ),
                (
                    "genre_vehicule",
                    models.ForeignKey(
                        db_column="codegenrevehicule",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.genrevehicule",
                        to_field="CodeGenre",
                        verbose_name="Genre du véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taux de dépréciation des véhicules",
                "verbose_name_plural": "Taux de dépréciation des véhicules",
                "db_table": "stddepreciationvehicule",
            },
        ),
        migrations.AddConstraint(
            model_name="depreciationvehicule",
            constraint=models.UniqueConstraint(
                fields=("genre_vehicule", "mois"),
                name="depreciation_vehicule_mois_genre_unique",
            ),
        ),
    ]
