# Generated by Django 4.2.13 on 2025-12-17 17:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0056_alter_genrevehicule_codegenre_depreciationvehicule_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SousGarantieMRH",
            fields=[
                (
                    "code",
                    models.CharField(
                        help_text="Code spécifique MRH (ex: INCENDIE, DEGAT_EAUX, etc.)",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code sous-garantie MRH",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("OBLIGATOIRE", "Obligatoire"),
                            ("OPTIONNELLE", "Optionnelle"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "sous_garantie_std",
                    models.ForeignKey(
                        blank=True,
                        db_column="idsousgarantie",
                        help_text="Lien avec la table stdsousgarantie existante",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="config_mrh",
                        to="configuration_api.sousgarantie",
                        verbose_name="Sous-Garantie générale liée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Garantie MRH",
                "verbose_name_plural": "Sous-Garanties MRH",
                "db_table": "stdmrh_sous_garantie",
                "ordering": ["type", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="UsageHabitation",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code usage",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage habitation",
                "verbose_name_plural": "Usages habitation",
                "db_table": "stdmrh_usage_habitation",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="ParametresCalcul",
            fields=[
                (
                    "usage",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="parametres",
                        serialize=False,
                        to="configuration_api.usagehabitation",
                        verbose_name="Usage",
                    ),
                ),
                (
                    "coeff_valeur_batiment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Coefficient valeur bâtiment (‰)",
                    ),
                ),
                (
                    "coeff_valeur_contenu",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Coefficient valeur contenu (‰)",
                    ),
                ),
                (
                    "coeff_loyer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Coefficient loyer (‰)",
                    ),
                ),
                (
                    "coeff_capital_rvt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Coefficient capital RVT (‰)",
                    ),
                ),
                (
                    "coeff_reduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                        verbose_name="Coefficient de réduction",
                    ),
                ),
                (
                    "forfait_fixe",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Forfait fixe (FCFA)",
                    ),
                ),
                (
                    "param_valeur_batiment_requis",
                    models.BooleanField(
                        default=False, verbose_name="Valeur bâtiment requise"
                    ),
                ),
                (
                    "param_valeur_contenu_requis",
                    models.BooleanField(
                        default=False, verbose_name="Valeur contenu requise"
                    ),
                ),
                (
                    "param_loyer_requis",
                    models.BooleanField(default=False, verbose_name="Loyer requis"),
                ),
                (
                    "param_capital_rvt_requis",
                    models.BooleanField(
                        default=False, verbose_name="Capital RVT requis"
                    ),
                ),
                (
                    "formule_texte",
                    models.TextField(
                        blank=True, null=True, verbose_name="Formule (texte)"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de calcul",
                "verbose_name_plural": "Paramètres de calcul",
                "db_table": "stdmrh_parametres_calcul",
            },
        ),
        migrations.CreateModel(
            name="SousGarantieForfait",
            fields=[
                (
                    "sous_garantie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="forfait",
                        serialize=False,
                        to="configuration_api.sousgarantiemrh",
                        verbose_name="Garantie",
                    ),
                ),
                (
                    "prime_nette",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Prime nette (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Garantie forfait",
                "verbose_name_plural": "Sous-Garanties forfait",
                "db_table": "stdmrh_sous_garantie_forfait",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Code option",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "type_option",
                    models.CharField(
                        choices=[
                            ("GENERALE", "Générale"),
                            ("SPECIFIQUE", "Spécifique"),
                        ],
                        max_length=20,
                        verbose_name="Type d'option",
                    ),
                ),
                (
                    "type_ajustement",
                    models.CharField(
                        choices=[
                            ("TYPE1", "TYPE 1 - Taux sur prime de base"),
                            ("TYPE2", "TYPE 2 - Taux sur prime garantie"),
                            ("FORFAIT", "FORFAIT - Montant fixe"),
                        ],
                        max_length=20,
                        verbose_name="Type d'ajustement",
                    ),
                ),
                (
                    "taux_ajustement",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Taux d'ajustement",
                    ),
                ),
                (
                    "montant_forfait",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Montant forfait (FCFA)",
                    ),
                ),
                (
                    "signe_ajustement",
                    models.CharField(
                        blank=True,
                        choices=[("+", "Majoration"), ("-", "Réduction")],
                        max_length=1,
                        null=True,
                        verbose_name="Signe ajustement",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "sous_garantie_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="options_liees",
                        to="configuration_api.sousgarantiemrh",
                        verbose_name="Sous-Garantie cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option",
                "verbose_name_plural": "Options",
                "db_table": "stdmrh_option",
                "ordering": ["type_option", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="CleRepartition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_repartition",
                    models.CharField(
                        choices=[
                            ("FIXE", "Montant fixe"),
                            ("POURCENTAGE", "Pourcentage"),
                        ],
                        max_length=20,
                        verbose_name="Type de répartition",
                    ),
                ),
                (
                    "montant_fixe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Montant fixe (FCFA)",
                    ),
                ),
                (
                    "taux_pourcentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Taux pourcentage (%)",
                    ),
                ),
                (
                    "groupe",
                    models.IntegerField(
                        help_text="1 = montants fixes, 2 = pourcentages",
                        verbose_name="Groupe",
                    ),
                ),
                (
                    "ordre_calcul",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ordre de calcul"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "sous_garantie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cles_repartition",
                        to="configuration_api.sousgarantiemrh",
                        verbose_name="Garantie",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cles_repartition",
                        to="configuration_api.usagehabitation",
                        verbose_name="Usage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé de répartition",
                "verbose_name_plural": "Clés de répartition",
                "db_table": "stdmrh_cle_repartition",
                "ordering": ["usage", "groupe", "ordre_calcul"],
            },
        ),
        migrations.CreateModel(
            name="SousGarantieUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obligatoire",
                    models.BooleanField(default=True, verbose_name="Obligatoire"),
                ),
                (
                    "taux_repartition",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pourcentage de répartition de la prime de base",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Taux de répartition (%)",
                    ),
                ),
                (
                    "ordre_affichage",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Ordre d'affichage"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "sous_garantie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages_lies",
                        to="configuration_api.sousgarantiemrh",
                        verbose_name="Sous-Garantie MRH",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_garanties_liees",
                        to="configuration_api.usagehabitation",
                        verbose_name="Usage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sous-Garantie par usage",
                "verbose_name_plural": "Sous-Garanties par usage",
                "db_table": "stdmrh_sous_garantie_usage",
                "ordering": ["usage", "ordre_affichage"],
                "indexes": [
                    models.Index(
                        fields=["usage"], name="stdmrh_sous_usage_i_50df08_idx"
                    ),
                    models.Index(
                        fields=["sous_garantie"], name="stdmrh_sous_sous_ga_86e966_idx"
                    ),
                ],
                "unique_together": {("usage", "sous_garantie")},
            },
        ),
        migrations.CreateModel(
            name="OptionUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages_applicables",
                        to="configuration_api.option",
                        verbose_name="Option",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options_applicables",
                        to="configuration_api.usagehabitation",
                        verbose_name="Usage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Option par usage",
                "verbose_name_plural": "Options par usage",
                "db_table": "stdmrh_option_usage",
                "ordering": ["usage", "option"],
                "indexes": [
                    models.Index(
                        fields=["usage"], name="stdmrh_opti_usage_i_027208_idx"
                    ),
                    models.Index(
                        fields=["option"], name="stdmrh_opti_option__657988_idx"
                    ),
                ],
                "unique_together": {("option", "usage")},
            },
        ),
        migrations.AddIndex(
            model_name="option",
            index=models.Index(
                fields=["sous_garantie_cible"], name="stdmrh_opti_sous_ga_50031e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clerepartition",
            index=models.Index(fields=["usage"], name="stdmrh_cle__usage_i_857ae7_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="clerepartition",
            unique_together={("usage", "sous_garantie")},
        ),
    ]
