# Generated by Django 4.2.13 on 2025-12-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "configuration_api",
            "0057_sousgarantiemrh_usagehabitation_parametrescalcul_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usagehabitation",
            name="qualite_assure",
            field=models.CharField(
                choices=[("PROPRIETAIRE", "Propriétaire"), ("LOCATAIRE", "Locataire")],
                default="PROPRIETAIRE",
                max_length=20,
                verbose_name="Qualité Assuré",
            ),
            preserve_default=False,
        ),
        migrations.RunSQL(sql="UPDATE public.stdmrh_usage_habitation SET qualite_assure = 'LOCATAIRE' WHERE code IN ('locataire_meuble', 'locataire', 'locataire_partiel', 'logement_fonction');", reverse_sql=migrations.RunSQL.noop)
    ]
