# Generated by Django 4.2.13 on 2025-12-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0058_usagehabitation_qualite_assure"),
    ]

    operations = [
        migrations.AddField(
            model_name="usagehabitation",
            name="offre",
            field=models.ForeignKey(
                blank=True,
                db_column="idoffre",
                help_text="Lien avec la table stdoffre existante",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usage_habitation_mrh",
                to="configuration_api.offre",
                verbose_name="Offre MRH liée",
            ),
        ),
    ]
