# Generated by Django 4.2.13 on 2025-12-18 13:43

from django.db import migrations
from uranus.utils.migrations import load_sql_from_app


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0059_usagehabitation_offre"),
    ]

    operations = [
        migrations.RunSQL(sql=load_sql_from_app(__file__, 'raw/parametrage_offre_mrh.sql'), reverse_sql=migrations.RunSQL.noop)
        
    ]
