# Generated by Django 4.2.13 on 2026-02-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0060_parametrage_complement_mrh"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomaineActiviteRC",
            fields=[
                (
                    "id_domaine_activite",
                    models.AutoField(
                        db_column="iddomaineactivite",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Domaine Activité RC",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        db_column="libelle",
                        max_length=100,
                        verbose_name="Libellé Domaine Activité RC",
                    ),
                ),
            ],
            options={
                "db_table": "stddomaineactivite",
            },
        ),
        migrations.AddConstraint(
            model_name="domaineactiviterc",
            constraint=models.CheckConstraint(
                check=models.Q(("libelle__regex", "^[A-Z]+(?: [A-Z]+)*$")),
                name="chk_libelle_format",
            ),
        ),
    ]
