# Generated by Django 4.2.13 on 2026-02-14 09:41

from django.db import migrations
    
trigger = """
CREATE TRIGGER trg_normalize_libelle_stddomaineactivite
BEFORE INSERT OR UPDATE ON stddomaineactivite
FOR EACH ROW
EXECUTE FUNCTION fn_normalize_libelle();
"""

def create_trigger(apps, schema_editor):
    schema_editor.execute(trigger)

def drop_trigger(apps, schema_editor):
    schema_editor.execute("DROP TRIGGER IF EXISTS trg_normalize_libelle_stddomaineactivite ON stddomaineactivite;")

class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0061_domaineactiviterc_and_more"),
    ]


    operations = [
        migrations.RunPython(create_trigger, reverse_code=drop_trigger),
    ]

