# Generated by Django 4.2.13 on 2026-02-14 12:15
from django.db import migrations

def add_or_replace_check_constraint(apps, schema_editor):
    # Supprimer la contrainte si elle existe déjà
    schema_editor.execute("""
        ALTER TABLE stddomaineactivite
        DROP CONSTRAINT IF EXISTS chk_libelle_format;
    """)
    # Créer la nouvelle contrainte robuste
    schema_editor.execute("""
        ALTER TABLE stddomaineactivite
        ADD CONSTRAINT chk_libelle_format
        CHECK (
            libelle = upper(regexp_replace(trim(libelle), '\\s+', ' ', 'g'))
        );
    """)

def drop_check_constraint(apps, schema_editor):
    schema_editor.execute("""
        ALTER TABLE stddomaineactivite
        DROP CONSTRAINT IF EXISTS chk_libelle_format;
    """)

class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0062_trg_normalize_libelle_stddomaineactivite"),
    ]

    operations = [
        migrations.RunPython(add_or_replace_check_constraint, reverse_code=drop_check_constraint),
    ]
