# Generated by Django 4.2.13 on 2026-02-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0063_chk_libelle_format_stddomaineactivite"),
    ]

    operations = [
        migrations.AddField(
            model_name="offregarantie",
            name="OrdreAffichage",
            field=models.SmallIntegerField(
                db_column="ordreaffichage",
                default=0,
                verbose_name="Ordre d'affichage",
            ),
        ),
    ]
