# Generated by Django 4.1.4 on 2023-03-27 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("configuration_api", "0007_collegesante_lienjuridiquesante"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdherentSanteInsertionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idadherent", models.IntegerField(default=0)),
                ("devis", models.IntegerField(default=0)),
                ("outputmessage", models.CharField(default="", max_length=500)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AffilieSanteInsertionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idaffilie", models.IntegerField(default=0)),
                ("adherent", models.IntegerField()),
                ("devis", models.IntegerField()),
                ("outputmessage", models.CharField(default="", max_length=500)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FilialeSanteInsertionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idfiliale", models.IntegerField(default=0)),
                ("devis", models.IntegerField()),
                ("outputmessage", models.CharField(default="", max_length=500)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Adherent",
            fields=[
                ("idadherent", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("sexe", models.CharField(max_length=1)),
                ("cni", models.CharField(max_length=50)),
                ("vip", models.BooleanField(default=False)),
                ("adresse", models.CharField(max_length=100)),
                ("mobile1", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile2", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("dateadhesion", models.DateField(blank=True, null=True)),
                ("datesortie", models.DateField(blank=True, null=True)),
                ("actif", models.BooleanField()),
                ("datemaj", models.DateTimeField(auto_now=True, null=True)),
                (
                    "devis",
                    models.IntegerField(blank=True, db_column="iddevis", null=True),
                ),
                ("datedebutconsommation", models.DateField()),
            ],
            options={
                "verbose_name": "Adhérent",
                "verbose_name_plural": "Adhérents",
                "db_table": "stdadherent",
            },
        ),
        migrations.CreateModel(
            name="NumeroSaisieSante",
            fields=[
                (
                    "id_devis",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Numero Devis Temporaire",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                ("saisie_en_cours", models.BooleanField()),
                (
                    "operateur",
                    models.ForeignKey(
                        db_column="idoperateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de devis temporaire",
                "verbose_name_plural": "Numéros de devis temporaire",
                "db_table": "stdnumerosaisiesante",
            },
        ),
        migrations.CreateModel(
            name="FilialeSante",
            fields=[
                (
                    "idfiliale",
                    models.AutoField(
                        db_column="idfiliale",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Filiale",
                    ),
                ),
                (
                    "devis",
                    models.IntegerField(db_column="iddevis", verbose_name="Devis"),
                ),
                ("police", models.CharField(max_length=50, null=True)),
                (
                    "nomfiliale",
                    models.CharField(
                        blank=True, db_column="nom_filiale", max_length=150, null=True
                    ),
                ),
                ("actif", models.BooleanField()),
                ("datesouscription", models.DateField(db_column="date_souscription")),
                ("dateeffet", models.DateField(db_column="date_effet")),
                ("dateexpiration", models.DateField(db_column="date_expiration")),
                ("source", models.CharField(max_length=1)),
                (
                    "datemaj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        db_column="idcollege",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.collegesante",
                        verbose_name="Collège",
                    ),
                ),
                (
                    "offresante",
                    models.ForeignKey(
                        db_column="idoffresante",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="configuration_api.offre",
                        verbose_name="Offre Santé",
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        db_column="idoperateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Filiale Santé",
                "verbose_name_plural": "Filiales Santé",
                "db_table": "stdfiliale",
            },
        ),
        migrations.CreateModel(
            name="Affilie",
            fields=[
                ("idaffilie", models.AutoField(primary_key=True, serialize=False)),
                ("lien", models.CharField(max_length=1)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("cni", models.CharField(max_length=50)),
                ("datenaissance", models.DateField(blank=True, null=True)),
                ("dateadhesion", models.DateField(blank=True, null=True)),
                ("datesortie", models.DateField(blank=True, null=True)),
                ("certificat", models.BooleanField(null=True)),
                ("datectrl", models.DateField(blank=True, null=True)),
                ("matricule", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "carte_en_vigueur",
                    models.BooleanField(
                        blank=True, db_column="carte_vigueur", null=True
                    ),
                ),
                (
                    "anc_matricule",
                    models.CharField(
                        blank=True,
                        db_column="ancien_matricule",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "date_dern_demande",
                    models.DateField(
                        blank=True, db_column="date_dernier_demande", null=True
                    ),
                ),
                ("observations", models.CharField(max_length=4000)),
                ("handicape", models.BooleanField()),
                ("sexe", models.CharField(max_length=1)),
                ("actif", models.BooleanField()),
                ("primeannuelle", models.DecimalField(decimal_places=4, max_digits=19)),
                ("datemaj", models.DateTimeField(auto_now=True, null=True)),
                (
                    "devis",
                    models.IntegerField(blank=True, db_column="iddevis", null=True),
                ),
                ("datedebutconsommation", models.DateField(blank=True, null=True)),
                (
                    "adherent",
                    models.ForeignKey(
                        db_column="idadherent",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sante.adherent",
                        verbose_name="Adhérent",
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        db_column="idoperateur",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affilié",
                "verbose_name_plural": "Affiliés",
                "db_table": "stdaffilie",
            },
        ),
        migrations.AddField(
            model_name="adherent",
            name="filiale",
            field=models.ForeignKey(
                blank=True,
                db_column="idfiliale",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sante.filialesante",
            ),
        ),
        migrations.AddField(
            model_name="adherent",
            name="operateur",
            field=models.ForeignKey(
                db_column="idoperateur",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Opérateur",
            ),
        ),
    ]
