# Generated by Django 4.1.4 on 2023-03-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherent",
            name="datedebutconsommation",
            field=models.DateField(db_column="datedebutconsommation"),
        ),
        migrations.RenameField(
            model_name="adherent",
            old_name="datedebutconsommation",
            new_name="debutconsommation",
        ),
        migrations.AlterField(
            model_name="affilie",
            name="datenaissance",
            field=models.DateField(blank=True, db_column="datenaissance", null=True),
        ),
        migrations.RenameField(
            model_name="affilie",
            old_name="datenaissance",
            new_name="date_naissance",
        ),
        migrations.AlterField(
            model_name="affilie",
            name="datedebutconsommation",
            field=models.DateField(
                blank=True, db_column="datedebutconsommation", null=True
            ),
        ),
        migrations.RenameField(
            model_name="affilie",
            old_name="datedebutconsommation",
            new_name="debutconsommation",
        ),
    ]
