# Generated by Django 4.1.4 on 2023-03-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuration_api", "0009_alter_zonecouverturesante_libellezone"),
        ("sante", "0002_alter_adherent_datedebutconsommation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filialesante",
            name="zonecouverture",
            field=models.ForeignKey(
                db_column="idzonecouverture",
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="configuration_api.zonecouverturesante",
                verbose_name="Zone Couverture",
            ),
        ),
    ]
