# Generated by Django 4.1.4 on 2023-04-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0003_filialesante_zonecouverture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="affilie",
            name="observations",
        ),
        migrations.AddField(
            model_name="affilie",
            name="observations_affilie",
            field=models.CharField(
                db_column="observations", default="RAS", max_length=4000
            ),
        ),
    ]
