# Generated by Django 4.1.4 on 2023-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0004_remove_affilie_observations_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adherent",
            name="cni",
        ),
        migrations.RemoveField(
            model_name="affilie",
            name="cni",
        ),
        migrations.AddField(
            model_name="adherent",
            name="numerocni",
            field=models.CharField(
                blank=True, db_column="cni", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="numerocni",
            field=models.CharField(
                blank=True, db_column="cni", max_length=50, null=True
            ),
        ),
    ]
