# Generated by Django 4.1.4 on 2023-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0005_remove_adherent_cni_remove_affilie_cni_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="numerosaisiesante",
            name="devis_enregistre",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="numerosaisiesante",
            name="id_devis_final",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="numerosaisiesante",
            name="saisie_en_cours",
            field=models.BooleanField(default=True),
        ),
    ]
