# Generated by Django 4.1.4 on 2023-07-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0006_numerosaisiesante_devis_enregistre_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NumeroSaisieSante",
        ),
    ]
