# Generated by Django 4.1.4 on 2023-07-16 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0008_numerosaisiesante"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NumeroSaisieSante",
        ),
    ]
