# Generated by Django 4.1.4 on 2023-07-16 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sante", "0009_delete_numerosaisiesante"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeroSaisieSante",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="datecreation",
                        verbose_name="Date de création",
                    ),
                ),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="datemaj",
                        verbose_name="Date de mise à jour",
                    ),
                ),
                (
                    "saisie_en_cours",
                    models.BooleanField(
                        db_column="saisieencours",
                        default=True,
                        verbose_name="Saisie en cours",
                    ),
                ),
                (
                    "id_devis",
                    models.IntegerField(
                        db_column="iddevis", unique=True, verbose_name="ID Devis"
                    ),
                ),
                (
                    "operateur",
                    models.ForeignKey(
                        db_column="idoperateur",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Opérateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Numéro de devis temporaire",
                "verbose_name_plural": "Numéros de devis temporaire",
                "db_table": "stdnumerosaisiesante",
            },
        ),
    ]
