# Generated by Django 4.1.4 on 2023-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0010_numerosaisiesante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adherent",
            name="adresse",
        ),
        migrations.AddField(
            model_name="adherent",
            name="adresseadherent",
            field=models.CharField(
                blank=True, db_column="adresse", max_length=100, null=True
            ),
        ),
    ]
