# Generated by Django 4.1.4 on 2023-08-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0011_remove_adherent_adresse_adherent_adresseadherent"),
    ]

    operations = [
        migrations.AddField(
            model_name="affilie",
            name="montantsurprime",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="surprimeappliquee",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
