# Generated by Django 4.1.4 on 2023-08-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0012_affilie_montantsurprime_affilie_surprimeappliquee"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaisieDevisSanteEnCours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("devis", models.IntegerField()),
                ("identifiant_devis", models.CharField(max_length=70)),
                ("utilisateur", models.IntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="adherent",
            name="groupesanguinadherent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                ],
                db_column="groupesanguin",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adherent",
            name="matriculeadherent",
            field=models.CharField(
                blank=True, db_column="matricule", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="adherent",
            name="montantsurprime",
            field=models.DecimalField(
                blank=True, decimal_places=4, default=0, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="adherent",
            name="surprimeappliquee",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="affilie",
            name="groupesanguinaffilie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                ],
                db_column="groupesanguin",
                max_length=3,
                null=True,
            ),
        ),
    ]
