# Generated by Django 4.2.4 on 2023-09-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0013_saisiedevissanteencours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adherent",
            name="datenaissanceadherent",
            field=models.DateField(blank=True, db_column="datenaissance", null=True),
        ),
        migrations.AddField(
            model_name="affilie",
            name="mobile1_affilie",
            field=models.CharField(
                blank=True, db_column="mobile1", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="mobile2_affilie",
            field=models.CharField(
                blank=True, db_column="mobile2", max_length=20, null=True
            ),
        ),
    ]
