# Generated by Django 4.2.5 on 2023-09-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0014_adherent_datenaissanceadherent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adherent",
            name="fichier_piece",
            field=models.FileField(
                blank=True,
                db_column="fichierpiece",
                null=True,
                upload_to="uploads/adherents/",
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="fichier_piece",
            field=models.FileField(
                blank=True, db_column="fichierpiece", null=True, upload_to="uploads/"
            ),
        ),
    ]
