# Generated by Django 4.2.5 on 2024-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0015_adherent_fichier_piece_affilie_fichier_piece"),
    ]

    operations = [
        migrations.AddField(
            model_name="adherent",
            name="nombrepathologie_adherent",
            field=models.IntegerField(
                blank=True, db_column="nombrepathologie", default=0, null=True
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="nombrepathologie_affilie",
            field=models.IntegerField(
                blank=True, db_column="nombrepathologie", default=0, null=True
            ),
        ),
    ]
