# Generated by Django 4.2.5 on 2024-02-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0016_adherent_nombrepathologie_adherent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adherent",
            name="numerocmu_adherent",
            field=models.CharField(
                blank=True, db_column="numerocmu", default="", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="affilie",
            name="numerocmu_affilie",
            field=models.CharField(
                blank=True, db_column="numerocmu", default="", max_length=20, null=True
            ),
        ),
    ]
