# Generated by Django 4.2.5 on 2024-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0017_adherent_numerocmu_adherent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id_personne",
                    models.AutoField(
                        db_column="idpersonne", primary_key=True, serialize=False
                    ),
                ),
                ("nom", models.CharField(db_column="nom", max_length=60)),
                (
                    "prenoms",
                    models.CharField(
                        blank=True, db_column="prenoms", max_length=60, null=True
                    ),
                ),
                (
                    "piece",
                    models.FileField(
                        blank=True,
                        db_column="piece",
                        null=True,
                        upload_to="uploads/personnes",
                    ),
                ),
            ],
            options={
                "db_table": "stdpersonnetest",
            },
        ),
        migrations.AlterField(
            model_name="adherent",
            name="groupesanguinadherent",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                    ("NS", "INFO NON DISPONIBLE"),
                ],
                db_column="groupesanguin",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="fichier_piece",
            field=models.FileField(
                blank=True,
                db_column="fichierpiece",
                null=True,
                upload_to="uploads/affilies",
            ),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="groupesanguinaffilie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("O-", "O-"),
                    ("O+", "O+"),
                    ("A-", "A-"),
                    ("A+", "A+"),
                    ("B-", "B-"),
                    ("B+", "B+"),
                    ("AB-", "AB-"),
                    ("AB+", "AB+"),
                    ("NS", "INFO NON DISPONIBLE"),
                ],
                db_column="groupesanguin",
                max_length=3,
                null=True,
            ),
        ),
    ]
