# Generated by Django 4.2.5 on 2024-03-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0018_person_alter_adherent_groupesanguinadherent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherent",
            name="debutconsommation",
            field=models.DateField(
                blank=True, db_column="datedebutconsommation", null=True
            ),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="certificat",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="observations_affilie",
            field=models.CharField(
                blank=True,
                db_column="observations",
                default="RAS",
                max_length=4000,
                null=True,
            ),
        ),
    ]
