# Generated by Django 4.2.5 on 2024-03-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0019_alter_adherent_debutconsommation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffilieFn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iddevis", models.IntegerField()),
                ("idaffilie", models.IntegerField()),
                ("idadherent", models.IntegerField()),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("lien", models.CharField(max_length=1)),
                ("lienparente", models.CharField(max_length=10)),
                ("datenaissance", models.DateField()),
                ("sexe", models.CharField(max_length=1)),
                ("numerocni", models.CharField(max_length=50)),
                ("numerocmu", models.CharField(max_length=20)),
                ("groupesanguin", models.CharField(max_length=3)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
