# Generated by Django 4.2.13 on 2026-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sante", "0020_affiliefn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adherent",
            name="nom",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="adherent",
            name="prenom",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="nom",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="affilie",
            name="prenom",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="person",
            name="nom",
            field=models.CharField(db_column="nom", max_length=80),
        ),
        migrations.AlterField(
            model_name="person",
            name="prenoms",
            field=models.CharField(
                blank=True, db_column="prenoms", max_length=80, null=True
            ),
        ),
    ]
