# Generated by Django 4.1.4 on 2023-04-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BordereauEmissionInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("type_etat", models.SmallIntegerField()),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BordereauEmissionResultSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_police", models.CharField(max_length=16)),
                ("numero_quittance", models.CharField(max_length=16)),
                ("numero_avenant", models.CharField(max_length=16)),
                ("date_emission", models.DateField()),
                ("date_effet", models.DateField()),
                ("date_expiration", models.DateField()),
                ("prime_nette", models.DecimalField(decimal_places=4, max_digits=19)),
                ("accessoire", models.DecimalField(decimal_places=4, max_digits=19)),
                ("taxe", models.DecimalField(decimal_places=4, max_digits=19)),
                ("prime_ttc", models.DecimalField(decimal_places=4, max_digits=19)),
                ("id_client", models.IntegerField()),
                ("nom_client", models.CharField(max_length=125)),
                ("id_produit", models.IntegerField()),
                ("libelle_produit", models.CharField(max_length=60)),
                ("id_compagnie", models.IntegerField()),
                ("nom_compagnie", models.CharField(max_length=100)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
