# Generated by Django 4.1.4 on 2023-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatDecisionnel",
            fields=[
                (
                    "id_etat",
                    models.AutoField(
                        db_column="idetat",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Etat",
                    ),
                ),
                (
                    "libelle_etat",
                    models.CharField(
                        db_column="libelleetat",
                        max_length=255,
                        verbose_name="Libellé Etat",
                    ),
                ),
                ("actif", models.BooleanField(db_column="actif", default=True)),
            ],
            options={
                "verbose_name": "Etat (Reporting)",
                "verbose_name_plural": "Etats (Reporting)",
                "db_table": "stdetatdecisionnel",
            },
        ),
    ]
