# Generated by Django 4.1.4 on 2023-04-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_etatdecisionnel"),
    ]

    operations = [
        migrations.AddField(
            model_name="etatdecisionnel",
            name="code_etat",
            field=models.CharField(
                db_column="codeetat", max_length=3, null=True, verbose_name="Code Etat"
            ),
        ),
    ]
