# Generated by Django 4.1.4 on 2023-04-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_etatdecisionnel_code_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etatdecisionnel",
            name="code_etat",
            field=models.CharField(
                db_column="codeetat",
                max_length=3,
                unique=True,
                verbose_name="Code Etat",
            ),
        ),
    ]
