# Generated by Django 4.1.4 on 2023-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0004_alter_etatdecisionnel_code_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="etatdecisionnel",
            name="url",
            field=models.CharField(db_column="url", default="DETAIL", max_length=255),
        ),
    ]
