# Generated by Django 4.1.4 on 2023-07-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_etatdecisionnel_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtatCimaE1Emissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                (
                    "assurance_des_personnes",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "automobile_responsabilite_civile",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "automobile_autres_risques",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "incendie_et_multirisque",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "autres_dommages_aux_biens",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "responsabilite_civile",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "transport_terrestre",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "transport_maritime",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "corps",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "vie",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "capitalisation",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "ensemble",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EtatCimaE2Arrieres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercice_inventaire", models.IntegerField()),
                ("libelle", models.CharField(max_length=255)),
                (
                    "annee_souscription_moins_deux",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "annee_souscription_moins_un",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "annee_souscription",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=4, default=0, max_digits=19),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
