# Generated by Django 4.1.4 on 2023-07-26 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_etatcimae1emissions_etatcimae2arrieres"),
    ]

    operations = [
        migrations.CreateModel(
            name="RubriqueEtatCima",
            fields=[
                (
                    "id_rubrique",
                    models.AutoField(
                        db_column="idrubrique", primary_key=True, serialize=False
                    ),
                ),
                ("code_etat", models.CharField(db_column="codeetat", max_length=3)),
                (
                    "libelle_rubrique",
                    models.CharField(db_column="libellerubrique", max_length=50),
                ),
            ],
            options={
                "verbose_name": "Rubrique Etat CIMA",
                "verbose_name_plural": "Rubriques Etat CIMA",
                "db_table": "stdrubriqueetatcima",
            },
        ),
        migrations.CreateModel(
            name="LigneEtatCima",
            fields=[
                (
                    "id_ligne",
                    models.AutoField(
                        db_column="idligne", primary_key=True, serialize=False
                    ),
                ),
                (
                    "clef_colonne",
                    models.CharField(db_column="clefcolonne", max_length=50),
                ),
                (
                    "valeur_colonne",
                    models.DecimalField(
                        db_column="valeurcolonne", decimal_places=4, max_digits=19
                    ),
                ),
                (
                    "id_rubrique",
                    models.ForeignKey(
                        db_column="idrubrique",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reporting.rubriqueetatcima",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne Etat CIMA",
                "verbose_name_plural": "Lignes Etat CIMA",
                "db_table": "stdligneetatcima",
            },
        ),
    ]
