# Generated by Django 4.1.4 on 2023-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0007_rubriqueetatcima_ligneetatcima"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubriqueetatcima",
            name="libelle_rubrique",
            field=models.CharField(db_column="libellerubrique", max_length=100),
        ),
    ]
