# Generated by Django 4.1.4 on 2023-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0008_alter_rubriqueetatcima_libelle_rubrique"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LigneEtatCima",
        ),
        migrations.DeleteModel(
            name="RubriqueEtatCima",
        ),
    ]
