# Generated by Django 4.2.13 on 2026-09-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogCima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=60, verbose_name="Type d'opération (ENCAISSEMENT, EMISSION, REVERSEMENT, SINISTRE, DEROGATION)")),
                ('description', models.TextField(verbose_name="Description détaillée de l'opération")),
                ('auteur', models.CharField(max_length=100, verbose_name='Auteur / Opérateur')),
                ('statut_conformite', models.CharField(default='CONFORME', max_length=30, verbose_name='Statut de conformité')),
                ('reference_reglementaire', models.CharField(default='CIMA Art. 13', max_length=100, verbose_name='Règle CIMA')),
                ('details_json', models.JSONField(blank=True, default=dict, verbose_name="Métadonnées d'audit")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entrée Journal Audit CIMA',
                'verbose_name_plural': 'Journal Audit CIMA',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ConventionAssureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_convention', models.CharField(max_length=50, unique=True, verbose_name='Code Convention')),
                ('compagnie', models.CharField(max_length=100, verbose_name='Compagnie Partenaire')),
                ('code_partenaire', models.CharField(max_length=60, verbose_name='Code Partenaire / Intermédiaire')),
                ('delai_reversement_jours', models.IntegerField(default=30, verbose_name='Délai reversement (jours CIMA)')),
                ('plafond_delegation_sinistre', models.DecimalField(decimal_places=2, default=5000000, max_digits=14, verbose_name='Plafond délégation sinistres (FCFA)')),
                ('encaissement_delegue', models.BooleanField(default=True, verbose_name='Encaissement direct autorisé')),
                ('statut', models.CharField(default='Actif', max_length=30, verbose_name='Statut de la convention')),
                ('date_effet', models.DateField(blank=True, null=True, verbose_name="Date d'effet")),
                ('date_renouvellement', models.DateField(blank=True, null=True, verbose_name='Date de renouvellement')),
                ('commissions_branches', models.JSONField(blank=True, default=dict, verbose_name='Barème commissions par branche')),
                ('participation_beneficiaire', models.JSONField(blank=True, default=dict, verbose_name='Conditions de participation bénéficiaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Convention Assureur',
                'verbose_name_plural': 'Conventions Assureurs',
                'ordering': ['compagnie'],
            },
        ),
        migrations.CreateModel(
            name='CrmLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_lead', models.CharField(max_length=50, unique=True, verbose_name='ID Prospect')),
                ('nom_prospect', models.CharField(max_length=150, verbose_name='Nom du Prospect / Entreprise')),
                ('contact', models.CharField(blank=True, default='', max_length=150, verbose_name='Contact / Interlocuteur')),
                ('telephone', models.CharField(blank=True, default='', max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('branche', models.CharField(default='Automobile', max_length=60, verbose_name="Branche d'assurance")),
                ('prime_estimee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prime estimée (FCFA)')),
                ('statut', models.CharField(default='Nouveau', help_text='Nouveau, Qualifié, Proposition, Négociation, Gagné, Perdu', max_length=40, verbose_name='Étape Kanban')),
                ('commercial_attribue', models.CharField(default='Koffi Serge', max_length=100, verbose_name='Commercial affecté')),
                ('prochaine_action', models.TextField(blank=True, default='', verbose_name='Prochaine action requise')),
                ('date_action', models.DateField(blank=True, null=True, verbose_name="Date d'échéance action")),
                ('historique_echanges', models.JSONField(blank=True, default=list, verbose_name='Historique des échanges')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prospect CRM',
                'verbose_name_plural': 'Prospects CRM',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGED',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True, verbose_name='N° Référence Document')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre du document')),
                ('categorie', models.CharField(max_length=50, verbose_name='Catégorie CIMA (Contrat, Quittance, Sinistre, KYC, Avenant, Attestation, Convention)')),
                ('type_mime', models.CharField(default='application/pdf', max_length=60, verbose_name='Type MIME')),
                ('taille', models.CharField(default='1.2 MB', max_length=30, verbose_name='Taille')),
                ('entite_type', models.CharField(blank=True, default='contrat', max_length=50, verbose_name='Type entité rattachée')),
                ('entite_id', models.CharField(blank=True, default='', max_length=60, verbose_name="ID ou N° de l'entité")),
                ('statut_validation', models.CharField(default='Validé', max_length=40, verbose_name='Statut de conformité')),
                ('auteur', models.CharField(default='Direction Technique LE PHARE', max_length=100, verbose_name='Auteur / Opérateur')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ged/', verbose_name='Fichier numérique')),
            ],
            options={
                'verbose_name': 'Document GED',
                'verbose_name_plural': 'Documents GED',
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='SinistreDelegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sinistre', models.CharField(max_length=50, unique=True, verbose_name='N° Dossier Sinistre')),
                ('police_num', models.CharField(max_length=60, verbose_name="N° Police d'assurance")),
                ('assure_nom', models.CharField(max_length=150, verbose_name="Nom de l'assuré")),
                ('compagnie', models.CharField(max_length=100, verbose_name='Compagnie porteuse')),
                ('nature', models.CharField(max_length=150, verbose_name="Nature de l'événement")),
                ('date_survenance', models.DateField(verbose_name='Date de survenance')),
                ('date_declaration', models.DateField(verbose_name='Date de déclaration')),
                ('lieu', models.CharField(blank=True, default='', max_length=150, verbose_name='Lieu du sinistre')),
                ('montant_reclame', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant réclamé (FCFA)')),
                ('montant_indemnise', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant indemnisé (FCFA)')),
                ('statut', models.CharField(default='Déclaré', help_text='Déclaré, Expertise en cours, En attente validation, Prêt pour règlement, Réglé, Clôturé, Rejeté', max_length=50, verbose_name='Statut du sinistre')),
                ('delegation_respectee', models.BooleanField(default=True, verbose_name='Gestion sous plafond de délégation autorisée')),
                ('expert_assigne', models.CharField(blank=True, max_length=150, null=True, verbose_name="Cabinet d'expertise désigné")),
                ('pieces_justificatives', models.JSONField(blank=True, default=list, verbose_name='Checklist des pièces probantes CIMA')),
                ('recours_info', models.JSONField(blank=True, default=dict, verbose_name='Recours subrogatoire adverse')),
                ('historique_evenements', models.JSONField(blank=True, default=list, verbose_name='Journal chronologique du sinistre')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sinistre Délégué',
                'verbose_name_plural': 'Sinistres Délégués',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='CrmInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True, verbose_name='ID Client')),
                ('client_nom', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom Client')),
                ('type_interaction', models.CharField(default='Appel', max_length=50, verbose_name='Type (Appel, Email, RDV, Relance)')),
                ('auteur', models.CharField(default='Conseiller Commercial', max_length=100, verbose_name='Auteur')),
                ('resume', models.TextField(verbose_name='Compte rendu / Résumé')),
                ('date_interaction', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='institutionnel.crmlead')),
            ],
            options={
                'verbose_name': 'Interaction CRM',
                'verbose_name_plural': 'Interactions CRM',
                'ordering': ['-date_interaction'],
            },
        ),
    ]
