# Generated by Django 4.2.13 on 2026-09-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutionnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BordereauReversement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True, verbose_name='Référence Bordereau')),
                ('compagnie', models.CharField(max_length=100, verbose_name='Compagnie Partenaire')),
                ('nombre_polices', models.IntegerField(default=1, verbose_name='Nombre de contrats inclus')),
                ('montant_primes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total primes recouvrées (FCFA)')),
                ('commissions_deduites', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Commissions de courtage déduites')),
                ('net_a_reverser', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant net à reverser')),
                ('date_generation', models.DateField(auto_now_add=True, verbose_name='Date de génération')),
                ('date_echeance_30j', models.DateField(blank=True, null=True, verbose_name='Date limite légale CIMA (J+30)')),
                ('statut', models.CharField(default='En attente validation', max_length=40, verbose_name='Statut du reversement')),
                ('compte_bancaire_debit', models.CharField(default='SGCI - Compte Primes Séquestre LE PHARE', max_length=80, verbose_name='Compte bancaire')),
                ('ordre_virement_ref', models.CharField(blank=True, default='', max_length=60, verbose_name='Réf. Ordre de Virement')),
            ],
            options={
                'verbose_name': 'Bordereau de Reversement CIMA',
                'verbose_name_plural': 'Bordereaux de Reversement CIMA',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='QuittanceCima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quittance', models.CharField(max_length=60, unique=True, verbose_name='N° Quittance CIMA')),
                ('police_num', models.CharField(max_length=60, verbose_name='N° Police')),
                ('souscripteur', models.CharField(max_length=150, verbose_name='Souscripteur / Assuré')),
                ('compagnie', models.CharField(max_length=100, verbose_name="Compagnie d'assurance")),
                ('branche', models.CharField(default='Automobile', max_length=80, verbose_name='Branche')),
                ('montant_encaisse', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant encaissé (FCFA)')),
                ('mode_paiement', models.CharField(default='ESPECES', max_length=50, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, default='', max_length=100, verbose_name='Réf. Chèque/Virement/Mobile')),
                ('date_encaissement', models.DateTimeField(auto_now_add=True, verbose_name="Date & Heure d'encaissement")),
                ('mention_legale', models.TextField(default="Conformément à l'Article 13 du Code des Assurances CIMA (« Pas de prime, pas d'assurance »), la présente quittance atteste du paiement effectif de la prime et confère validité immédiate aux garanties souscrites.", verbose_name='Mention légale CIMA')),
                ('emetteur', models.CharField(default='Caisse Centrale LE PHARE', max_length=100, verbose_name='Agent émetteur')),
            ],
            options={
                'verbose_name': 'Quittance CIMA',
                'verbose_name_plural': 'Quittances CIMA',
                'ordering': ['-date_encaissement'],
            },
        ),
        migrations.AddField(
            model_name='sinistredelegue',
            name='accord_prealable_requis',
            field=models.BooleanField(default=False, verbose_name='Accord préalable de la compagnie requis (dépassement plafond)'),
        ),
        migrations.AddField(
            model_name='sinistredelegue',
            name='date_limite_instruction_cima',
            field=models.DateField(blank=True, null=True, verbose_name="Date limite légale d'offre CIMA (90 jours)"),
        ),
        migrations.AddField(
            model_name='sinistredelegue',
            name='quittance_subrogative_emise',
            field=models.BooleanField(default=False, verbose_name="Quittance d'indemnité subrogative émise (Art. 54 CIMA)"),
        ),
    ]
