# Generated by Django 4.2.5 on 2024-01-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArolitecSMSDispatching",
            fields=[
                (
                    "climsgid",
                    models.UUIDField(
                        db_column="climsgid",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant défini par le client",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        db_column="content", max_length=1000, verbose_name="Contents"
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        db_column="receiver", max_length=20, verbose_name="Receiver"
                    ),
                ),
                (
                    "charset",
                    models.CharField(
                        blank=True,
                        db_column="charset",
                        max_length=40,
                        null=True,
                        verbose_name="Charset",
                    ),
                ),
                (
                    "time_to_send",
                    models.DateTimeField(
                        blank=True,
                        db_column="timetosend",
                        null=True,
                        verbose_name="Time to send",
                    ),
                ),
                (
                    "dispatching_status",
                    models.CharField(
                        blank=True,
                        db_column="dispatchingstatus",
                        max_length=1,
                        null=True,
                        verbose_name="Dispatching Status",
                    ),
                ),
                (
                    "dispatching_error",
                    models.CharField(
                        blank=True,
                        db_column="dispatchingerror",
                        max_length=50,
                        null=True,
                        verbose_name="Dispatching Error",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="datecreated",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="datemodified",
                        verbose_name="Modified At",
                    ),
                ),
            ],
            options={
                "verbose_name": "AROLITEC SMS Dispatching",
                "verbose_name_plural": "AROLITEC SMS Dispatchings",
                "db_table": "stdarolitecsmsdispatching",
            },
        ),
        migrations.CreateModel(
            name="ArolitecSMSResponse",
            fields=[
                (
                    "response_id",
                    models.BigAutoField(
                        db_column="responseid",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Client-Generated Response ID",
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        db_column="success", default=False, verbose_name="Success"
                    ),
                ),
                (
                    "msgid",
                    models.CharField(
                        blank=True,
                        db_column="msgid",
                        max_length=40,
                        null=True,
                        unique=True,
                        verbose_name="Platform-Generated Message ID",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        blank=True,
                        db_column="receiver",
                        max_length=20,
                        null=True,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        db_column="cost",
                        decimal_places=4,
                        max_digits=19,
                        null=True,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "error",
                    models.CharField(
                        blank=True,
                        db_column="error",
                        max_length=50,
                        null=True,
                        verbose_name="Error",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="datecreated",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "date_modified",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="datemodified",
                        verbose_name="Modified At",
                    ),
                ),
                (
                    "climsgid",
                    models.ForeignKey(
                        blank=True,
                        db_column="climsgid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="responses",
                        to="messaging.arolitecsmsdispatching",
                        verbose_name="Client-generated ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AROLITEC SMS Response",
                "verbose_name_plural": "AROLITEC SMS Responses",
                "db_table": "stdarolitecsmsresponse",
            },
        ),
        migrations.CreateModel(
            name="ArolitecSMSMo",
            fields=[
                (
                    "feedback_id",
                    models.BigAutoField(
                        db_column="feedbackid",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Client-Generated Feedback ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        db_column="deliverydate", verbose_name="Delivery Date"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        db_column="feedbacktype",
                        max_length=10,
                        verbose_name="Feedback Type",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        db_column="content",
                        max_length=255,
                        verbose_name="Feedback Message",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        db_column="sender", max_length=20, verbose_name="Message Sender"
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        db_column="receiver",
                        max_length=20,
                        verbose_name="Message Recipient",
                    ),
                ),
                (
                    "msgid",
                    models.ForeignKey(
                        db_column="msgid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.arolitecsmsresponse",
                        to_field="msgid",
                        verbose_name="Platform-Generated Message ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AROLITEC SMS Mo",
                "verbose_name_plural": "AROLITEC SMS Mo",
                "db_table": "stdarolitecsmsmo",
            },
        ),
        migrations.CreateModel(
            name="ArolitecSMSAck",
            fields=[
                (
                    "feedback_id",
                    models.BigAutoField(
                        db_column="feedbackid",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Client-Generated Feedback ID",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        db_column="deliverydate", verbose_name="Delivery Date"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        db_column="feedbacktype",
                        max_length=10,
                        verbose_name="Feedback Type",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        db_column="content",
                        max_length=255,
                        verbose_name="Feedback Message",
                    ),
                ),
                (
                    "dlr",
                    models.CharField(
                        db_column="dlr",
                        max_length=3,
                        verbose_name="Code Accusé Reception",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        db_column="status", max_length=3, verbose_name="Statut Message"
                    ),
                ),
                (
                    "climsgid",
                    models.ForeignKey(
                        db_column="climsgid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.arolitecsmsdispatching",
                        verbose_name="Client-Generated Message ID",
                    ),
                ),
                (
                    "msgid",
                    models.ForeignKey(
                        db_column="msgid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="messaging.arolitecsmsresponse",
                        to_field="msgid",
                        verbose_name="Platform-Generated Message ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "AROLITEC SMS Ack",
                "verbose_name_plural": "AROLITEC SMS Ack",
                "db_table": "stdarolitecsmsack",
            },
        ),
    ]
