# Generated by Django 4.1.4 on 2023-03-21 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemandeAttestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Demande Attestation",
                    ),
                ),
                (
                    "numero_demande",
                    models.CharField(
                        blank=True,
                        db_column="numerodemande",
                        max_length=100,
                        null=True,
                        verbose_name="Numéro Demande",
                    ),
                ),
                (
                    "code_demandeur",
                    models.CharField(
                        db_column="codedemandeur",
                        max_length=100,
                        verbose_name="Code Demandeur",
                    ),
                ),
                (
                    "code_compagnie",
                    models.CharField(
                        db_column="codecompagnie",
                        max_length=100,
                        verbose_name="Code Compagnie",
                    ),
                ),
                (
                    "code_intermediaire",
                    models.CharField(
                        db_column="codeintermediaire",
                        max_length=100,
                        verbose_name="Code Intermediaire",
                    ),
                ),
                (
                    "code_acces",
                    models.CharField(
                        db_column="codeacces", max_length=100, verbose_name="Code Accès"
                    ),
                ),
                (
                    "point_vente",
                    models.CharField(
                        db_column="pointvente",
                        max_length=100,
                        verbose_name="Code Point Vente",
                    ),
                ),
                (
                    "bureau",
                    models.CharField(
                        db_column="bureau", max_length=100, verbose_name="Bureau"
                    ),
                ),
            ],
            options={
                "db_table": "stddemandeattestation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ItemDemandeAttestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Item Demande",
                    ),
                ),
                (
                    "date_demande_edition",
                    models.DateField(
                        db_column="datedemandeedition", verbose_name="Date Demande"
                    ),
                ),
                (
                    "date_souscription",
                    models.DateField(
                        db_column="datesouscription", verbose_name="Date Souscription"
                    ),
                ),
                (
                    "date_effet",
                    models.DateField(db_column="dateeffet", verbose_name="Date Effet"),
                ),
                (
                    "date_echeance",
                    models.DateField(
                        db_column="dateecheance", verbose_name="Date Echéance"
                    ),
                ),
                (
                    "genre_vehicule",
                    models.CharField(
                        db_column="genrevehicule",
                        max_length=50,
                        verbose_name="Genre Véhicule",
                    ),
                ),
                (
                    "numero_immatriculation",
                    models.CharField(
                        db_column="numeroimmatriculation",
                        max_length=10,
                        verbose_name="Numéro Immatriculation",
                    ),
                ),
                (
                    "type_vehicule",
                    models.CharField(
                        db_column="typevehicule",
                        max_length=20,
                        verbose_name="Type Véhicule",
                    ),
                ),
                (
                    "model_vehicule",
                    models.CharField(
                        db_column="modelvehicule",
                        max_length=20,
                        verbose_name="Modèle Véhicule",
                    ),
                ),
                (
                    "categorie_vehicule",
                    models.CharField(
                        db_column="categorievehicule",
                        max_length=100,
                        verbose_name="Catégorie Vehicule",
                    ),
                ),
                (
                    "usage_vehicule",
                    models.CharField(
                        db_column="usagevehicule",
                        max_length=50,
                        verbose_name="Usage Véhicule",
                    ),
                ),
                (
                    "source_energie",
                    models.CharField(
                        db_column="sourceenergie",
                        max_length=20,
                        verbose_name="Source Energie",
                    ),
                ),
                (
                    "nombre_place",
                    models.CharField(
                        db_column="nombreplace",
                        max_length=100,
                        verbose_name="Nombre Places",
                    ),
                ),
                (
                    "marque_vehicule",
                    models.CharField(
                        db_column="marquevehicule",
                        max_length=50,
                        verbose_name="Marque Véhicule",
                    ),
                ),
                (
                    "numero_chassis",
                    models.CharField(
                        db_column="numerochassis",
                        default="NA",
                        max_length=20,
                        verbose_name="Numéro Chassis",
                    ),
                ),
                (
                    "numero_moteur",
                    models.CharField(
                        db_column="numeromoteur",
                        default="NA",
                        max_length=30,
                        verbose_name="Numéro Moteur",
                    ),
                ),
                (
                    "numero_carte_brune_physique",
                    models.CharField(
                        db_column="numerocartebrunephysique",
                        max_length=50,
                        verbose_name="Numéro Carte Brune Physique",
                    ),
                ),
                (
                    "numero_rccm",
                    models.CharField(
                        db_column="numero_rccm",
                        default="NA",
                        max_length=100,
                        verbose_name="Numéro RCCM",
                    ),
                ),
                (
                    "bureau_enregistreur",
                    models.CharField(
                        db_column="bureauenregistreur",
                        default="NA",
                        max_length=50,
                        verbose_name="Bureau Enregistreur",
                    ),
                ),
                (
                    "nom_souscripteur",
                    models.CharField(
                        db_column="nomsouscripteur",
                        max_length=100,
                        verbose_name="Nom Souscripteur",
                    ),
                ),
                (
                    "type_souscripteur",
                    models.CharField(
                        db_column="typesouscripteur",
                        max_length=20,
                        verbose_name="Type Souscripteur",
                    ),
                ),
                (
                    "adresse_mail_souscripteur",
                    models.EmailField(
                        db_column="adressemailsouscripteur",
                        max_length=254,
                        verbose_name="Adresse Email Souscripteur",
                    ),
                ),
                (
                    "numero_telephone_souscripteur",
                    models.CharField(
                        db_column="numerotelephonesouscripteur",
                        max_length=20,
                        verbose_name="Numéro Téléphone Souscripteur ",
                    ),
                ),
                (
                    "boite_postale_souscripteur",
                    models.CharField(
                        db_column="boitepostalesouscripteur",
                        default="NA",
                        max_length=20,
                        verbose_name="Boîte Postale Souscripteur",
                    ),
                ),
                (
                    "type_assure",
                    models.CharField(
                        db_column="typeassure",
                        default="NA",
                        max_length=50,
                        verbose_name="Type Assuré",
                    ),
                ),
                (
                    "nom_assure",
                    models.CharField(
                        db_column="nomassure", max_length=50, verbose_name="Nom Assure"
                    ),
                ),
                (
                    "adresse_mail_assure",
                    models.EmailField(
                        db_column="adressemailassure",
                        max_length=254,
                        verbose_name="Adresse Email Assure",
                    ),
                ),
                (
                    "boite_postale_assure",
                    models.CharField(
                        db_column="boitepostaleassure",
                        default="NA",
                        max_length=20,
                        verbose_name="Boîte Postale Assure",
                    ),
                ),
                (
                    "numero_police",
                    models.CharField(
                        db_column="numeropolice",
                        max_length=50,
                        verbose_name="Numéro Police",
                    ),
                ),
                (
                    "numero_telephone_assure",
                    models.CharField(
                        db_column="numerotelephoneassure",
                        max_length=20,
                        verbose_name="Numero Téléphone Assuré",
                    ),
                ),
                (
                    "profession_assure",
                    models.CharField(
                        db_column="professionassure",
                        max_length=100,
                        verbose_name="Profession Assuré",
                    ),
                ),
                (
                    "type_point_vente_compagnie",
                    models.CharField(
                        db_column="typepointventecompagnie",
                        default="NA",
                        max_length=50,
                        verbose_name="Type Point Vente Compagnie",
                    ),
                ),
                (
                    "code_point_vente_compagnie",
                    models.CharField(
                        db_column="codepointventecompagnie",
                        max_length=50,
                        verbose_name="Code Point Vente Compagnie",
                    ),
                ),
                (
                    "denomination_point_vente_compagnie",
                    models.CharField(
                        db_column="denominationpointventecompagnie",
                        max_length=100,
                        verbose_name="Dénomination Point Vente Compagnie",
                    ),
                ),
                (
                    "rc",
                    models.CharField(
                        db_column="rc",
                        max_length=20,
                        verbose_name="Responsabilité Civile",
                    ),
                ),
                (
                    "code_nature_attestation",
                    models.CharField(
                        db_column="codenatureattestation",
                        max_length=10,
                        verbose_name="Code Nature Attestation",
                    ),
                ),
                (
                    "garantie",
                    models.CharField(
                        db_column="garantie",
                        default="NA",
                        max_length=1000,
                        verbose_name="Garantie",
                    ),
                ),
                (
                    "contrat",
                    models.CharField(
                        db_column="contrat",
                        default="NA",
                        max_length=1000,
                        verbose_name="Contrat",
                    ),
                ),
                (
                    "zone_circulation",
                    models.CharField(
                        db_column="codezonecirculation",
                        default="NA",
                        max_length=10,
                        verbose_name="Zone Circulation",
                    ),
                ),
                (
                    "date_premiere_mise_en_circulation",
                    models.DateField(
                        db_column="datepremieremiseencirculation",
                        verbose_name="Date Première Mise En Circulation",
                    ),
                ),
                (
                    "valeur_neuve",
                    models.CharField(
                        db_column="valeurneuve",
                        max_length=20,
                        verbose_name="Valeur Neuve",
                    ),
                ),
                (
                    "valeur_venale",
                    models.CharField(
                        db_column="valeurvenale",
                        max_length=20,
                        verbose_name="Valeur Vénale",
                    ),
                ),
                (
                    "montant_autres_garanties",
                    models.CharField(
                        db_column="montantautresgaranties",
                        max_length=20,
                        verbose_name="Montant Autres Garanties",
                    ),
                ),
                (
                    "montant_prime_nette_total",
                    models.CharField(
                        db_column="montantprimenettetotale",
                        max_length=20,
                        verbose_name="Montant Prime Nette Totale",
                    ),
                ),
                (
                    "montant_accessoires",
                    models.CharField(
                        db_column="montantaccessoires",
                        max_length=20,
                        verbose_name="Montant Accessoires",
                    ),
                ),
                (
                    "montant_taxes",
                    models.CharField(
                        db_column="montanttaxes",
                        max_length=20,
                        verbose_name="Montant Taxes",
                    ),
                ),
                (
                    "montant_carte_brune",
                    models.CharField(
                        db_column="montantcartebrune",
                        max_length=20,
                        verbose_name="Montant Carte Brune",
                    ),
                ),
                (
                    "fga",
                    models.CharField(
                        db_column="montantfga",
                        max_length=20,
                        verbose_name="Montant FGA",
                    ),
                ),
                (
                    "montant_prime_ttc",
                    models.CharField(
                        db_column="montantprimettc",
                        max_length=20,
                        verbose_name="Montant Prime TTC",
                    ),
                ),
            ],
            options={
                "db_table": "stditemdemandeattestation",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RetourDemAttestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id Réponse Demande",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="datecreation",
                        verbose_name="Date Création",
                    ),
                ),
                (
                    "numero_demande",
                    models.CharField(
                        db_column="numerodemande",
                        max_length=100,
                        verbose_name="Numéro Demande",
                    ),
                ),
                (
                    "statut",
                    models.IntegerField(db_column="statut", verbose_name="Statut"),
                ),
            ],
            options={
                "verbose_name": "Réponse à une demande d'attestation",
                "verbose_name_plural": "Réponses aux demandes d'attestation",
                "db_table": "stdretourdemattestation",
            },
        ),
        migrations.CreateModel(
            name="DetailRetourDemAttestation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        db_column="id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="Infos",
                    ),
                ),
                (
                    "numero_demande",
                    models.CharField(
                        db_column="numerodemande",
                        default="XXXXXXXXXX",
                        max_length=100,
                        verbose_name="Numéro Demande",
                    ),
                ),
                (
                    "statut",
                    models.IntegerField(
                        db_column="statut", default=-999, verbose_name="Statut"
                    ),
                ),
                (
                    "numero_attestation",
                    models.CharField(
                        db_column="numeroattestation",
                        max_length=20,
                        verbose_name="Numéro Attestation",
                    ),
                ),
                (
                    "numero_immatriculation",
                    models.CharField(
                        db_column="numeroimmatriculation",
                        max_length=10,
                        verbose_name="Numéro Immatriculation",
                    ),
                ),
                (
                    "numero_chassis",
                    models.CharField(
                        db_column="numerochassis",
                        max_length=20,
                        verbose_name="Numéro Chassis",
                    ),
                ),
                (
                    "date_effet",
                    models.CharField(
                        db_column="dateeffet", max_length=20, verbose_name="Date Effet"
                    ),
                ),
                (
                    "date_echeance",
                    models.CharField(
                        db_column="dateecheance",
                        max_length=20,
                        verbose_name="Date Echéance",
                    ),
                ),
                (
                    "lien_pdf",
                    models.CharField(
                        db_column="lienpdf", max_length=255, verbose_name="Lien PDF"
                    ),
                ),
                (
                    "lien_image",
                    models.CharField(
                        db_column="lienimage", max_length=255, verbose_name="Lien Image"
                    ),
                ),
                (
                    "lien_qrcode",
                    models.CharField(
                        db_column="lienqrcode",
                        max_length=255,
                        verbose_name="Lien QrCode",
                    ),
                ),
                (
                    "id_demande",
                    models.ForeignKey(
                        db_column="id_retour_demande",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="infos",
                        to="asaci.retourdemattestation",
                        verbose_name="Reponse à la demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de la réponse à une demande",
                "verbose_name_plural": "Détails des réponses aux demandes",
                "db_table": "stddetailretourdemattestation",
            },
        ),
    ]
