# Generated by Django 4.2.13 on 2026-01-17 07:47

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "production",
            "0107_contrat_taux_commission_quittance_taux_commission_and_more",
        ),
        ("configuration_api", "0060_parametrage_complement_mrh"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnulationPaiementCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Référence unique de l'annulation",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("motif", models.TextField(help_text="Motif de l'annulation")),
                (
                    "date_annulation",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date et heure de l'annulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Annulation de paiement de commission",
                "verbose_name_plural": "Annulations de paiement de commission",
                "db_table": "std_annulation_paiement_commission",
                "ordering": ["-date_annulation"],
            },
        ),
        migrations.CreateModel(
            name="CacheDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cle",
                    models.CharField(
                        db_index=True,
                        help_text="Clé unique pour identifier le cache",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "donnees",
                    models.JSONField(help_text="Données cachées au format JSON"),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        db_index=True, help_text="Date et heure d'expiration du cache"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cache de dashboard",
                "verbose_name_plural": "Caches de dashboard",
                "db_table": "std_cache_dashboard",
            },
        ),
        migrations.CreateModel(
            name="DetailAnnulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commentaire",
                    models.TextField(
                        blank=True, help_text="Commentaire spécifique pour ce détail"
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail d'annulation",
                "verbose_name_plural": "Détails d'annulation",
                "db_table": "std_detail_annulation",
            },
        ),
        migrations.CreateModel(
            name="DetailPaiementCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant_prime_reversee",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Montant de la prime reversée à la compagnie",
                        max_digits=19,
                    ),
                ),
                (
                    "taux_commission",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taux de commission en %",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "montant_commission_du",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Montant total de la commission due pour cette affaire",
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "montant_commission_paye",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Montant de la commission payée dans ce paiement",
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "est_annule",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si ce paiement a été annulé",
                    ),
                ),
                (
                    "reference_affaire",
                    models.CharField(
                        blank=True,
                        help_text="Référence de l'affaire fournie par la compagnie",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Détail de paiement de commission",
                "verbose_name_plural": "Détails de paiement de commission",
                "db_table": "std_detail_paiement_commission",
            },
        ),
        migrations.CreateModel(
            name="NotificationCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_notification",
                    models.CharField(
                        choices=[
                            ("RETARD_PAIEMENT", "Retard de paiement"),
                            ("PAIEMENT_RECU", "Paiement reçu"),
                            ("PAIEMENT_ANNULE", "Paiement annulé"),
                            ("VALIDATION_REQUISE", "Validation requise"),
                            ("ANOMALIE_DETECTEE", "Anomalie détectée"),
                        ],
                        db_index=True,
                        help_text="Type de notification",
                        max_length=30,
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        help_text="Titre de la notification", max_length=200
                    ),
                ),
                ("message", models.TextField(help_text="Message de la notification")),
                (
                    "lue",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indique si la notification a été lue",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date de création de la notification",
                    ),
                ),
                (
                    "date_lecture",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de lecture de la notification",
                        null=True,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Notification de commission",
                "verbose_name_plural": "Notifications de commission",
                "db_table": "sdt_notification_commission",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="PaiementCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        help_text="Référence unique du paiement",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        db_index=True, help_text="Date du paiement de la commission"
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Montant total du paiement",
                        max_digits=19,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente de traitement"),
                            ("TRAITE", "Traité"),
                            ("VALIDE", "Validé"),
                        ],
                        db_index=True,
                        default="EN_ATTENTE",
                        help_text="Statut du paiement",
                        max_length=20,
                    ),
                ),
                (
                    "fichier_detail",
                    models.FileField(
                        blank=True,
                        help_text="Fichier de détail fourni par la compagnie",
                        null=True,
                        upload_to="commissions/details/",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes ou commentaires sur le paiement"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paiement de commission",
                "verbose_name_plural": "Paiements de commission",
                "db_table": "std_paiement_commission",
                "ordering": ["-date_paiement", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_snapshot",
                    models.DateField(
                        db_index=True, help_text="Date du snapshot", unique=True
                    ),
                ),
                (
                    "commissions_dues_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total des commissions dues",
                        max_digits=15,
                    ),
                ),
                (
                    "commissions_payees_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total des commissions payées",
                        max_digits=15,
                    ),
                ),
                (
                    "commissions_en_attente_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total des commissions en attente",
                        max_digits=15,
                    ),
                ),
                (
                    "nombre_affaires_total",
                    models.IntegerField(help_text="Nombre total d'affaires"),
                ),
                (
                    "nombre_affaires_payees",
                    models.IntegerField(
                        help_text="Nombre d'affaires entièrement payées"
                    ),
                ),
                (
                    "nombre_affaires_non_payees",
                    models.IntegerField(help_text="Nombre d'affaires non payées"),
                ),
                (
                    "nombre_affaires_partielles",
                    models.IntegerField(
                        help_text="Nombre d'affaires partiellement payées"
                    ),
                ),
                (
                    "taux_recouvrement",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage de commissions recouvrées",
                        max_digits=5,
                    ),
                ),
                (
                    "delai_moyen_paiement_jours",
                    models.IntegerField(
                        help_text="Délai moyen entre reversement et paiement commission en jours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Snapshot de commission",
                "verbose_name_plural": "Snapshots de commission",
                "db_table": "std_snapshot_commission",
                "ordering": ["-date_snapshot"],
            },
        ),
        migrations.CreateModel(
            name="SnapshotCommissionCompagnie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commissions_dues",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant des commissions dues pour cette compagnie",
                        max_digits=15,
                    ),
                ),
                (
                    "commissions_payees",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant des commissions payées par cette compagnie",
                        max_digits=15,
                    ),
                ),
                (
                    "commissions_en_attente",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant des commissions en attente pour cette compagnie",
                        max_digits=15,
                    ),
                ),
                (
                    "nombre_affaires",
                    models.IntegerField(
                        help_text="Nombre d'affaires pour cette compagnie"
                    ),
                ),
                (
                    "delai_moyen_paiement_jours",
                    models.IntegerField(
                        help_text="Délai moyen de paiement pour cette compagnie en jours"
                    ),
                ),
                (
                    "compagnie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuration_api.compagnie",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details_compagnie",
                        to="commissions.snapshotcommission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de commission par compagnie",
                "verbose_name_plural": "Snapshots de commission par compagnie",
                "db_table": "std_snapshot_commission_compagnie",
            },
        ),
        migrations.AddIndex(
            model_name="snapshotcommission",
            index=models.Index(
                fields=["date_snapshot"], name="std_snapsho_date_sn_2f1220_idx"
            ),
        ),
        migrations.AddField(
            model_name="paiementcommission",
            name="compagnie",
            field=models.ForeignKey(
                help_text="Compagnie d'assurance qui effectue le paiement",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements_commission",
                to="configuration_api.compagnie",
            ),
        ),
        migrations.AddField(
            model_name="paiementcommission",
            name="created_by",
            field=models.ForeignKey(
                help_text="Utilisateur ayant créé le paiement",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements_commission_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationcommission",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notificationcommission",
            name="utilisateur",
            field=models.ForeignKey(
                help_text="Destinataire de la notification",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications_commission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="detailpaiementcommission",
            name="detail_reversement",
            field=models.ForeignKey(
                help_text="Ligne de reversement concernée",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details_commission",
                to="production.detailreversement",
            ),
        ),
        migrations.AddField(
            model_name="detailpaiementcommission",
            name="paiement",
            field=models.ForeignKey(
                help_text="Paiement global auquel ce détail appartient",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="commissions.paiementcommission",
            ),
        ),
        migrations.AddField(
            model_name="detailpaiementcommission",
            name="quittance",
            field=models.ForeignKey(
                help_text="Quittance concernée",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="details_commission",
                to="production.quittance",
            ),
        ),
        migrations.AddField(
            model_name="detailannulation",
            name="annulation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details_annulation",
                to="commissions.annulationpaiementcommission",
            ),
        ),
        migrations.AddField(
            model_name="detailannulation",
            name="detail_paiement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details_annulation",
                to="commissions.detailpaiementcommission",
            ),
        ),
        migrations.AddIndex(
            model_name="cachedashboard",
            index=models.Index(
                fields=["cle", "date_expiration"], name="std_cache_d_cle_675ba5_idx"
            ),
        ),
        migrations.AddField(
            model_name="annulationpaiementcommission",
            name="annule_par",
            field=models.ForeignKey(
                help_text="Utilisateur ayant effectué l'annulation",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annulations_commission",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="annulationpaiementcommission",
            name="details_annules",
            field=models.ManyToManyField(
                related_name="annulation",
                through="commissions.DetailAnnulation",
                to="commissions.detailpaiementcommission",
            ),
        ),
        migrations.AddIndex(
            model_name="snapshotcommissioncompagnie",
            index=models.Index(
                fields=["compagnie", "snapshot"], name="std_snapsho_compagn_dc97b5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="snapshotcommissioncompagnie",
            unique_together={("snapshot", "compagnie")},
        ),
        migrations.AddIndex(
            model_name="paiementcommission",
            index=models.Index(
                fields=["reference"], name="std_paiemen_referen_dc88dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiementcommission",
            index=models.Index(
                fields=["date_paiement", "statut"],
                name="std_paiemen_date_pa_c61f50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paiementcommission",
            index=models.Index(
                fields=["compagnie", "statut"], name="std_paiemen_compagn_980bcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationcommission",
            index=models.Index(
                fields=["utilisateur", "lue"], name="sdt_notific_utilisa_3c7eb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationcommission",
            index=models.Index(
                fields=["type_notification", "date_creation"],
                name="sdt_notific_type_no_54f346_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detailpaiementcommission",
            index=models.Index(
                fields=["quittance"], name="std_detail__quittan_3994f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detailpaiementcommission",
            index=models.Index(
                fields=["detail_reversement"], name="std_detail__detail__ee7bcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detailpaiementcommission",
            index=models.Index(
                fields=["est_annule"], name="std_detail__est_ann_711cc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detailpaiementcommission",
            index=models.Index(
                fields=["paiement", "est_annule"], name="std_detail__paiemen_a6f62a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="detailannulation",
            unique_together={("annulation", "detail_paiement")},
        ),
        migrations.AddIndex(
            model_name="annulationpaiementcommission",
            index=models.Index(
                fields=["reference"], name="std_annulat_referen_0e5f75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="annulationpaiementcommission",
            index=models.Index(
                fields=["date_annulation"], name="std_annulat_date_an_29fe1e_idx"
            ),
        ),
    ]
