# Generated by Django 4.2.13 on 2025-12-06 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeAutorisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[
                            ("ANNUL_ENC", "Annulation Encaissement"),
                            ("ANNUL_REV", "Annulation Reversement"),
                            ("ANNUL_CNT", "Annulation Contrat"),
                        ],
                        default="ANNUL_ENC",
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                ("objet", models.CharField(max_length=255, verbose_name="Objet")),
                ("motif", models.TextField(verbose_name="Motif")),
                (
                    "date_demande",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Date de la demande",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID de l'objet"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Métadonnées"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvée"),
                            ("REJECTED", "Rejetée"),
                            ("EXPIRED", "Expirée"),
                            ("USED", "Utilisée"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_traitement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de traitement"
                    ),
                ),
                (
                    "motif_rejet",
                    models.TextField(blank=True, verbose_name="Motif du rejet"),
                ),
                (
                    "jeton_genere",
                    models.BooleanField(default=False, verbose_name="Jeton généré"),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approbateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_traitees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approbateur",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type d'objet",
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'autorisation",
                "verbose_name_plural": "Demandes d'autorisation",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_operation",
                    models.CharField(
                        choices=[
                            ("ANNUL_ENC", "Annulation Encaissement"),
                            ("ANNUL_REV", "Annulation Reversement"),
                            ("ANNUL_CNT", "Annulation Contrat"),
                        ],
                        max_length=20,
                        verbose_name="Type d'opération",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_autorisation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission d'autorisation",
                "verbose_name_plural": "Permissions d'autorisation",
                "unique_together": {("utilisateur", "type_operation")},
            },
        ),
        migrations.CreateModel(
            name="JetonAutorisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=8, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "date_generation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de génération"
                    ),
                ),
                (
                    "date_expiration",
                    models.DateTimeField(verbose_name="Date d'expiration"),
                ),
                ("utilise", models.BooleanField(default=False, verbose_name="Utilisé")),
                (
                    "date_utilisation",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'utilisation"
                    ),
                ),
                (
                    "ip_utilisation",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP d'utilisation"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jeton",
                        to="autorisations.demandeautorisation",
                        verbose_name="Demande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jeton d'autorisation",
                "verbose_name_plural": "Jetons d'autorisation",
                "indexes": [
                    models.Index(
                        fields=["code", "utilise"], name="autorisatio_code_6b9e0c_idx"
                    ),
                    models.Index(
                        fields=["date_expiration", "utilise"],
                        name="autorisatio_date_ex_c905fc_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["statut", "date_demande"], name="autorisatio_statut_fc09e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["demandeur", "statut"], name="autorisatio_demande_cf6b74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["type_operation", "statut"],
                name="autorisatio_type_op_d6591f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="autorisatio_content_a3d875_idx",
            ),
        ),
    ]
