# Generated by Django 4.2.13 on 2025-12-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("autorisations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="demandeautorisation",
            name="autorisatio_content_a3d875_idx",
        ),
        migrations.AlterField(
            model_name="demandeautorisation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("APPROVED", "Approuvée"),
                    ("REJECTED", "Rejetée"),
                    ("EXPIRED", "Expirée"),
                    ("USED", "Utilisée"),
                    ("CANCELLED", "Annulée"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["content_type", "object_id", "statut"],
                name="autorisatio_content_1acd5f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["type_operation", "content_type", "object_id", "statut"],
                name="autorisatio_type_op_95a75a_idx",
            ),
        ),
    ]
