# Generated by Django 4.2.13 on 2025-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "autorisations",
            "0002_remove_demandeautorisation_autorisatio_content_a3d875_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["date_demande"], name="autorisatio_date_de_5dbd76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="demandeautorisation",
            index=models.Index(
                fields=["date_traitement"], name="autorisatio_date_tr_ab60c7_idx"
            ),
        ),
    ]
